### ISSUE TITLE
Questions about transplants  

### ISSUE THREAD

**Issue by surqing** [eclipse/paho.mqtt.c#1154]
There are a lot of errors in Visual Studio VC++ 2019. Is there a better solution for porting this project. Error in project common_obj "Severity code description project file line disallows showing status  
Error C2146 Syntax error: Missing ") "(before identifier" lpWSAData ") common_obj D:\Windows Kits\10\Include\10.0.19041.0\um\winsock2.h 2353  
"

**Comment by icraggs** [comment]
You can see how the Windows builds work here: https://ci.appveyor.com/project/eclipsewebmaster/paho-mqtt-c/builds/40744588

**Comment by icraggs** [comment]
I assume this is answered.
