### ISSUE TITLE
No official 1.3.9 binaries for Windows?

### ISSUE THREAD

**Issue by d5UtQvp8QQU9** [eclipse/paho.mqtt.c#1155]
Latest release [1.3.9](https://github.com/eclipse/paho.mqtt.c/releases/tag/v1.3.9) does not provide official binaries for win32 and win64. The [changelog](https://github.com/eclipse/paho.mqtt.c/milestone/16?closed=1) does not look like the windows platform has not been affected by the changes. Will there be official binaries for windows again with the next version? Sorry if "Issues" is the wrong medium to ask this question.

**Comment by icraggs** [comment]
Ah yes, I hadn't copied them across.  I have now.
