### ISSUE TITLE
Makefile has -lpthread without -pthread

### ISSUE THREAD

**Issue by tcv-git** [eclipse/paho.mqtt.c#1160]
Makefile sets `LDFLAGS_*` to include `-lpthread` without including `-pthread` in CFLAGS and LDFLAGS..

If posix threads are used then `-pthread` must be specified on both the compilation and linking steps.

**Comment by icraggs** [comment]
Why does it work as it is then?

**Comment by tcv-git** [comment]
If you drive the down the wrong side of the motorway then the wheels still go round; that doesn't mean it's a good idea :-)

`man gcc` then search for pthread is the limit of my knowledge on this subject.

**Comment by icraggs** [comment]
The doc I've found says that the -pthread option covers the use of -lpthread, so only -pthread is needed.  

It also says it's platform specific, so if I change it I wouldn't be surprised if then it fails on some platform or other - in fact I had a vague memory that that's what happened.  I can change it to -pthread and then see if anyone complains.
