### ISSUE TITLE
What is the correct way to use secure connection?

### ISSUE THREAD

**Issue by KuanL1u** [eclipse/paho.mqtt.c#1162]
**Describe the bug**
Not able to establish a TLS connection with broker.

**To Reproduce**
1. I followed this [link ](https://www.hivemq.com/docs/hivemq/4.6/user-guide/howtos.html)and 
- Generated a server side certificate for HiveMQ
- Generated a PEM client certificate

2. Run the command
`paho_c_sub.exe -t test -c ssl://localhost:8883 --cafile hivemq-server-cert.pem`
paho_c_sub.exe is the util from this github repro. 
I also tried the command like
`paho_c_sub.exe -t test -c ssl://localhost:8883 --capath "<xxxx>\mqtt\hivemq\certs" --cafile hivemq-server-cert.pem`
and other combinations but neither worked.

3. The error message is 
`Connect failed, rc Failure`
I cannot get a useful error message to figure out the correct way to use it.

**Screenshots**
![image](https://user-images.githubusercontent.com/22803967/137545729-2676af7d-cb9a-4ab3-ab1d-402f499fb81c.png)

**Environment (please complete the following information):**
 - OS: WIN10

**Additional context**
It works with Paho Java.

I attched the .jks, .pem and .crt files here.
[attach.zip](https://github.com/eclipse/paho.mqtt.c/files/7355741/attach.zip)

**Comment by icraggs** [comment]
You can get the TLS status messages by adding the --trace protocol option to the sample program command line.

**Comment by KuanL1u** [comment]
Hi Ian,

Thank you for your response! I eventually make it work now.

I used the --trace protocol option and I found that the root cause of my issue: the certificate I used does not match the given host name "localhost". So I added the "--insecure" flag to make it work. And it works well now!

Thanks for your help!
Kuan
