### ISSUE TITLE
MQTTV5: Callback set on MQTTAsync_setDisconnected not called when the MQTT broker (mosquitto) is terminated

### ISSUE THREAD

**Issue by BinduRao2018** [eclipse/paho.mqtt.c#1163]
The callback set using MQTTAsync_setDisconnected() is not called when the MQTT broker (mosquitto) is terminated ('Disconnect_Req' from mqtt). However, calls callback on onFailure.

**Scenario to reproduce**
Step1: Here is the program - 

static void onConnectFailure(void* context, MQTTAsync_failureData* response)
{
  printf ("connection failure\n");
}

static void onConnectSuccess(void* context, MQTTAsync_successData* response)
{
  printf ("connection successful\n");
}

static void TestMQTTAsync_Connected(void* context, char* cause)
{
  printf ("Connected\n");
}

static void TestMQTTAsync_Disconnected(void* context, MQTTProperties* properties, enum MQTTReasonCodes reasonCode)
{
  printf ("Disconnected\n");
}
int main (void)
{
  int rc = -1;
  MQTTAsync client;

  MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;
  MQTTAsync_createOptions create_opts = MQTTAsync_createOptions_initializer;
  MQTTAsync_disconnectOptions opts = MQTTAsync_disconnectOptions_initializer;

  rc = MQTTAsync_createWithOptions (&client, ADDRESS, CLIENTID, MQTTCLIENT_PERSISTENCE_NONE, NULL, &create_opts);
  {
    conn_opts.keepAliveInterval = 10;
    conn_opts.cleansession = 0;
    conn_opts.automaticReconnect = 1;
    conn_opts.minRetryInterval = 1; // in secs - min retryinterval for reconnect
    conn_opts.maxRetryInterval = 1; // in secs - max retryinterval for reconnect
    conn_opts.connectTimeout = 30; //in secs - Timeout for initial connection
    conn_opts.automaticReconnect = 1;
    conn_opts.onFailure = onConnectFailure;
    conn_opts.onSuccess = onConnectSuccess;

    MQTTAsync_setConnected (client, NULL, TestMQTTAsync_Connected);
    MQTTAsync_setDisconnected (client, NULL, TestMQTTAsync_Disconnected);

    if ((rc = MQTTAsync_connect(client, &conn_opts)) == MQTTASYNC_SUCCESS)
    {
      int counter = 0;
      while (counter < 10)
      {
        sleep (5);
        counter++;
      }
      printf ("calling MQTTAsync_disconnect");
      rc = MQTTAsync_disconnect (client, &opts);
      sleep (10);
    }
  }
  return rc;
}

Step2: Start mosquitto broker and run the program.
Step3: When the client connects to the broker, terminate the broker and restart

-----------
output:
----------
connection successful
Connected
connection failure
connection failure
Connected
calling MQTTAsync_disconnect

**Expected behavior**
connection successful
Connected
Disconnected
Connected
calling MQTTAsync_disconnect

** Environment (please complete the following information):**
 - OS: Linux
 - Version 20.04

**Comment by icraggs** [comment]
As the documentation for the callback says "This is a callback function, which will be called when the client library receives a disconnect packet."  

This won't happen for MQTT 3.1.1 as the server cannot send a disconnect packet, so only applies to MQTT 5.0.

**Comment by BinduRao2018** [comment]
I tried with MQTT 5.0 client. i.e. set the MQTTVersion to 5 in the 'create' and 'connect' options.
MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer5;
MQTTAsync_createOptions create_opts = MQTTAsync_createOptions_initializer5;

However, I see the same output. 

Additional information:
Using Mosquitto broker 2.0.12 with the default configuration
Executing on Dell precision tower 3420
Using Wireshark, I see the 'disconnect_req' packet from the server.

**Comment by icraggs** [comment]
Maybe the disconnect packet didn't reach the client.  A client library trace as described in the readme would show more (minimum level).

**Comment by icraggs** [comment]
I should say that if you want to know when the connection has ended, that's what the connectionLost callback is for and works on MQTT 3.1.1 and MQTT 5.0.  The disconnected callback is specifically to supply information received in the MQTT 5.0 disconnect packet sent from the server.

**Comment by BinduRao2018** [comment]
There are 3 callbacks related to the end of the connection - ConnectFailure, ConnectionLost and Disconnected. Is it ok to subscribe to all these callbacks at the same time? Do these callbacks run on the same thread?

**Comment by icraggs** [comment]
You can set functions for all the callbacks, yes.  The callbacks run on one of two internal threads, but shouldn't be called at the same time.  They each have different purposes:

1. ConnectFailure - to report the failure of a connect command.  Will only be called once for each connect call.  It's not called if ConnectSuccess is called as a result of the connect command.
2. ConnectionLost - called whenever the connection state changes from connected to disconnected.
3. Disconnected - called only when an MQTT 5.0 disconnect packet is received, to report on the contents of that packet.

**Comment by BinduRao2018** [comment]
Thanks for the clarification. I am seeing issues with ConnectFailure and Disconnected. I get ConnectFailure when the MQTT broker is terminated, but there is no Disconnected callback. I will enable traces as suggested and get back

**Comment by BinduRao2018** [comment]
I have tried to reproduce the issue where the Disconnect callback is not called with the given sample MQTTAsync_publish initialized with MQTTVersion5.
Here is the code with changes to enable reconnect and initialized to MQTTVersion5
[MQTTAsync_publish..txt](https://github.com/eclipse/paho.mqtt.c/files/7499239/MQTTAsync_publish.txt)

Steps to reproduce:
- Start the MQTT Broker and execute the sample
- Terminate the MQTT Broker
    Expected: onDisconnect callback

Output seen:

=========================================================
                   Trace Output
Product name: Eclipse Paho Asynchronous MQTT C Client Library
Version: 1.3.9
Build level: 2021-11-08T18:14:54Z
/proc/version: Linux version 5.4.0-89-generic (buildd@lgw01-amd64-044) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021

=========================================================
Waiting for publication of Hello World!
on topic MQTT Examples for client with ClientID: ExampleClientPub
connected

Connection lost
     cause: (null)
connected


PS: Following compilation options are used to build paho-mqtt client:
-DPAHO_BUILD_SAMPLES=TRUE -DPAHO_HIGH_PERFORMANCE=TRUE -DPAHO_WITH_SSL=TRUE -DCMAKE_BUILD_TYPE=Debug
