### ISSUE TITLE
Paho-c working procedure with p12 certificates

### ISSUE THREAD

**Issue by ghost** [eclipse/paho.mqtt.c#1165]
Hi,
i am question about how to use p12 encypted certificate together with the paho-c library. Does they need to be converted into crt files and keys.

Thanks

**Comment by icraggs** [comment]
I'm no expert on this, but it's an OpenSSL question.  A quick search highlights the OpenSSL pkcs12 utility which can be used to convert files - https://www.openssl.org/docs/man1.0.2/man1/pkcs12.html.   The information I've found leads me to believe that you have to convert them - that was certainly the case with older Java SSL file formats.

**Comment by icraggs** [comment]
I think this is answered.
