### ISSUE TITLE
connected or error callback never called when reconnecting after keepalive timeout

### ISSUE THREAD

**Issue by sandro97git** [eclipse/paho.mqtt.c#1172]
**Describe the bug**
When the client does not receive a PINGRESP during the keepalive interval a callback for the subsequent MQTTAsync_connect call is never called.

According to the attached trace I assume that the keepalive timeout adds a DISCONNECT command to the queue (highlighted yellow).
After that the server closes the connection which is dicovered inside MQTTAsync_cycle and leads to firing the connection lost callback (highlighted red).
This leads to a reconnect (green) which is then aborted due to the DISCONNECT command being handled while connecting (blue).

**To Reproduce**

1. In the message arrived callback add a sleep time greater than 1.5 x keepalive timeout
2. In the connection_lost callback call MQTTASync_connect

**Expected behavior**
The reconnect should either trigger the connected callback or the error callback.

**Log files**
[paho-log.pdf](https://github.com/eclipse/paho.mqtt.c/files/7474923/paho-log.pdf)

** Environment (please complete the following information):**
 - OS: Linux
 - Version 1.3.8

**Comment by icraggs** [comment]
Your application should not spend a lot of time in any callback.  Sleeping for any time at at all is likely to cause issues and should not be done, certainly if it's longer than the keepalive interval as it will block other operations.

In the handling of PING timeouts, version 1.3.9 contained some changes, and there are also some in the develop branch which will be in the next release.

**Comment by icraggs** [comment]
I tried this scenario with the latest develop branch, by altering the test broker (paho.mqtt.testing) to not respond to a pingreq with a pingresp, and using the altered sample attached:

[MQTTAsync_publish.c.zip](https://github.com/eclipse/paho.mqtt.c/files/7490520/MQTTAsync_publish.c.zip)

and it worked as expected for me.

**Comment by sandro97git** [comment]
Thanks for the fast response. I repeated my test with v1.3.9 and it worked as expected. Client disconnected and connected again.
