### ISSUE TITLE
Check for working C compiler: /usr/bin/cc -- broken for gcc or g++

### ISSUE THREAD

**Issue by chalamareddu** [eclipse/paho.mqtt.c#1173]
-- The C compiler identification is GNU 10.3.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - broken
CMake Error at /usr/share/cmake/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /paho.mqtt.c-1.3.9/build/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/make -f Makefile cmTC_5efa6/fast && /usr/bin/make  -f CMakeFiles/cmTC_5efa6.dir/build.make CMakeFiles/cmTC_5efa6.dir/build
    make: /usr/bin/make: Operation not permitted
    make: *** [Makefile:127: cmTC_5efa6/fast] Error 127

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:21 (PROJECT)

-- Configuring incomplete, errors occurred!
See also "/paho.mqtt.c-1.3.9/build/CMakeFiles/CMakeOutput.log".
See also "/paho.mqtt.c-1.3.9/build/CMakeFiles/CMakeError.log".

This is what I am getting error when I build docker with alpine:3.14 version

**Comment by icraggs** [comment]
I searched for a solution for you, which could be this: https://stackoverflow.com/questions/53633705/cmake-the-c-compiler-is-not-able-to-compile-a-simple-test-program/53635241

**Comment by icraggs** [comment]
I think this is answered.

**Comment by AuberDjine** [comment]
> I think this is answered.

Thanks for your Answer, but I already stumbled uppon that Post and it didnt help
