### ISSUE TITLE
automaticReconnect with synchronous library

### ISSUE THREAD

**Issue by destroyedlolo** [eclipse/paho.mqtt.c#1175]
Hello,

It seems to me that automaticReconnect is only available for asynchronous library but not synchronous one.

What is the safe way to reconnect in case of disconnect ?

Thanks

Laurent

**Comment by icraggs** [comment]
Use the connectionLost callback to start a connect process, which at its simplest is calling connect..

**Comment by destroyedlolo** [comment]
Thanks for your reply.
It's meaning that I have to redo submission as well ?

**Comment by icraggs** [comment]
Submission?  You mean sending of messages?  If you are using QoS > 0,  cleansession=false,  and persistence, then resending of outstanding messages should be done for you.

**Comment by destroyedlolo** [comment]
Sorry, I means subscribed topics.

**Comment by icraggs** [comment]
Subscriptions are saved as long as you have connected cleansession=false every time.

If cleansession=true, the session is cleaned up on connect and disconnect, including subscriptions.

**Comment by destroyedlolo** [comment]
Ok, thanks for explanation (and paho.mqtt.c as well :) )
