### ISSUE TITLE
Question: Last Will Delay - How to implement

### ISSUE THREAD

**Issue by ghost** [eclipse/paho.mqtt.c#1178]
Hello, 
I want to implement the last will delay feature to my API using the paho framework. 

Inside the test95.c there is testcase "test1" where I think found the approach to go by. 
[https://github.com/eclipse/paho.mqtt.c/blob/3b7ae6348bc917d42c04efa962e4868c09bbde9f/test/test95.c#L573-L592](https://github.com/eclipse/paho.mqtt.c/blob/3b7ae6348bc917d42c04efa962e4868c09bbde9f/test/test95.c#L573-L592)

To me it seems that you have to do something like this the enable the last will delay: 
```
MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;		

MQTTProperties Init_willProperties = MQTTProperties_initializer;
			
MQTTProperty LastWillDelayProp;
			
LastWillDelayProp.identifier = MQTTPROPERTY_CODE_WILL_DELAY_INTERVAL;
LastWillDelayProp.integer4 = 120;
MQTTProperties_add(&Init_willProperties, &LastWillDelayProp) 
			
conn_opts.willProperties = &Init_willProperties;
```
I found out, that the session expiry interval should be set accordingly when using the last will delay feature. 
=> Assuming SessionExpiryInterval >= WillDelayInterval

```
MQTTProperties Init_connectProperties = MQTTProperties_initializer;
			
MQTTProperty SessionExpiryProp;
			
SessionExpiryProp.identifier = MQTTPROPERTY_CODE_SESSION_EXPIRY_INTERVAL; 
SessionExpiryProp.integer4 = 120; 
MQTTProperties_add(&Init_connectProperties, &SessionExpiryProp) 
			
conn_opts.connectProperties = &Init_connectProperties;
```

My questions now are: 
Is this approach correct? Or at least the way to go? 
When do I have to free the properties? In the testcase mentioned above, the properties are freed after a successful connection. 
Will the usage of the modified "conn_opts" on my connect call MQTTAsync_connect() be enough to enable the feature? 
 
I hope my questions are understandable. 
Looking forward to your answers. 

best regards 
Fabian

**Comment by ghost** [comment]
I found out, that also the MQTTVersion information has to be set in the create and connect methods for these options to work as expected. Otherwise you will get the MQTTASYNC_WRONG_MQTT_VERSION or MQTTASYNC_BAD_MQTT_OPTION

**Comment by icraggs** [comment]
The will delay feature is only in MQTT 5 not 3.1.1, so you can see from test95.c that the connect options have to be set to:

    MQTTAsync_connectOptions opts = MQTTAsync_connectOptions_initializer5;

to connect at MQTT 5.  

Apart from the MQTT 5 specification, one of the great resources on MQTT 5 is the HiveMQ blog: https://www.hivemq.com/blog/mqtt5-essentials-part4-session-and-message-expiry/

The properties object can be freed after the call the MQTTAsync_connect.

You can also look at the command line utility programs (paho_c_sub/paho_c_pub) as they work with MQTT 5 as well as 3.1.1.

**Comment by ghost** [comment]
Thanks. I will use the _initializer5 for my application.
