### ISSUE TITLE
PahoMqttC crashes when linking paho-mqtt3as-static but not when linking paho-mqtt3as

### ISSUE THREAD

**Issue by cuttlfish** [eclipse/paho.mqtt.c#1180]
**Describe the bug**
PahoMqttC crashes when linking paho-mqtt3as-static but not when linking paho-mqtt3as

**To Reproduce**
Take a library trace as outlined in the README, and/or have a program or describe the steps to reproduce the behavior:
Library crashes as soon as one call to MQTTAsync_sendMessage
Backtrace:
#0  ListUnlink (aList=0x31718 <state>, content=0xb5201670, callback=0x0, freeContent=1) at /local/users/dliu/22/gstreamer/samples/mink/out/_deps/paho-src/src/LinkedList.c:214
214     /local/users/dliu/22/gstreamer/samples/mink/out/_deps/paho-src/src/LinkedList.c: No such file or directory.
[Current thread is 1 (LWP 20662)]
(gdb) bt
#0  ListUnlink (aList=0x31718 <state>, content=0xb5201670, callback=0x0, freeContent=1) at /local/users/dliu/22/gstreamer/samples/mink/out/_deps/paho-src/src/LinkedList.c:214
#1  0x00024bb4 in ListRemove (aList=0x31718 <state>, content=0xb5201670) at /local/users/dliu/22/gstreamer/samples/mink/out/_deps/paho-src/src/LinkedList.c:259
#2  0x00018fe6 in MQTTProtocol_removePublication (p=0xb5201670) at /local/users/dliu/22/gstreamer/samples/mink/out/_deps/paho-src/src/MQTTProtocolClient.c:296
#3  0x00019d1e in MQTTProtocol_handlePubcomps (pack=0xb5202060, sock=4) at /local/users/dliu/22/gstreamer/samples/mink/out/_deps/paho-src/src/MQTTProtocolClient.c:640
#4  0x000182c4 in MQTTAsync_cycle (sock=0xb5bd7e14, timeout=1000, rc=0xb5bd7e18) at /local/users/dliu/22/gstreamer/samples/mink/out/_deps/paho-src/src/MQTTAsyncUtils.c:2947
#5  0x0001653e in MQTTAsync_receiveThread (n=0xce6b0) at /local/users/dliu/22/gstreamer/samples/mink/out/_deps/paho-src/src/MQTTAsyncUtils.c:1977
#6  0xb6bbb796 in ?? () from /lib/libpthread.so.0

**Expected behavior**
Not crash

**Log files**
Paho Log:
20211202 173909.716 4 ExampleClientSub -> PUBLISH msgid: 2 qos: 2 retained: 0 rc 0 payload len(22): {"count":0,"boxes":[
20211202 173909.722 4 ExampleClientSub <- PUBLISH msgid: 0 qos: 0 retained: 0 payload len(0):
20211202 173909.823 4 ExampleClientSub <- PUBREC msgid: 2
20211202 173909.823 4 ExampleClientSub -> PUBREL msgid: 2 (0)
20211202 173910.023 4 ExampleClientSub <- PUBCOMP msgid:2

** Environment (please complete the following information):**
 - OS: Linux
 - Version v1.39

**Additional context**

**Comment by icraggs** [comment]
All the CI tests run when linked statically and they certainly do send and receive messages, so I think there's something more going on.  I would need a test program or more of the library log (attached as a file, not pasted please).

**Comment by icraggs** [comment]
More info needed.
