### ISSUE TITLE
MQTT can't publish and receive message after SSL disconnected

### ISSUE THREAD

**Issue by adgiczone** [eclipse/paho.mqtt.c#1183]
Hi, I find a bug about publish and receive message with ssl, it happed with these steps:
 1. Publish and receive message frequently, message size is 1629 bytes
 2. After a period of time. MQTT client disconnect because ssl is disconnected. 
 3.  It will be reconnected soon and the server can receive the keep_alive msg, but the MQTT message cannot be received and published to the server.

We use synchronous client, MQTT client version is 1.3.9 and merged [this PR](https://github.com/eclipse/paho.mqtt.c/pull/1131l)
Log file is here. [err.log](https://github.com/eclipse/paho.mqtt.c/files/7674556/err.log)

I will keep track of this issue, and update this with new findings

**Comment by icraggs** [comment]
There's not enough information in that log to say what is going on.  It's at the protocol level (need minimum) and it just shows some messages apparently being published successfully.  More information about any actual error, either at the client side or on the broker side is needed.

**Comment by adgiczone** [comment]
This bug occurs infrequently, and we have set protocol level to minimum to try to reproduce it. it may take some time.

**Comment by adgiczone** [comment]
It happened again. there is a [err2.log](https://github.com/eclipse/paho.mqtt.c/files/7684891/err2.log) of when it happened. It seems like after reconnect, ssl can't get ready socket. I add a new log and find in isReady function , FD_ISSET(socket, read_set) is false. I will set protocol level to max and update more information.

**Comment by icraggs** [comment]
I don't think max trace level won't help any more than this one.  I don't think this shows anything wrong again - there are regular messages going out apparently fine.

You said "but the MQTT message cannot be received" - received by what from where?  Is this from an MQTT subscription?  If so, do you know the broker is sending out a message?  Have you re-issued the subscription or connected cleansession=false when reconnecting?

**Comment by adgiczone** [comment]
> received by what from where? Is this from an MQTT subscription

Yes, before disconnect, it has subscribe a topic and will receive msg after publish message.

> connected cleansession=false when reconnecting?

Yes, we reconnected with cleansession=false.

> do you know the broker is sending out a message?

I'm sure  broker will sending message to our clients after they publish message. But I have no confirmation that broker is sending out message in this condition. I will verify this the next time this happens

**Comment by adgiczone** [comment]
> received by what from where? Is this from an MQTT subscription

Yes, before disconnect, it has subscribe a topic and will receive msg after publish message.

> connected cleansession=false when reconnecting?

Yes, we reconnected with cleansession=false.

> do you know the broker is sending out a message?

I'm sure  broker will sending message to our clients after they publish message. But I have no confirmation that broker is sending out message in this condition. I will verify this the next time this happens

**Comment by icraggs** [comment]
A couple of things you could try:

- checking the sessionPresent flag when you reconnect to make sure that there is a session you are reconnecting to.
- resubscribing on reconnect to see if that makes a difference

**Comment by adgiczone** [comment]
there has a result:

**Comment by adgiczone** [comment]
There I report the result.

**Comment by adgiczone** [comment]
There I report the result:

1. clean_session is zero, once client is disconnect because keepalive timeout or other reasons. mqtt can resubscribing all topic before disconnection when reconnecting.
2. clean_session is zero, If client is disconnect because ssl  disconnect, MQTT will lost all topics  before disconnection when reconnecting,  and we have to resubscribe these topics manually.
3. We run connect function in callback function, and resubscribe topics in another thread after reconnection. the client will connect and disconnect several times before stabilizing. I think it weird.

**Comment by adgiczone** [comment]
Hello, I change all my client to MQTT_Async*, and there has another question. I receive segment fault in SSL_Shutdown when I reconnected in other threads.
The pseudocode  code is:
``` c
static void* reconnect(void *args) {
       MQTTAsync handle = (MQTTAsync )args;
        g_conn_opts.passward = new_passward;
        int ret = MQTTAsync_connect(handle, &conn_opts);
        if (ret) {
                return;
        }
        MQTTAsync_subscribe(........);
}

static void on_connection_lost(void *context, char *cause)
{
        MQTTAsync handle = (MQTTAsync )context;
        pthread_t thread;
        pthread_create(&thread, NULL, reconnect, handle);
}
``` 
This is the log [log.log](https://github.com/eclipse/paho.mqtt.c/files/7889034/symphony_log.log)
The gdb message is [gdb_error.log](https://github.com/eclipse/paho.mqtt.c/files/7888985/gdb_error.log)

Is this error caused by my usage?  I'll looking forward to your reply.

**Comment by icraggs** [comment]
You don't want to use automatic reconnect?

You don't need to start another thread to reconnect anyway, if you call MQTTAsync_connect the connect processing will happen in a background thread.  And you will have to wait before calling MQTTAsync_subscribe, as the MQTTAsync_connect won't have completed (your code won't work).

All the MQTTAsync_* calls are only complete when the onSuccess callback function is called.  Or to resubscribe on connect, you can put the subscribe call in the onConnected callback, which is called whether the reconnection is automatic or not.

**Comment by icraggs** [comment]
I think this is answered,
