### ISSUE TITLE
Setting maxBufferedMessages to zero always gets a publish error

### ISSUE THREAD

**Issue by fpagliughi** [eclipse/paho.mqtt.c#1193]
If you set the `maxBufferedMessages` parameter of the `MQTTAsync_createOptions` to zero, then when you try to publish, you get a [-12], `MQTTASYNC_MAX_BUFFERED_MESSAGES` error, even if the client is currently connected.

Note that the the `sendWhileDisconnected` option is also set to zero, indicating together that the application does not want to send messages while disconnected.

The behavior is a bit unexpected as the comment for `maxBufferedMessages` states:
```
/** The maximum number of messages allowed to be buffered while not connected. */
```
This would indicate that it should not have an effect while connected. 

But I now notice that the default is for `sendWhileDisconnected = 0` but `maxBufferedMessages = 100`.

- So is this buffer used while connected?
- Is there a minimum value required for a stable client?
- Should the C library take responsibility for ensuring there's at least the minimum required even if the user sets it to zero?

I tested this on Ubuntu 20.04.

**Comment by icraggs** [comment]
Yes, there's no record kept of whether a publish message is buffered while disconnected or connected.  I should improve the documentation.  We could also limit the allowed setting of maxBufferedMessages to >=1, at least.
