### ISSUE TITLE
Trying to get started with MQTT C Client on Raspberry Pi.

### ISSUE THREAD

**Issue by BruceCrowthorne** [eclipse/paho.mqtt.c#1195]
Not a bug, just a request for help

I have been using MQTT on Raspberry Pi using Python, and on Arduino / ESP8266 using C "PubSubClient.h" for ages. But now I am trying to get C going on Raspberry Pis.

I have followed a guide that I found at 
https://bytesofgigabytes.com/raspberrypi/mqtt-c-client-raspberry-pi/

This is very good, but maybe too specific for what I am trying, it has installed many bits of the C library successfully.

I have written a few programmes that I have "limping", but I am trying to make then robust enough to reconnect if a link is lost.  My current attempt runs for a few hours and then loses it's connection and stops. It reports my error messages eg "Now try and re-connect ....Tried to reconnect ....Failed to connect - re-try -, return code -1" I did try and write my own "re-connect" function - but obviously unsuccesfully!

So I have found the references to Automatic Reconnect at https://www.eclipse.org/paho/files/mqttdoc/MQTTAsync/html/auto_reconnect.html
but I am struggling to get this going.

I am trying to compile one of the sample files ...
`pi@206:~/MQTTClients/paho.mqtt.c/src/samples $ sudo cc MQTTAsync_publish.c -o Asynctest.o -lpaho-mqtt3c
/usr/bin/ld: /tmp/cc4R49mc.o: in function `connlost':
MQTTAsync_publish.c:(.text+0x6c): undefined reference to `MQTTAsync_connect'
/usr/bin/ld: /tmp/cc4R49mc.o: in function `onSend':
MQTTAsync_publish.c:(.text+0x180): undefined reference to `MQTTAsync_disconnect'
/usr/bin/ld: /tmp/cc4R49mc.o: in function `onConnect':
MQTTAsync_publish.c:(.text+0x2c8): undefined reference to `MQTTAsync_sendMessage'
/usr/bin/ld: /tmp/cc4R49mc.o: in function `main':
MQTTAsync_publish.c:(.text+0x360): undefined reference to `MQTTAsync_create'
/usr/bin/ld: MQTTAsync_publish.c:(.text+0x37c): undefined reference to `MQTTAsync_setCallbacks'
/usr/bin/ld: MQTTAsync_publish.c:(.text+0x3b8): undefined reference to `MQTTAsync_connect'
/usr/bin/ld: MQTTAsync_publish.c:(.text+0x418): undefined reference to `MQTTAsync_destroy'
collect2: error: ld returned 1 exit status
`

The code is just your file called MQTTAsync_publish.c  with the broker and queue names changed to ones that I own.

My current knowledge of C is poor - I last used it earnest about 30 years ago - so the basics are "kind of there" but I am still struggling.
My current guess is that the library "MQTTAsync.h" isn't being loaded?
Is that covered by the linker instruction to -lpaho-mqtt3c ?

Can you suggest how to get this going and what I can read to learn more about the library, please?

I apologise in advance for such a basic question.
Regards
Bruce

**Comment by icraggs** [comment]
That guide shows essentially what you need to do.  Building the project with "make" will build all the samples, and show the commands you need to build.

Those errors are because you're linking with the paho-mqtt3c library rather than paho-mqtt3a

**Comment by BruceCrowthorne** [comment]
Hi Ian, thank you very much for replying, I REALLY appreciate your help.
I used the "make" to build the environment and I have used one of the samples as the basis for my programme.
I guess I missed the difference between the paho-mqtt3c library and paho-mqtt3a! Oops!
I will recompile it in the next couple of days and hopefully that will fix the issue
Thanks and regards
Bruce

**Comment by icraggs** [comment]
I think this has been answered.
