### ISSUE TITLE
Example paho_c_sub does not work on Linux while paho_c_pub works fine

### ISSUE THREAD

**Issue by KuanL1u** [eclipse/paho.mqtt.c#1197]
**Describe the bug**
The build-in example paho_c_sub does not work on Linux while paho_c_pub works fine. How to fix this? Thanks!

**To Reproduce**
**% ./paho_c_pub -c tcp://broker.hivemq.com -t kuanliu/test -m hello --trace protocol**
Trace : 3, =========================================================
Trace : 3,                    Trace Output
Trace : 3, Product name: Eclipse Paho Asynchronous MQTT C Client Library
Trace : 3, Version: 1.3.5
Trace : 3, Build level: Fri 04 Feb 2022 10:31:04 AM EST
Trace : 3, OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
Trace : 3, OpenSSL flags: compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-8Ocme2/openssl-1.1.1d=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM 
Trace : 3, OpenSSL build timestamp: built on: Mon Apr 20 20:23:01 2020 UTC
Trace : 3, OpenSSL platform: platform: debian-amd64
Trace : 3, OpenSSL directory: OPENSSLDIR: "/usr/lib/ssl"
Trace : 3, /proc/version: Linux version 4.19.0-9-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.118-2 (2020-04-29)

Trace : 3, =========================================================
Trace : 4, 20220204 113216.182 Connecting to serverURI broker.hivemq.com with MQTT version 4
Trace : 4, 20220204 113216.308 3 paho-c-pub -> CONNECT version 4 clean: 1 (0)
Trace : 4, 20220204 113216.402 3 paho-c-pub <- CONNACK rc: 0
Trace : 4, 20220204 113216.402 3 paho-c-pub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(5): hello
Trace : 4, 20220204 113216.483 3 paho-c-pub -> DISCONNECT (0)

**% ./paho_c_sub -c tcp://broker.hivemq.com -t kuanliu/test --trace protocol**                        
Trace : 3, =========================================================
Trace : 3,                    Trace Output
Trace : 3, Product name: Eclipse Paho Asynchronous MQTT C Client Library
Trace : 3, Version: 1.3.5
Trace : 3, Build level: Fri 04 Feb 2022 10:31:04 AM EST
Trace : 3, OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
Trace : 3, OpenSSL flags: compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-8Ocme2/openssl-1.1.1d=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM 
Trace : 3, OpenSSL build timestamp: built on: Mon Apr 20 20:23:01 2020 UTC
Trace : 3, OpenSSL platform: platform: debian-amd64
Trace : 3, OpenSSL directory: OPENSSLDIR: "/usr/lib/ssl"
Trace : 3, /proc/version: Linux version 4.19.0-9-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.118-2 (2020-04-29)

Trace : 3, =========================================================
Trace : 4, 20220204 113800.687 Connecting to serverURI broker.hivemq.com with MQTT version 4
Trace : 4, 20220204 113800.909 3 paho-c-sub -> CONNECT version 4 clean: 1 (0)
Trace : 4, 20220204 113801.002 3 paho-c-sub <- CONNACK rc: 0
Trace : 4, 20220204 113801.003 3 paho-c-sub -> SUBSCRIBE msgid: 1 (0)
Trace : 4, 20220204 113801.092 3 paho-c-sub <- SUBACK msgid: 1
Trace : 4, 20220204 113803.428 3 paho-c-sub -> DISCONNECT (0)
Trace : 4, 20220204 113803.428 Connecting to serverURI broker.hivemq.com with MQTT version 3
Trace : 4, 20220204 113803.528 3 paho-c-sub -> CONNECT version 3 clean: 1 (0)
Trace : 4, 20220204 113803.618 3 paho-c-sub <- CONNACK rc: 0
Trace : 4, 20220204 113804.019 3 paho-c-sub -> DISCONNECT (0)
Connect failed, rc Failure
Failed to start disconnect, return code: Disconnected

**Comment by icraggs** [comment]
Because someone else is subscribed with the same utility using the same client id.  If you change client id to something unique, it works.

**Comment by KuanL1u** [comment]
Thanks! Using a unique ID can resolve this issue.
