### ISSUE TITLE
Crash at SSLSocket.c 198 line---FD_SET(newSd, &(mod_s.rset_saved))

### ISSUE THREAD

**Issue by XcafebabeX** [eclipse/paho.mqtt.c#1199]
**Describe the bug**
Crash at SSLSocket.c 198 line---FD_SET(newSd, &(mod_s.rset_saved));

ios15.0 /usr/include/sys/_types/_fd_def.h
int __darwin_check_fd_set_overflow(int, const void *, int) __API_AVAILABLE(macosx(11.0), ios(14.0), tvos(14.0), watchos(7.0));

** Environment (please complete the following information):**
 - OS:  compiled app at ios 15 sdk, xcode 13.1, crashes on ios12

Similar problems：
curl： https://github.com/curl/curl/issues/5210

xamarin：https://github.com/xamarin/xamarin-macios/issues/8325

mono：https://github.com/mono/mono/issues/19393
How to sovle this problem？

**Comment by icraggs** [comment]
More information, as described in the issue template, is needed.  If you take a trace please attach it as a file, rather than pasting the contents.

Those examples you provide all seem to be about linking at build time, not while running, so I'm not sure what relevance they have?

**Comment by XcafebabeX** [comment]
My compile option is wrong, 
xcode->Build Setting ->iOS Deployment Target need set to IOS 10.0 (corresponding version)
