### ISSUE TITLE
Fails to publish with user-defined topic to IoT hub 

### ISSUE THREAD

**Issue by inderveerSinghJ** [eclipse/paho.mqtt.c#1201]
I followed the sample code  and documents to connect to the Azure IoT Hub and I am able to send data from device to cloud. The data is being sent on device/<deviceID>/messages/events topic(telemetry message) topic. From same application, I am not able to publish the message on custom topic(user-defined). Can someone help if I am missing any configurations that I should have done?

**Comment by fpagliughi** [comment]
Does Azure let you send user-defined topics?

I don't use it myself, but the last time I tested it, if I recall, it was very specific about the topics it let you send.

**Comment by icraggs** [comment]
From the Azure IoT Hub docs (https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messaging):

_Since IoT Hub is not a general-purpose pub-sub messaging broker, it only supports the documented topic names and topic filters._

**Comment by icraggs** [comment]
I'll take it that this has been answered.
