### ISSUE TITLE
SSL_read error causes Paho MQTT client to disconnect and reconnect

### ISSUE THREAD

**Issue by nirmitdesai** [eclipse/paho.mqtt.c#1204]
**Describe the bug**

When we have 40 or so clients connecting to MQTT broker, occasionally, we will see that MQTT client disconnects and then reconnects in ~4 seconds. The disconnect is preceded by SSL error

**To Reproduce**

It's difficult to reproduce this at smaller scale. In my test setup, it's easy to reproduce where we launch 40 clients and have multiple messages sent back and forth.

**Expected behavior**
No disconnection should happen and client should remain connected

**Log files**
[error_log.txt](https://github.com/eclipse/paho.mqtt.c/files/8145251/error_log.txt)
```
20220225 054007.012 SSLSocket error (5) in SSL_read - getch for socket 6284 rc -1 errno 2 No such file or directory
```
is where things go wrong.

I've  just added relevant snippets from original log file. If you need more data, please let me know.

** Environment (please complete the following information):**
 - OS: Windows
 - Version : Using paho 1.3.9 alongwith commit from https://github.com/eclipse/paho.mqtt.c/pull/1131 . However, from the log file, MQTTProtocol_queueAck is never invoked.

**Comment by icraggs** [comment]
Are there any error messages on the broker?  The trace is not long enough to get any idea of what is happening - needs more precursor info.  And at the minimum level, doesn't need maximum, that just clutters things up with memory allocation info.

If you're trying that commit, why not just try the whole develop branch? I think there are some other fixes that could be relevant.

**Comment by nirmitdesai** [comment]
Hi @icraggs , unfortunately, I don't have broker logs available. I'll do another run with logs at minimum level.

We had tested 1.3.9 + the commit in issue 1131 internally, so that's the version we used for our internal testing. It's just that this SSL_Read error occasionally pops up when we've multiple clients subscribing and publishing messages to broker.

**Comment by icraggs** [comment]
The broker logs are probably not as important as some lead up trace. The SSL_read error isn't a problem in itself - it happens all the time. If it's a problem, it's the particular circumstances under which it occurs. If the broker decided to throw the MQTT client off for whatever reason, then it could show up like this. I'm not saying that's definitely the reason, but it's one possibility.

**Comment by nirmitdesai** [comment]
Thanks for your insights Ian. I think it's difficult to get broker logs in our existing setup. I've attached entire trace from start till the time we see SSL_read error followed by disconnect on client side.
 
[sanitized_log.txt](https://github.com/eclipse/paho.mqtt.c/files/8165472/sanitized_log.txt)

Let me know if that helps. It's easy for us to reproduce this scenario so if you need any changes on client side, feel free to suggest.
Also, from the logs, I can see SSL_read error occuring only once, which is followed by disconnection of MQTT client.

From the log, SSL_Read that's invoked from SSLSocket_getch method always returns 1, as the next method in log is SocketBuffer_queueChar. However, only in one instance, I see SSL_Read returning -1. This is percolated all the way up the chain and that causes MQTT connection to be disconnected.

Edited to add more analysis of SSL_Read

**Comment by icraggs** [comment]
Well the easiest two things are as I suggested 1) try the complete develop branch as it is, as it has some other fixes too 2) see if there are any messages on the broker side when this happens.  

I would only expect the queueAck function to be called if there was such a high throughput as to block the socket when an ack was needed.  Your trace doesn't look to have that high a throughput.

Also - what broker are you using?

**Comment by nirmitdesai** [comment]
Sure @icraggs , I'll try what you suggested and update you.

I am using VerneMQ broker.

**Comment by nirmitdesai** [comment]
Even with develop branch, I was able to reproduce the issue. Haven't gotten a chance to look at broker logs yet so will update this issue once I find something concrete.

**Comment by icraggs** [comment]
I would also try with a later version of OpenSSL just to see if it makes any difference and to rule it out.

**Comment by icraggs** [comment]
Closing pending more information from the broker.
