### ISSUE TITLE
linux cmake no static targets generated

### ISSUE THREAD

**Issue by nandlab** [eclipse/paho.mqtt.c#1207]
Are static builds supported on Linux?

Although I can build with `cmake -DPAHO_BUILD_STATIC=ON` and get the archives `libpaho-mqtt3*.a`, I do not see any static targets in the generated cmake config files, which are:
- eclipse-paho-mqtt-cConfig.cmake
- eclipse-paho-mqtt-cConfig-none.cmake
- eclipse-paho-mqtt-cConfigVersion.cmake

I only see targets like `eclipse-paho-mqtt-c::paho-mqtt3c`, which include the shared libraries.

Do I miss something out?

**Comment by icraggs** [comment]
I'm no CMake expert - the doc says that add_library should create a target.  And there is an add_library for paho-mqtt3cs-static and paho-mqtt3as-static.

**Comment by icraggs** [comment]
No further information forthcoming.
