### ISSUE TITLE
During auto reconnect, some published messages get lost.

### ISSUE THREAD

**Issue by deblauwetom** [eclipse/paho.mqtt.c#1210]
**Describe the bug**
When an automatic reconnect happens, published messages are lost during that reconnect.

**To Reproduce**
Take a library trace as outlined in the README, and/or have a program or describe the steps to reproduce the behavior:
1. I use the async client(with the cpp frontend), created with a persistance directory given, and these options:
`  auto maxBufferedMessages = 1000;  
    auto createOpts = mqtt::create_options(MQTTVERSION_5, maxBufferedMessages);
    createOpts.set_delete_oldest_messages(true);
    createOpts.set_restore_messages(true);
    createOpts.set_send_while_disconnected(true, true);`

2. These are the connect options:
`    auto connOpts = mqtt::connect_options_builder()
                        .keep_alive_interval(20s)
                        .user_name(clientUuid)
                        .password(clientPassword)
                        .ssl(std::move(sslopts))
                        .clean_session(false)
                        .automatic_reconnect(2s, 15s)
                        .mqtt_version(MQTTVERSION_5)
                        .will(willOpts)
                        .finalize();
    connOpts.set_clean_start(false);`
3. The broker is mqtt version 5. I publish a message with qos 1 every second to that broker, each with an incremental number.
4. While this happens, I disconnect my network interface for a while, and then I enable it again.
5. During that downtime, an automatic reconnect happens ok, but the first messages during that downtime seem to be gone and don't get sent after the connection is up again. So I get for example 1,2,3,4,5,....reconnecting.......succeeded...10,11,12. And the packets are not there.

From the logs, it's obvious what I don't want to happen:
`20220324 164608.937 Cleaning session state on connect because sessionPresent is 0`
which is printed at reconnect time looks not what I want. however, I don't seem to find what I can do about it. Any help greatly appreciated!

**Expected behavior**
I expect all messages to be sent because qos 1 and I have persistent storage and surely have not buffered 1000 messages, so I don't want to lose any published messages.

**Log files**
[reconnect_log.txt](https://github.com/eclipse/paho.mqtt.c/files/8343290/reconnect_log.txt)

** Environment (please complete the following information):**
 - OS: Linux, arm64

 - Version: develop branch: 29ed338abc523c0b915ab6dacd564f627ac48c69

**Additional context**
I can always reproduce it.

**Comment by icraggs** [comment]
In MQTT version 5, the clean session flag becomes the clean start flag and cleans up only on the start of the connection.  To control clean up at the end, you need to set the session expiry property.  

This https://www.hivemq.com/blog/mqtt5-essentials-part4-session-and-message-expiry/ might explain a bit more.

**Comment by deblauwetom** [comment]
Yes! I just was reading the code and figured it out 3h ago and was just about to close this issue :) 
Good to know that it's the same solution as you propose, thanks for the answer! It works perfectly now.
