### ISSUE TITLE
Multiple subs in one process

### ISSUE THREAD

**Issue by ypearson** [eclipse/paho.mqtt.c#1211]
I would like to have a separate thread for N subscribers to a N topics. Right now it seems the callbacks are not thread safe (global variables)

Re-org of code to allow N threads to run and N subscribers in a single process.

I'm trying to re-write some of the code to allow this, but I'm probably not doing to do it the correct way. I'm not too familiar with the internals of  MQTT. I will try none the less.

**Comment by icraggs** [comment]
I think you can do what you want already.  Do you want multiple MQTT connections each subscribing to a topic, or one MQTT connection subscribing to multiple topics? 

What global variables are you referring to?

**Comment by ypearson** [comment]
I'm looking at paho_c_sub.com, I'm renamed the `main` to `main_function` and I'm running multiple threads of `main_function` whilst passing in the correct `args`
I put the following variables in a context variable, eliminating the need for globals, along with the `opts` global variable:
`volatile int finished = 0;`
`int subscribed = 0;`
`int disconnected = 0;`

Any advice?

**Comment by icraggs** [comment]
If you want to subscribe to multiple topics, you don't need multiple threads.  Just subscribe to all the topics you want, and then when a message arrives on any of them, the message arrived callback will be invoked.

Do you need multiple threads for some other reason?

**Comment by ypearson** [comment]
I'm using MQTT to simulate multiple hardware/sensors. Each sensor thread needs to do something if topic data comes in. 
If I can have a single sub for multiple topics then I can use a `queue` to channel the topics data to the correct recipient for the topic data. Which means I don't have to mess with `paho_c_sub.c` =)

**Comment by ypearson** [comment]
`./paho_c_sub -t testtopic1 -t testtopic2`
This doesn't seem to work maybe because of this:
`rc = MQTTAsync_subscribeMany(handle, 1, (char * const *)(&topic), &qos, response);`

**Comment by icraggs** [comment]
No, that wouldn't.  The command line example doesn't handle multiple subscriptions as it stands, except for wildcards (+ or #).  It would need to be changed to use MQTTAsync_subscribeMany or multiple calls to MQTTAsync_subscribe.

Several tests show the use of subscribeMany: test9.c, test95.c, test11.c

**Comment by ypearson** [comment]
I appreciate that info! I'll look into this, thank you
