### ISSUE TITLE
libpaho-mqtt3cs.so.1.0 not found

### ISSUE THREAD

**Issue by vishalgupta2406** [eclipse/paho.mqtt.c#1213]
Hello,

Currently we are using eclipse paho version 1.3.0 and trying to upgrade to 1.3.9. I have downloaded the latest code from master for 1.3.9 and after make command I dont see library "libpaho-mqtt3cs.so.1.0" generated in build folder which is what our current framework is referring to.

Can you please help and suggest what we should be using instead of libpaho-mqtt3cs.so.1.0 as it is not longer generated in build folder.?

 lib:
    {
        libpaho-mqtt3cs.so
        libpaho-mqtt3cs.so.1
        libpaho-mqtt3cs.so.1.0
    }

**Comment by icraggs** [comment]
I think your framework should either be referring one of the symlinks libpaho-mqtt3cs.so or libpaho-mqtt3cs.so,1 not the library itself, which could change with every release (and in the CMake builds, does). The purpose of the symlinks is to avoid having to change library references every time a new version is installed.

**Comment by vishalgupta2406** [comment]
I have changed it to use libpaho-mqtt3cs.so.1.3 which fixes the issue, do you think I should just use libpaho-mqtt3cs.so.1
 or libpaho-mqtt3cs.so ?

**Comment by icraggs** [comment]
Yes, use one of the symlinks - they won't change so frequently, if ever.

**Comment by icraggs** [comment]
I think this is answered.
