### ISSUE TITLE
possible race condition betwee MQTTClient_waitfor and MQTTClient_run

### ISSUE THREAD

**Issue by nhorman** [eclipse/paho.mqtt.c#1214]
**Describe the bug**
Was running helgrind on an application I'm building, and observed a possible raw error during testing (see attachment):
[helgrind.log](https://github.com/eclipse/paho.mqtt.c/files/8405081/helgrind.log)

I've not tracked it down yet, but I _think_ the problem is in MQTT_client_cycle, which, when called from MQTTClient_run drops the mqtt_clientlock (so that MQTTClient_cycle can re-acquire it).  Before doing the re-acquisition, MQTTClient_cycle reads the *sock pointer, which MQTTClient_waitfor also writes to, leading to the race detection

**To Reproduce**
Take a library trace as outlined in the README, and/or have a program or describe the steps to reproduce the behavior:
1. write a simple program that creates an MQTT client and calls MQTT_connect5 on said client
2. Run the program under helgrind (valgrind --tool=helgrind --log-file=./helgrind.log <a.out>

**Expected behavior**
No races detected

**Screenshots**
see attachment

**Log files**

** Environment (please complete the following information):**
 - OS: Fedora 35 (5.16.12-200.fc35.x86_64 #1 SMP PREEMPT Wed Mar 2 19:06:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux)

**Additional context**
None

**Comment by icraggs** [comment]
I've put a fix into the develop branch.

**Comment by nhorman** [comment]
Thanks!  I'll give it a try in just a bit

**Comment by nhorman** [comment]
confirmed, helgrind is silent now, thank you!
