### ISSUE TITLE
Paho C client not able to connect with "CA Signed Server certificate"

### ISSUE THREAD

**Issue by satyamtpatel** [eclipse/paho.mqtt.c#1216]
**Describe the bug**
We are trying to connect to mqtt server using paho c client but it is failing. But we do with MQTT.fx or other mqtt client then it is working fine.

**To Reproduce**
Take a library trace as outlined in the README, and/or have a program or describe the steps to reproduce the behavior:
1. **We have setup below parameters in our code:**
// Setting Options for MQTT Connection
  conn_opts.keepAliveInterval = uiKeepAliveInterval;
  conn_opts.cleansession = bCleanSession;
  conn_opts.context=client;
  conn_opts.automaticReconnect=1;
  conn_opts.username = strMQTTUsername.c_str();
  conn_opts.password = strMQTTPassword.c_str();
  conn_opts.serverURIcount=0;
  conn_opts.serverURIs = NULL;

  // conn_opts.struct_version = 4;
  ssl_opts.enableServerCertAuth = 0;
  ssl_opts.verify=0;
  // ssl_opts.enableServerCertAuth = false;
  // ssl_opts.verify = true;
   ssl_opts.sslVersion = MQTT_SSL_VERSION_TLS_1_2;
  //ssl_opts.sslVersion = 3;
 

  conn_opts.ssl = &ssl_opts;
  
  //conn_opts.ssl->enabledCipherSuites = "aNULL";
	

  // Connect to MQTTClient
  if ((uiConnectSts = MQTTAsync_connect(client, &conn_opts)) != MQTTASYNC_SUCCESS) {
      std::cout << "uiConnectToBroker : Failed to connect to MQTT Broker, return code : " << (int)uiConnectSts << std::endl;
      clMQTTLoggerObj.bInsertCriticalLog("uiConnectToBroker : Failed to connect to MQTT Broker, return code %d\n", uiConnectSts);
      MQTTAsync_destroy(&client);
      return IC_FAIL;
  }

2. **We did compile our code using paho-mqtt3as. When we are executing our program it is not connecting to mqtt server"
**3. Below is trace from the client**

=========================================================
                   Trace Output
Product name: Eclipse Paho Asynchronous MQTT C Client Library
Version: 1.3.6
Build level: 2022-04-08T18:53:23Z
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
OpenSSL flags: compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-vxXVMf/openssl-1.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX2
OpenSSL build timestamp: built on: Wed Mar  9 12:13:40 2022 UTC
OpenSSL platform: platform: debian-amd64
OpenSSL directory: OPENSSLDIR: "/usr/lib/ssl"
/proc/version: Linux version 4.15.0-175-generic (buildd@lcy02-amd64-034) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #184-Ubuntu SMP Thu Mar 24 17:48:36 UTC 2022

=========================================================
19691231 190000.000 (2018838400)  (1)> Socket_outInitialize:131
19691231 190000.000 (2018838400)   (2)> SocketBuffer_initialize:106
19691231 190000.000 (2018838400)   (2)< SocketBuffer_initialize:114 (0)
19691231 190000.000 (2018838400)  (1)< Socket_outInitialize:144
19691231 190000.000 (2018838400)  (1)> SSLSocket_initialize:447
19691231 190000.000 (2018838400)   (2)> SSL_create_mutex:346
19691231 190000.000 (2018838400)   (2)< SSL_create_mutex:352 (0)
19691231 190000.000 (2018838400)   (2)> SSL_create_mutex:346
19691231 190000.000 (2018838400)   (2)< SSL_create_mutex:352 (0)
19691231 190000.000 (2018838400)  (1)< SSLSocket_initialize:493 (1)
19691231 190000.000 (2018838400)  (1)> MQTTStrncpy:905
19691231 190000.000 (2018838400)  (1)< MQTTStrncpy:915
19691231 190000.000 (2018838400)  (1)> MQTTStrncpy:905
19691231 190000.000 (2018838400)  (1)< MQTTStrncpy:915
19691231 190000.000 (2018838400)  (1)> MQTTPersistence_create:52
19691231 190000.000 (2018838400)  (1)< MQTTPersistence_create:100 (0)
19691231 190000.000 (2018838400)  (1)> MQTTPersistence_initialize:115
19691231 190000.000 (2018838400)  (1)< MQTTPersistence_initialize:123 (0)
19691231 190000.000 (2018838400)  (1)> MQTTAsync_restoreCommands:1238
20220408 150305.875 0 commands restored for client Broadcaster_Agent_190305
20220408 150305.875 (2018838400)  (1)< MQTTAsync_restoreCommands:1318 (0)
20220408 150305.875 (2018838400)  (1)> MQTTPersistence_restoreMessageQueue:796
20220408 150305.875 0 queued messages restored for client Broadcaster_Agent_190305
20220408 150305.875 (2018838400)  (1)< MQTTPersistence_restoreMessageQueue:836 (0)
20220408 150305.875 (2018838400) (0)< MQTTAsync_createWithOptions:732 (0)
20220408 150305.875 (2018838400) (0)> MQTTAsync_setCallbacks:3070
20220408 150305.875 (2018838400) (0)< MQTTAsync_setCallbacks:3084 (0)
20220408 150305.875 (2018838400) (0)> MQTTAsync_setConnected:3183
20220408 150305.875 (2018838400) (0)< MQTTAsync_setConnected:3195 (0)
20220408 150305.875 (2018838400) (0)> MQTTAsync_connect:3488
20220408 150305.875 (2018838400)  (1)> UTF8_validateString:160
20220408 150305.875 (2018838400)   (2)> UTF8_validate:134
20220408 150305.875 (2018838400)   (2)< UTF8_validate:146 (1)
20220408 150305.875 (2018838400)  (1)< UTF8_validateString:165 (1)
20220408 150305.875 (2018838400)  (1)> UTF8_validateString:160
20220408 150305.875 (2018838400)   (2)> UTF8_validate:134
20220408 150305.875 (2018838400)   (2)< UTF8_validate:146 (1)
20220408 150305.875 (2018838400)  (1)< UTF8_validateString:165 (1)
20220408 150305.875 (2018838400)  (1)> Thread_start:69
20220408 150305.875 (2018838400)  (1)< Thread_start:79
20220408 150305.875 (2018838400)  (1)> Thread_start:69
20220408 150305.875 (2018838400)  (1)< Thread_start:79
20220408 150305.875 (2018838400)  (1)> MQTTStrncpy:905
20220408 150305.875 (2018838400)  (1)< MQTTStrncpy:915
20220408 150305.875 (2018838400)  (1)> MQTTStrncpy:905
20220408 150305.875 (2018838400)  (1)< MQTTStrncpy:915
20220408 150305.875 (1893361408) (0)> MQTTAsync_receiveThread:2700
20220408 150305.875 (1893361408)  (1)> MQTTAsync_cycle:4574
20220408 150305.875 (1893361408)   (2)> Socket_getReadySocket:249
20220408 150305.875 (1893361408)   (2)< Socket_getReadySocket:321 (0)
20220408 150305.875 (1893361408)   (2)> MQTTAsync_sleep:482
20220408 150305.875 (1901754112) (0)> MQTTAsync_sendThread:2395
20220408 150305.875 (1901754112)  (1)> Thread_wait_cond:421
20220408 150305.875 (2018838400)  (1)> MQTTAsync_addCommand:1424
20220408 150305.875 (2018838400)   (2)> Thread_signal_cond:403
20220408 150305.875 (2018838400)   (2)< Thread_signal_cond:408 (0)
20220408 150305.875 (2018838400)  (1)< MQTTAsync_addCommand:1521 (0)
20220408 150305.875 (2018838400) (0)< MQTTAsync_connect:3851 (0)
20220408 150305.875 (2018838400) (0)> MQTTAsync_sendMessage:4334
20220408 150305.876 (2018838400)  (1)> MQTTAsync_send:4238
20220408 150305.876 (2018838400)  (1)< MQTTAsync_send:4322 (-3)
20220408 150305.876 (2018838400) (0)< MQTTAsync_sendMessage:4353 (-3)
20220408 150305.876 (1901754112)  (1)< Thread_wait_cond:436 (0)
20220408 150305.876 (1901754112)  (1)> MQTTAsync_checkTimeouts:2300
20220408 150305.876 (1901754112)  (1)< MQTTAsync_checkTimeouts:2389
20220408 150305.876 (1901754112)  (1)> MQTTAsync_processCommand:1848
20220408 150305.876 Connecting to serverURI mqtt.atma-platform.info:555 with MQTT version 4
20220408 150305.876 (1901754112)   (2)> MQTTProtocol_connect:161
20220408 150305.876 (1901754112)    (3)> MQTTProtocol_addressPort:60
20220408 150305.876 (1901754112)    (3)< MQTTProtocol_addressPort:92
20220408 150305.876 (1901754112)    (3)> Socket_new:689
20220408 150305.876 (2018838400) (0)> MQTTAsync_destroy:2558
20220408 150305.876 New socket 6 for mqtt.atma-platform.info:555, port 555
20220408 150305.876 (1901754112)     (4)> Socket_addSocket:173
20220408 150305.876 (1901754112)      (5)> Socket_setnonblocking:85
20220408 150305.876 (1901754112)      (5)< Socket_setnonblocking:90 (0)
20220408 150305.876 (1901754112)     (4)< Socket_addSocket:208 (0)
20220408 150305.876 Connect pending
20220408 150305.876 (1901754112)    (3)< Socket_new:845 (115)
20220408 150305.914 (1901754112)   (2)< MQTTProtocol_connect:324 (115)
20220408 150305.914 (1901754112)   (2)> MQTTProperties_free:382
20220408 150305.914 (1901754112)   (2)< MQTTProperties_free:405
20220408 150305.914 (1901754112)  (1)< MQTTAsync_processCommand:2230 (1)
20220408 150305.914 (1901754112)  (1)> Thread_wait_cond:421
20220408 150305.914 (2018838400)  (1)> MQTTAsync_closeSession:3298
20220408 150305.914 (2018838400)   (2)> MQTTAsync_closeOnly:3268
20220408 150305.914 (2018838400)    (3)> MQTTProtocol_checkPendingWrites:1650
20220408 150305.914 (2018838400)    (3)< MQTTProtocol_checkPendingWrites:1667
20220408 150305.914 (2018838400)    (3)> WebSocket_close:526
20220408 150305.914 (2018838400)    (3)< WebSocket_close:574
20220408 150305.914 (2018838400)    (3)> SSLSocket_close:933
20220408 150305.914 (2018838400)     (4)> SSLSocket_destroyContext:920
20220408 150305.914 (2018838400)     (4)< SSLSocket_destroyContext:924
20220408 150305.914 (2018838400)    (3)< SSLSocket_close:946 (1)
20220408 150305.914 (2018838400)    (3)> Socket_close:629
20220408 150305.914 (2018838400)     (4)> Socket_close_only:603
20220408 150305.914 (2018838400)     (4)< Socket_close_only:617 (0)
20220408 150305.914 (2018838400)     (4)> Socket_abortWrite:955
20220408 150305.914 (2018838400)     (4)< Socket_abortWrite:973 (0)
20220408 150305.914 (2018838400)     (4)> SocketBuffer_cleanup:153
20220408 150305.914 (2018838400)     (4)< SocketBuffer_cleanup:165
20220408 150305.914 Removed socket 6
20220408 150305.914 (2018838400)    (3)< Socket_close:656
20220408 150305.914 (2018838400)   (2)< MQTTAsync_closeOnly:3292
20220408 150305.914 (2018838400)   (2)> MQTTAsync_cleanSession:3333
20220408 150305.914 (2018838400)    (3)> MQTTAsync_unpersistInflightMessages:1367
20220408 150305.914 0 inflight messages deleted for client Broadcaster_Agent_190305
20220408 150305.914 (2018838400)    (3)< MQTTAsync_unpersistInflightMessages:1392 (0)
20220408 150305.914 (2018838400)    (3)> MQTTProtocol_emptyMessageList:866
20220408 150305.914 (2018838400)    (3)< MQTTProtocol_emptyMessageList:875
20220408 150305.914 (2018838400)    (3)> MQTTProtocol_emptyMessageList:866
20220408 150305.914 (2018838400)    (3)< MQTTProtocol_emptyMessageList:875
20220408 150305.914 (2018838400)    (3)> MQTTAsync_freeResponses:2456
20220408 150305.914 0 responses removed for client Broadcaster_Agent_190305
20220408 150305.914 (2018838400)    (3)< MQTTAsync_freeResponses:2496
20220408 150305.914 (2018838400)   (2)< MQTTAsync_cleanSession:3347 (0)
20220408 150305.914 (2018838400)  (1)< MQTTAsync_closeSession:3305
20220408 150305.914 (2018838400)  (1)> MQTTAsync_freeResponses:2456
20220408 150305.914 0 responses removed for client Broadcaster_Agent_190305
20220408 150305.914 (2018838400)  (1)< MQTTAsync_freeResponses:2496
20220408 150305.914 (2018838400)  (1)> MQTTAsync_freeCommands:2506
20220408 150305.914 0 commands removed for client Broadcaster_Agent_190305
20220408 150305.914 (2018838400)  (1)< MQTTAsync_freeCommands:2550
20220408 150305.914 (2018838400)  (1)> MQTTStrncpy:905
20220408 150305.914 (2018838400)  (1)< MQTTStrncpy:915
20220408 150305.914 (2018838400)  (1)> MQTTPersistence_close:137
20220408 150305.914 (2018838400)  (1)< MQTTPersistence_close:152 (0)
20220408 150305.914 (2018838400)  (1)> MQTTAsync_emptyMessageQueue:2434
20220408 150305.914 (2018838400)  (1)< MQTTAsync_emptyMessageQueue:2448
20220408 150305.914 (2018838400)  (1)> MQTTProtocol_freeClient:813
20220408 150305.914 (2018838400)   (2)> MQTTProtocol_freeMessageList:885
20220408 150305.914 (2018838400)    (3)> MQTTProtocol_emptyMessageList:866
20220408 150305.914 (2018838400)    (3)< MQTTProtocol_emptyMessageList:875
20220408 150305.914 (2018838400)   (2)< MQTTProtocol_freeMessageList:888
20220408 150305.914 (2018838400)   (2)> MQTTProtocol_freeMessageList:885
20220408 150305.914 (2018838400)    (3)> MQTTProtocol_emptyMessageList:866
20220408 150305.914 (2018838400)    (3)< MQTTProtocol_emptyMessageList:875
20220408 150305.914 (2018838400)   (2)< MQTTProtocol_freeMessageList:888
20220408 150305.914 (2018838400)  (1)< MQTTProtocol_freeClient:854
20220408 150305.915 Removed client Broadcaster_Agent_190305 from bstate->clients, socket 0
20220408 150305.915 (2018838400)  (1)> MQTTAsync_terminate:749
20220408 150305.915 (2018838400)   (2)> MQTTAsync_stop:3023
20220408 150305.915 Conn_count is 0
20220408 150305.915 sleeping
20220408 150305.915 (2018838400)    (3)> MQTTAsync_sleep:482
20220408 150305.915 (1893361408)   (2)< MQTTAsync_sleep:488
20220408 150305.915 (1893361408)   (2)> MQTTAsync_retry:4363
20220408 150305.915 (1893361408)    (3)> MQTTProtocol_keepalive:660
20220408 150305.915 (1893361408)    (3)< MQTTProtocol_keepalive:696
20220408 150305.915 (1893361408)    (3)> MQTTProtocol_retry:784
20220408 150305.915 (1893361408)    (3)< MQTTProtocol_retry:803
20220408 150305.915 (1893361408)   (2)< MQTTAsync_retry:4373
20220408 150305.915 (1893361408)  (1)< MQTTAsync_cycle:4725 (-1)
20220408 150305.915 (1893361408)  (1)> Thread_signal_cond:403
20220408 150305.915 (1893361408)  (1)< Thread_signal_cond:408 (0)
20220408 150305.915 (1893361408) (0)< MQTTAsync_receiveThread:3009
20220408 150305.915 (1901754112)  (1)< Thread_wait_cond:436 (0)
20220408 150305.915 (1901754112)  (1)> MQTTAsync_checkTimeouts:2300
20220408 150305.915 (1901754112)  (1)< MQTTAsync_checkTimeouts:2389
20220408 150305.976 (1901754112) (0)< MQTTAsync_sendThread:2424
20220408 150305.976 (2018838400)    (3)< MQTTAsync_sleep:488
20220408 150305.976 (2018838400)   (2)< MQTTAsync_stop:3058 (1)
20220408 150305.976 (2018838400)   (2)> WebSocket_terminate:1259
20220408 150305.976 (2018838400)    (3)> Socket_outTerminate:153
20220408 150305.976 (2018838400)     (4)> SocketBuffer_terminate:138
20220408 150305.976 (2018838400)     (4)< SocketBuffer_terminate:143
20220408 150305.976 (2018838400)    (3)< Socket_outTerminate:161
20220408 150305.976 (2018838400)    (3)> SSLSocket_terminate:499
20220408 150305.976 (2018838400)     (4)> SSL_destroy_mutex:390
20220408 150305.976 (2018838400)     (4)< SSL_destroy_mutex:396 (0)
20220408 150305.976 (2018838400)     (4)> SSL_destroy_mutex:390
20220408 150305.976 (2018838400)     (4)< SSL_destroy_mutex:396 (0)
20220408 150305.976 (2018838400)    (3)< SSLSocket_terminate:520
20220408 150305.976 (2018838400)   (2)< WebSocket_terminate:1292
20220408 150305.976 Maximum heap use was 3072 bytes

**Expected behavior**

**Screenshots**

**Log files**
Please try to attach log files rather than pasting the log contents. It makes the issues easier to read.

** Environment (please complete the following information):**
 - OS: [e.g. Linux] Ubuntu
 - Version [e.g. 22] 18.04

**Additional context**

**Comment by icraggs** [comment]
The trace looks strange. It looks like you're trying to send a message before waiting for the connect to complete, and then calling destroy too. To wait for the connect to complete you must wait for the onSuccess callback. See the paho_c_pub.c and paho_c_sub.c command line programs for how.

**Comment by icraggs** [comment]
Closing as no more info.
