### ISSUE TITLE
dll binary files in archive eclipse-paho-mqtt-c-win32-1.3.10.zip are 64bits (not 32bits)

### ISSUE THREAD

**Issue by francescofoti** [eclipse/paho.mqtt.c#1220]
The compiled dlls in the \bin directory in the x86 archive are actually the x64 dlls (Windows).

Techniques to verify the the bitness of the dll are many. One possibility is to rename the dll to .exe, show the file properties in explorer, go to the "Compatibility" tab and look at the list of proposed Windows versions. If 32bits platforms (like Windows XP) do not show, then it's a 64 executable or library (https://www.winhelponline.com/blog/find-out-if-a-program-exe-file-is-32-bit-or-64-bit).

**Expected behavior**
32bits binaries are expected in the x86 archive.

**Screenshots**
![image](https://user-images.githubusercontent.com/6288870/164571198-8069fa46-9786-477c-bcdd-021380c05fee.png)

** Environment (please complete the following information):**
 - OS: Windows 10
 - Version : any

**Comment by francescofoti** [comment]
Anyway, I managed to compile one of the dlls (paho-mqtt3c.dll) with Visual Studio 2022:
- Make sure you have installed the necessary Visual Studio components (at least CMake build tools, MSBuild maybe also)
- Download the source archive of the paho-mqtt client libraries (or clone the project)
- Open Visual Studio without any project
- Open the source folder from Visual Studio (the root folder containing CMakeLists.txt, File > Open > Folder)
- The rest is quite nicely handled by Visual Studio, which sort of parses the CMake project I guess, and then you can see all the libraries projects, tests, etc.. in the solution explorer
- You'll have to clone the x64-Debug configuration ("Manage configurations..." in the configuration combo), maybe rename it (Edit JSON, VS will refresh after saving the modified json file) and build the project you need
- Voilà
I was trying to do that with PellesC, to be free from the msvcrt_xxx_ C runtime, but I was loosing myself in the complexity of the process, so I tried Visual Studio which quite simplifies things.
I followed this Microsoft documentation: [CMake projects in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-170)
Cheers.

**Comment by emgre** [comment]
This is a regression, the 1.3.9 release has the expected Windows x86 binaries in the release zip.

FYI, a better way to check this information is to run `dumpbin <whatever.[exe|dll|lib]> /headers`.

cc @EmileGregoire-Eaton

**Comment by icraggs** [comment]
Fixed for 1.3.11
