### ISSUE TITLE
MQTTAsync client - sending a lot of messages causes deadlock

### ISSUE THREAD

**Issue by markus-fischbacher** [eclipse/paho.mqtt.c#1222]
**Describe the bug**
I have a program that is subscribing to a topic. Received messages cause sending data over RS485.
The response of the RS485 is then published to MQTT.

The received MQTT message payload is pushed to a queue of the RS485 worker.
That queue is read from the RS485 worker which is then sending the data over RS485.
The received RS485 response is published to MQTT from that RS485 worker thread.

In my case there are at least two thread involved. The MQTT message received worker and my RS485 worker.
The enqueueing and dequeueing of the elements is synchronised by a std::recursive_mutex.

**To Reproduce**
I tried to create a minimum working example which is showing the error.
Unfortunately I can't reproduce it there.
The problem occurs, when a lot of messages are published to my program causing a lot of RS485 requests and the RS485 responses are causing a lot of message publishes.
If the messages are not published that fast to my program, it's not gonna stuck.

But I've created a MQTT trace.
What I could figure out is, that the lock happens when the mqttasync_mutex is tried to lock.

I'm using the master branch and build the source directly in my project.

**Expected behavior**
Sending and receiving a lot of messages in a short period of time should not block.

**Log files**
Please find the file attached.

**Environment (please complete the following information):**
 - OS: Linux embedded on an i.MX6 ARM CPU
 - Version: 5.4.91-bsp-yocto-i.mx6ul

**Additional context**
If I run my program on Ubuntu or MacOS, the problem does not appear.
It's about the CPU speed I guess. The embedded system is way slower than the notebook

Any help is appreciated.

Kind regards,
Markus
[trace.log](https://github.com/eclipse/paho.mqtt.c/files/8581927/trace.log)

**Comment by markus-fischbacher** [comment]
Just found the cause of my dead lock.
Two threads (MQTTs internal thread and my worker thread) and two different mutex (MQTTs mqttasync_mutex and a mutex of my worker) are the origin.

**Comment by DeserterW** [comment]
> Just found the cause of my dead lock. Two threads (MQTTs internal thread and my worker thread) and two different mutex (MQTTs mqttasync_mutex and a mutex of my worker) are the origin.

Hey there ! I found the same question you have met. But my program can't make two thread contact each other. Is there any solution to solve it ? Appreciate it for your reply.
