### ISSUE TITLE
v1.3.10 client must use "sudo" to connect server, v1.3.9 no problem

### ISSUE THREAD

**Issue by xuxinle** [eclipse/paho.mqtt.c#1223]
When I used  v1.3.10 in WSL Ubuntu and embedded Ubuntu, I must use sudo to execute the client.
If not, MQTTClient_connect return -1.
I tried v.1.3.9,  it did not happened.

    MQTTClient client;
    MQTTClient_connectOptions con_opts = MQTTClient_connectOptions_initializer;
    MQTTClient_message message = MQTTClient_message_initializer;
    MQTTClient_deliveryToken token;
    int rc;
    rc = MQTTClient_create(&client, "ssl://xxx:1883", "paho", MQTTCLIENT_PERSISTENCE_NONE, NULL);
    if (rc) {
        return rc;
    }
    con_opts.keepAliveInterval = 20;
    con_opts.cleansession = 1;
    con_opts.username = "xxx";
    con_opts.password = "xxx";
    MQTTClient_SSLOptions ssl_options = MQTTClient_SSLOptions_initializer;
    ssl_options.enableServerCertAuth = 0;
    rc = MQTTClient_connect(client, &con_opts);
    if (rc) {
        puts("connect failed");
        printf("%d %s", rc, MQTTClient_strerror(rc));
        return rc;
    }

**Comment by icraggs** [comment]
I don't really know what this means. Perhaps if you take a trace as described in the readme, of the failing case, this might help. I've no idea of any changes between versions which could cause this, but as I said I really don't understand what is going on here (why you need to use sudo). My best guess is it's using some resource on the file system which is not accessible by the user.

**Comment by icraggs** [comment]
Closing as no more info provided.
