### ISSUE TITLE
Why Mqtt process comand hang here?

### ISSUE THREAD

**Issue by dionysus1016** [eclipse/paho.mqtt.c#1225]
I have a trace below, at the end of the trace, we can see there are 17 seconds in which MQTT does nothing there,  any idea why this happens?
--------------------------------------------------------------------------------------------------------------
20220509 111446.707 (3556767488)  (1)> MQTTAsync_processCommand:1180
20220509 111446.707 Connecting to serverURI xxx.xxx.com:1883 with MQTT version 4
20220509 111446.707 (3556767488)   (2)> MQTTProtocol_connect:218
20220509 111446.707 (3556767488)    (3)> MQTTProtocol_addressPort:60
20220509 111446.707 (3556767488)    (3)< MQTTProtocol_addressPort:92
20220509 111446.707 (3556767488)    (3)> Socket_new:696
20220509 111447.707 (3548374784)    (3)> Socket_continueWrites:995
20220509 111447.707 (3548374784)    (3)< Socket_continueWrites:1025 (0)
20220509 111447.707 (3548374784)   (2)< Socket_getReadySocket:328 (0)
20220509 111447.707 (3548374784)   (2)> MQTTAsync_sleep:104
20220509 111447.707 (3548374784)   (2)< MQTTAsync_sleep:110
20220509 111447.707 (3867133696) (0)> MQTTAsync_isConnected:1316
20220509 111447.707 getaddrinfo failed for addr xxx.xxx.com with rc -3
20220509 111447.707 xxx.xxx.com is not a valid IP address
20220509 111447.707 (3556767488)    (3)< Socket_new:852 (-3)
20220509 111447.707 (3556767488)   (2)< MQTTProtocol_connect:340 (-3)
20220509 111447.707 (3556767488)   (2)> MQTTAsync_disconnect1:2530
20220509 111447.707 (3556767488)   (2)< MQTTAsync_disconnect1:2571 (-3)
20220509 111447.707 (3556767488)   (2)> MQTTAsync_checkConn:189
20220509 111447.707 (3556767488)   (2)< MQTTAsync_checkConn:192 (1)
20220509 111447.707 Connect failed, more to try
20220509 111447.707 (3556767488)   (2)> MQTTAsync_addCommand:791
20220509 111447.707 (3556767488)    (3)> Thread_signal_cond:396
20220509 111447.707 (3556767488)    (3)< Thread_signal_cond:401 (0)
20220509 111447.707 (3556767488)   (2)< MQTTAsync_addCommand:912 (0)
**20220509 111447.707 (3556767488)  (1)< MQTTAsync_processCommand:1571 (1)
20220509 111514.737 (3556767488)  (1)> MQTTAsync_processCommand:1180**

**Comment by dionysus1016** [comment]
we use 1.3.9 branch in our test.

**Comment by stuqqq** [comment]
perhaps mqtt connection failure triggerd the reconnect retry interval

**Comment by icraggs** [comment]
1.You have a getaddrinfo failure just before, it could be the DNS lookup failure, which is synchronous. There is an issue for that https://github.com/eclipse/paho.mqtt.c/issues/690.

2. The other possibility I can think of is if you have a callback in which the program is spending a long time, which must be avoided.

Looks like option 1 is the most likely.

**Comment by dionysus1016** [comment]
> 

Thanks for the reply, from the code, I don't see any functions are called there between "
20220509 111447.707 (3556767488) (1)< MQTTAsync_processCommand:1571 (1)" and "20220509 111514.737 (3556767488) (1)> MQTTAsync_processCommand:1180",   even the main loop will call Thread_wait_cond if there are NO pending commands, but from the trace, we don't see "Thread_wait_cond" is called, therefore, there are pending commands in the queue.

**Comment by dionysus1016** [comment]
We are running the MQTT client on the so-called "AGL" Linux which have limited tool installed, and we are trying to make bcc tools works in that system which may help to figure out the off-CPU stack, but from the code, it looks impossible for the thread to wait 17 seconds there.

**Comment by icraggs** [comment]
More trace would be useful.

From that snippet it also looks like you're calling MQTTAsync_isConnected() which doesn't return in that time frame, unless you've omitted it. That could indicate a deadlock somewhere. MQTTAsync_isConnected shouldn't be called in a callback.

**Comment by icraggs** [comment]
Assuming this is answered.
