### ISSUE TITLE
use with openssl3.0.0

### ISSUE THREAD

**Issue by SinberZhang** [eclipse/paho.mqtt.c#1228]
SSL configuration added, but connection failed

           ssl_opts.keyStore = SSL_CLIENT_CRT; 
            ssl_opts.trustStore = SSL_CA_CRT;
            ssl_opts.privateKey = SSL_CLIENT_KEY; 
            ssl_opts.sslVersion = MQTT_SSL_VERSION_DEFAULT;
            ssl_opts.enableServerCertAuth=0;
            conn_opts.ssl = &ssl_opts;

Connect failed, rc:-1 ,msg:TCP/TLS connect failure

The configuration doesn't seem to work。Please help me, thank you！

**Comment by SinberZhang** [comment]
The MQTT tool has been used to test the connectivity of the server. Is there a problem with the configuration of the PAHO MQTT

**Comment by icraggs** [comment]
A trace, at the protocol level, as requested in the issue template, would help.

**Comment by SinberZhang** [comment]
The Wireshark is used to capture packets. The client does not send the "Client Hello" data frame

**Comment by SinberZhang** [comment]
![image](https://user-images.githubusercontent.com/57391996/170445405-b26f3e22-1efb-41af-870e-1b2cb228ab96.png)

**Comment by SinberZhang** [comment]
Normal connection is as follows
![image](https://user-images.githubusercontent.com/57391996/170446013-c4482cb8-ff78-4d01-ae01-9bfd8bad059c.png)

**Comment by SinberZhang** [comment]
![image](https://user-images.githubusercontent.com/57391996/171130185-ee7c639a-6484-4b89-81ce-e5d46810f608.png)
Description: Bad Certificate (42)

**Comment by SinberZhang** [comment]
There are some issues with the configuration of certificates

**Comment by JuergenKosel** [comment]
Hello @SinberZhang ,

I ran into a similar issue: I have rebuild and linked my `paho.mqtt.c` application with openssl-library upgraded from `libssl1.1` to `libssl3`.
But now the connection to the mosquitto broker with a client certificate can not longer be established, if the private-key of the client certificate is not password protected.
In this case the log-output of the mosquitto broker shows this:

```
1701862996: New connection from 10.30.240.14:37512 on port 8884.
1701862996: OpenSSL Error[0]: error:140260E5:SSL routines:ACCEPT_SR_CLNT_HELLO:ssl handshake failure
1701862996: Client <unknown> disconnected: Protocol error.
```

Could it be, that openssl version 3 refuses to use the 1024 bit private key, which was not a problem for the earlier version?

How have you solved your problem? Just recreated new certificates?

/reopen

**Comment by JuergenKosel** [comment]
Maybe my problems are related to this openssl issue:
https://github.com/openssl/openssl/issues/20877
