### ISSUE TITLE
Memory Vulnerabilities in ListFindItem and ListRemoveHead

### ISSUE THREAD

**Issue by pkallimath** [eclipse/paho.mqtt.c#1229]
Description:
We are observing segmentation faults and corefiles are pointing ListFindItem and ListRemoveHead functions.

Program terminated with signal 11, Segmentation fault.
#0  0x00068fb8 in ListFindItem ()
(gdb) bt
#0  0x00068fb8 in ListFindItem ()
#1  0x0005ba20 in MQTTClient_run ()
#2  0xb6bb7eb4 in start_thread () from /lib/arm-linux-gnueabi/libpthread.so.0
#3  0xb6ab3358 in clone () from /lib/arm-linux-gnueabi/libc.so.6

(gdb) bt
#0  0x00068fb8 in ListRemoveHead ()
#1  0x0005ba20 in MQTTClient_run ()
#2  0xb6bb7eb4 in ?? ()
#3  0xb6bb7eb4 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)

**To Reproduce**
Our module runs in a multithreaded environment and the function arguments use global variables. I think that might be reason for the assert.

**Expected behavior**
A NULL check is necessary to avoid de-referencing a NULL pointer. 
<img width="821" alt="image" src="https://user-images.githubusercontent.com/82024734/169496559-24f42283-5139-47e3-b655-ecfa044a0d7d.png">

**Comment by icraggs** [comment]
That's not much information to reproduce. 

Adding NULL checks may well get you further but it's likely that would be masking the real issues rather than fixing them, which is why the checks aren't in there already. Some more detail about your scenario and ideally some trace would help.

**Comment by pkallimath** [comment]
I am not getting full backtrace, it is giving me only thread name. And these functions are called from with the paho library but at multiple instances.

So, if you could add more details on your ask, i.e., what is that you mean by "more details about your scenario and some trace"?

**Comment by icraggs** [comment]
The details requests are outlined in the issue template.

The backtrace only shows the MQTTClient_run thread but that doesn't say anything about the activity on the other application threads.

Basically more about your scenario. If it's a fairly complicated one, in a multithreaded environment, then the MQTTAsync API might be more suited.

**Comment by icraggs** [comment]
Closing as no further info.
