### ISSUE TITLE
MQTTAsync_processCommand calls callback before mqttasync_mutex is unlocked

### ISSUE THREAD

**Issue by Stannieman** [eclipse/paho.mqtt.c#1230]
Hi

I noticed that when MQTTAsync_processCommand (in MQTTAsyncUtils.c) calls the command's onSuccess or onFailure callbacks it does so before mqttasync_mutex is unlocked. Because of this it can deadlock if you try to do something else that will also lock the mutex from inside the callback (mutex is not recursive).

Is there a specific reason it's implemented like this? And should/can it be changed?

**Comment by icraggs** [comment]
Yes it's deliberate, to stop other potential timing issues. You can make other API calls to initiate operations, but nothing that will block (like waiitForCompletion), or anything that inquires on state and needs to take that lock (isConnected). I think those are the only two.

**Comment by Stannieman** [comment]
Ok thanks, we'll handle it on our side then!
