### ISSUE TITLE
Ubuntu 22.04 Support

### ISSUE THREAD

**Issue by max-os-lg** [eclipse/paho.mqtt.c#1234]
**Describe the bug**
It seems the library is not yet supported on Ubuntu 22.04.  
When trying to install I get:  

```
The following packages have unmet dependencies:
 libpaho-mqtt : Depends: libssl1.1 (>= 1.1.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

```

** Environment (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04

**Comment by stuqqq** [comment]
It looks like you haven't installed libssl1.1.
You can try the following command to install ```sudo apt-get install libssl-dev```

**Comment by icraggs** [comment]
I think this is answered.
