### ISSUE TITLE
use MQTTAsync_responseOptions set user-defined token,but successcallback return autoincrement token instead of user-defined token

### ISSUE THREAD

**Issue by stuqqq** [eclipse/paho.mqtt.c#1238]
**Question**
use MQTTAsync_responseOptions set user-defined token,but sendsuccesscallback return auto-increment token instead of user-defined token. 

How to use a user-defined Token?

**To Reproduce**
```
    MQTTAsync_responseOptions opts = MQTTAsync_responseOptions_initializer;
    ........
    opts.token = (MQTTAsync_token)UserDefined_token;
    ......
    MQTTAsync_sendMessage(client, Itopic, &pubmsg, &opts));
```
   > Debug Log:
```
   set UserDefinedtoken: 702636
   [MQTT]Message with token value 2 delivery confirmed
   set UserDefinedtoken: 704632
   [MQTT]Message with token value 3 delivery confirmed
```
**Expected behavior**
Return the user-defined token.

** Environment (please complete the following information):**
 - OS: [Win10]
 - Version [1.3.9]
 - Mqtt:
 - - Qos:2
 - - keepsession
 - - restoreMessages

**Comment by stuqqq** [comment]
At the latest MQTTAsync.c file.In line 1250 `response->token = pub->command.token;`
```	
{
	pub->command.onSuccess = response->onSuccess;
	pub->command.onFailure = response->onFailure;
	pub->command.onSuccess5 = response->onSuccess5;
	pub->command.onFailure5 = response->onFailure5;
	pub->command.context = response->context;
	response->token = pub->command.token;
	if (m->c->MQTTVersion >= MQTTVERSION_5)
		pub->command.properties = MQTTProperties_copy(&response->properties);
}
```
respose->token is an output parameter only too?

**Comment by icraggs** [comment]
Yes, it's an output only token. The value is set by the library automatically.

**Comment by icraggs** [comment]
Updated doc.

**Comment by icraggs** [comment]
Added doc
