### ISSUE TITLE
Update Online Documentation

### ISSUE THREAD

**Issue by ghost** [eclipse/paho.mqtt.c#1240]
**Describe the bug**
The documentation hosted here (as mentioned in the README):
https://www.eclipse.org/paho/files/mqttdoc/MQTTClient/html/index.html
is almost four years old.

It would probably be worth updating this documentation to something more recent as there are plenty of documentation bugs and clarifications that have been published since then. Sure, someone could generate the docs locally, but a lot of people (like myself) start by perusing the hosted documentation.

**To Reproduce**
Got to hosted documentation.

**Expected behavior**
Expect documentation from the latest release.

**Comment by icraggs** [comment]
The documentation is now here: https://eclipse.github.io/paho.mqtt.c/MQTTClient/html/

I'll update the readme

**Comment by icraggs** [comment]
Done
