### ISSUE TITLE
mqtt ssl connect cloud failed error cb is 1973408736:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1914:

### ISSUE THREAD

**Issue by yuandonglp** [eclipse/paho.mqtt.c#1241]
**Is your feature request related to a problem? Please describe.**
use mqtt ssl to connect cloud failed,  func ssl_error_cb report: error cb is 1973408736:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1914:
without ssl  it can connect cloud success
openssl version is 1.1.1m
code
    MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;
    conn_opts.MQTTVersion = MQTTVERSION_3_1_1;
    conn_opts.keepAliveInterval = 60;
    conn_opts.cleansession = 1;
    conn_opts.username = userName;
    conn_opts.password = passWord;
    conn_opts.onSuccess = onConnect;
    conn_opts.onFailure = onConnectFailure;
    conn_opts.context = client;
    
    if (useSSL) 
    {
        MQTTAsync_SSLOptions ssl =MQTTAsync_SSLOptions_initializer;
        ssl.ssl_error_cb = ssl_error_cb;
        printf("1ssl -> struct id =%s\r\n",ssl.struct_id);
        printf("1ssl -> struct_version =%d\r\n",ssl.struct_version);
        ssl.enableServerCertAuth = 0;
        conn_opts.ssl = &ssl;
    } 
    else 
    {
        conn_opts.ssl = NULL;
    } 
    
    conn_opts.automaticReconnect = 0;
    conn_opts.connectTimeout = 20;
    
    if ((rc = MQTTAsync_connect(client, &conn_opts)) != MQTTASYNC_SUCCESS) 
    {
        printf("[5G] : Failed to start connect, return code %d\n", rc);
        return rc;//connect failure
    }
    else
    {
	    //printf("[5G] : connect success\r\n");
    }
    return 0;//connect suces

**Comment by icraggs** [comment]
Seeing the rest of the SSL log output might help. A client library trace at the PROTOCOL level would do that.

But I think you probably do want to verify the server certificate, don't you? That would be good practice. The cloud provider should give details on the CA certificate you need to use for that.
