### ISSUE TITLE
HOW TO dynamic link the library paho-mqtt3cs

### ISSUE THREAD

**Issue by WangFengtu1996** [eclipse/paho.mqtt.c#1251]
Hi,all
* I want to use cmake to manage the whole project about the third-party library imported by source code , like paho-mqtt3cs. I search the way in the internet, I got the way maybe solve my  need. But a link error that con not find dynamic library paho-mqtt3cs is got.  
* some detail information are in the github project issue. https://github.com/intel-iot-devkit/people-counter-cpp/issues/10#issue-1309274653

Thanks for your time.

**Comment by icraggs** [comment]
You'd probably be better off asking this on a CMake mailing list or forum, or StackOverflow.

The CMake configuration in this project might help, as it builds sample programs and tests, both of which link that library.
