### ISSUE TITLE
undefined reference error while using pre-built version

### ISSUE THREAD

**Issue by ChaoticEar** [eclipse/paho.mqtt.c#1253]
Hi,

I downloaded [Eclipse-Paho-MQTT-C-1.3.10-Linux.tar.gz](https://github.com/eclipse/paho.mqtt.c/releases/download/v1.3.10/Eclipse-Paho-MQTT-C-1.3.10-Linux.tar.gz) the linux pre-built libs to work on my project. My code is running on Ubuntu 18.04 with cmake version 3.10

my CmakeLists with mqtt part are as follows:
`
set(eclipse-paho-mqtt-c_DIR ../3rdparty/mqtt/lib/cmake/eclipse-paho-mqtt-c)

find_package(eclipse-paho-mqtt-c REQUIRED)

include_directories(../3rdparty/mqtt/include)

target_link_libraries(ZIC_XXX ${eclipse-paho-mqtt-c_LIBS})
`

ZIC_XXX is a static lib of my project. When I try to build the whole project, I get error message as follows:

====================[ Build | demo | Debug ]====================================
/usr/bin/cmake --build /home/frank/work/project/DEV_LD_FUSION/cmake-build-debug --target demo -- -j 8
Scanning dependencies of target ZIC_XXX
[ 25%] Building C object lib_dev/CMakeFiles/ZIC_XXX.dir/src/ZIC_XXX.c.o
[ 50%] Linking C static library ../bin/libZIC_XXX.a
[ 50%] Built target ZIC_XXX
[ 75%] Linking C executable ../bin/demo
../bin/libZIC_XXX.a(ZIC_XXX.c.o): In function `ZIC_run':
/home/frank/work/project/DEV_LD_FUSION/lib_dev/src/ZIC_XXX.c:74: undefined reference to `MQTTClient_create'
/home/frank/work/project/DEV_LD_FUSION/lib_dev/src/ZIC_XXX.c:85: undefined reference to `MQTTClient_connect'
/home/frank/work/project/DEV_LD_FUSION/lib_dev/src/ZIC_XXX.c:94: undefined reference to `MQTTClient_publishMessage'
/home/frank/work/project/DEV_LD_FUSION/lib_dev/src/ZIC_XXX.c:96: undefined reference to `MQTTClient_waitForCompletion'
/home/frank/work/project/DEV_LD_FUSION/lib_dev/src/ZIC_XXX.c:100: undefined reference to `MQTTClient_disconnect'
/home/frank/work/project/DEV_LD_FUSION/lib_dev/src/ZIC_XXX.c:101: undefined reference to `MQTTClient_destroy'
collect2: error: ld returned 1 exit status
demo/CMakeFiles/demo.dir/build.make:95: recipe for target 'bin/demo' failed
make[3]: *** [bin/demo] Error 1
CMakeFiles/Makefile2:140: recipe for target 'demo/CMakeFiles/demo.dir/all' failed
make[2]: *** [demo/CMakeFiles/demo.dir/all] Error 2
CMakeFiles/Makefile2:152: recipe for target 'demo/CMakeFiles/demo.dir/rule' failed
make[1]: *** [demo/CMakeFiles/demo.dir/rule] Error 2
Makefile:131: recipe for target 'demo' failed
make: *** [demo] Error 2

my project structure are
-project
     |-3rdparty
     |    |-mqtt
     |    |-bin
     |    |-include
     |    |-lib
     |    |-share
     |-demo
     |    |-main.c
     |-lib_dev
     |    |-include
     |    |-src

I untar all the files into project/3rdparty/mqtt
How can I avoid the undefined error, should I change something in my cmakelists?

**Comment by icraggs** [comment]
It's probably better to ask this question in a CMake support forum. You should make sure you are using the right library - libpaho-mqtt3a is the async library (MQTTAsync) whereas you need libpaho-mqtt3c for the MQTTClient calls.

**Comment by icraggs** [comment]
Closing as answered.
