### ISSUE TITLE
is_ connected() still returns true without network

### ISSUE THREAD

**Issue by xdy6248625** [eclipse/paho.mqtt.c#1257]
In the main process of my project, I run a thread to detect whether the connection is disconnected. The approximate code is as follows:

```cpp
//main process
monitor();
//...
void monitor() {
  monitor_thread = std::make_shared<std::thread>([this]() {
    if(!myClient->is_connected()) {
      LOG_INFO << "client disconnect";
      my_client->PubReconnect();
      sleep(1);
    }
    sleep(1); 
    }
  );
}
```
If myClient.is_connected() returns false, run Pubreconnect() to reconnect. During a test, I found that in the case of network disconnection, myClient.is_ connected()  still return true. I manually disconnected the network for several times during the operation and found that this unstable situation did occur.
In addition, my reconnection function code is as follows:

```cpp
bool PubReconnect() {
    while(!myClient->is_connected()) {
        try{
            myClient->connect(_connopts);
            sleep(1);
        } catch(const mqtt::exception&e) {
            LOG_ERROR << "publish reconnect fail for: " << e.what();
            sleep(1);
        }
    }
    LOG_INFO << "publish reconnect success";
    return true;
}
```
And also, when there is no network connection,  the functoun Pubreconnect() will hang after running a certain number of times.
I don't know whether this problem is caused by the thread calling the function in a short time. I sincerely ask for your help, Thank you very much!
If you think my description is unclear or you need me to provide more information, I will reply to you as soon as possible. Thank you again sincerely.

**Comment by icraggs** [comment]
The issue template is a good guide for information asked for.

You don't say which API you are using - MQTTClient or MQTTAsync, or what version.

The is_connected() function call is always going to be less efficient than using the connection lost callback, which is there explicitly for this. The loss of connection is sometimes only able to be detected when the keepalive processing shows it, and the frequency of those checks is dictated by the keepalive interval.

So I would advise using the connection lost callback.

**Comment by xdy6248625** [comment]
> The issue template is a good guide for information asked for.
> 
> You don't say which API you are using - MQTTClient or MQTTAsync, or what version.
> 
> The is_connected() function call is always going to be less efficient than using the connection lost callback, which is there explicitly for this. The loss of connection is sometimes only able to be detected when the keepalive processing shows it, and the frequency of those checks is dictated by the keepalive interval.
> 
> So I would advise using the connection lost callback.

Thank you ! I'm using MQTTAsync.I'll try to use connection lost callback. In addition, I would like to humbly ask you that even if I do not set the min and maxRetryInterval, my client can still automatically reconnect after my network is restored.I don't see that they are set with the default initial value in the source code.

**Comment by icraggs** [comment]
The min and maxRetryInterval are set to 1 and 60 by the MQTTAsync_connectOptions_initializer
