### ISSUE TITLE
Fakeroot installation dependency is mentioned twice in README

### ISSUE THREAD

**Issue by Hadatko** [eclipse/paho.mqtt.c#1260]
**Describe the bug**
Handled in topic

**To Reproduce**
Take a library trace as outlined in the README, and/or have a program or describe the steps to reproduce the behavior:
1. Go to '...' top README file

**Expected behavior**
Mention dependency just one

**Screenshots**
![image](https://user-images.githubusercontent.com/13130700/185900408-cdc3ba32-bd5e-406d-8568-f18105302391.png)

**Log files**
Please try to attach log files rather than pasting the log contents. It makes the issues easier to read.

** Environment (please complete the following information):**
 - OS: [e.g. Linux]

**Additional context**

**Comment by icraggs** [comment]
Fixed - thanks
