### ISSUE TITLE
MQTTClient_publish can not return

### ISSUE THREAD

**Issue by styfstr** [eclipse/paho.mqtt.c#1263]
Hi，
I am calling MQTTClient_publish from inside a messageArrived callback. Sometimes the MQTTClient_publish blocks and cannot return. Is this a normal phenomenon? Should I not call MQTTClient_publish in messageArrived callback?

If the locking problem is normal, are there any good suggestions to avoid it?

Thanks！

**Comment by icraggs** [comment]
You mustn't make any MQTTClient API calls in any callback, except for Connect in the ConnectionLost callback. If you want to do this sort of thing, you can use the MQTTAsync API, which does allow it.

**Comment by icraggs** [comment]
I think this is answered.
