### ISSUE TITLE
The eclipse-paho-mqtt-c-win64-1.3.10.zip archive only contains static lib files, rather than the dynamic-link lib and dll files

### ISSUE THREAD

**Issue by KevinChri** [eclipse/paho.mqtt.c#1264]
The **lib** folder in the "eclipse-paho-mqtt-c-win64-1.3.10.zip" archive on the "releases" web page contains only four "______static.lib" files.

I did not expect this, since in previous release versions, that folder has contained eight dynamic-link lib and dll files.

I tried to use these "______static.lib" files in various versions of Microsoft Visual Studio and was unable to link against them.

**Comment by icraggs** [comment]
Should be fixed in the 1.3.11 release
