### ISSUE TITLE
can't publish json payload

### ISSUE THREAD

**Issue by SaimShuja** [eclipse/paho.mqtt.c#1269]
**Describe the bug**
i can'y publish json payload to mqtt 

**To Reproduce**
Take a library trace as outlined in the README, and/or have a program or describe the steps to reproduce the behavior:
1. started from the [src/samples/MQTTClient_publish.c/](https://github.com/eclipse/paho.mqtt.c/blob/master/src/samples/MQTTClient_publish.c)

`
char *PAYLOAD = (char *)malloc(50 * sizeof(char));
const char *s;
struct json_object *jobj;

float temperature, humidity, lux, pm25;

for (int i = 0; i < 10; i++)
{
    printf("-------- %i ---------\n", i);
    temperature = humidity = lux = pm25 = i * 2;

    time_t t = time(NULL);
    struct tm tm = *localtime(&t);
    sprintf(PAYLOAD, "
                     "{ \"messageId\":  %i , \
		\"date\": \"%02d:%02d:%02d\",  \
		\"devicename\": \"%s\" , \
		\"operator\": \"update\" , \
    \"info\" : [ \
    { \
      \"temp\": \"%f\", \
      \"hum\": \"%f\", \
      \"pm25\": \"%f\", \
      \"lux\": \"%f\", \
    } \
    ] \
    }",
            i, tm.tm_hour, tm.tm_min, tm.tm_sec, CLIENTID, temperature, humidity, pm25, lux);
    jobj = json_tokener_parse(PAYLOAD);
    s = json_object_get_string(jobj);
    printf("json to publish:\n---\n%s\n---\n", s);

    pubmsg.payload = (void *)s;
    pubmsg.payloadlen = (int)strlen(s);
    pubmsg.qos = QOS;
    pubmsg.retained = 0;

    if ((rc = MQTTClient_publishMessage(client, TOPIC, &pubmsg, &token)) != MQTTCLIENT_SUCCESS)
    {
        printf("Failed to publish message, return code %d\n", rc);
        exit(EXIT_FAILURE);
    }
}`

3. compile using `gcc test.c  -ljson-c -lpaho-mqtt3c -o test1`
4. program when run by "./test1"
5. it crashes saying "munmap_chunk(): invalid pointer"

**Expected behavior**
publish the json to mqtt topic.

**Screenshots**
[screenshot](https://imgur.com/a/clJ4AbU)

**Log files**
Please try to attach log files rather than pasting the log contents. It makes the issues easier to read.

** Environment (please complete the following information):**
Linux raspberrypi 5.15.61-v7+ #1579 SMP Fri Aug 26 11:10:59 BST 2022 armv7l GNU/Linux

**Additional context**
error occurs on line `pubmsg.payload = (void *)s;`

**Comment by icraggs** [comment]
This is a C question, not an MQTT library question. You should ask this in a C subject forum,

You've probably overwritten the pubmsg variable storage, as you've allocated 50 bytes for PAYLOAD, but then copied about 200 bytes into that location (the length of the JSON string).

**Comment by SaimShuja** [comment]
Thankyou soo much @icraggs for reply .. 
You are absolutely right about the variable storage allocation and the size , will fix that .. 

Can you share a link or document or some piece of code in which json is sent as payload using paho mqtt .
Thankyou

**Comment by icraggs** [comment]
If you use the sample program paho_c_pub, you can put some json code into a file and use the -f option to send the contents of the file. I suggest you take a look at that.

**Comment by SaimShuja** [comment]
> You've probably overwritten the pubmsg variable storage, as you've allocated 50 bytes for PAYLOAD, but then copied about 200 bytes into that location (the length of the JSON string).

Bro this fixed it I increased the amount of memory allocated for PAYLOAD to 250, and now works perfectly.
thankyou for your guidance.
