### ISSUE TITLE
compiler error C2371 when compiling with USE_SELECT

### ISSUE THREAD

**Issue by stefankueng** [eclipse/paho.mqtt.c#1271]
when USE_SELECT is defined, I get a compiler error C2371:
`pahoMqtt\c\src\Socket.c(356,5): error C2371: 'Socket_getReadySocket': redefinition; different basic types`

The problem is that in socket.c, the function Socket_getReadySocket is defined as
`int Socket_getReadySocket(int more_work, int timeout, mutex_type mutex, int* rc)`
with USE_SELECT defined, but in the header socket.h the function is set as
`SOCKET Socket_getReadySocket(int more_work, int timeout, mutex_type mutex, int* rc);`

note `SOCKET` and `int `as the return values.

the header needs an ifdef as well.

Using VS2022 to compile.

**Comment by icraggs** [comment]
Fix added to develop branch
