### ISSUE TITLE
Can't run mosquitto 2.0.15 with the Paho C config/certs

### ISSUE THREAD

**Issue by fpagliughi** [eclipse/paho.mqtt.c#1273]
I'm trying to run mosquitto v 2.0.15 using the SSL test certificates and configuration, but am getting an error. This is on Ubuntu Linux 20.04.

```
$ cd paho.mqtt.c
$ mosquitto -c test/tls-testing/mosquitto.conf
1664832137: mosquitto version 2.0.15 starting
1664832137: Config loaded from test/tls-testing/mosquitto.conf.
1664832137: Opening ipv4 listen socket on port 1883.
1664832137: Opening ipv6 listen socket on port 1883.
1664832137: Opening ipv4 listen socket on port 18883.
1664832137: Opening ipv6 listen socket on port 18883.
1664832137: Opening ipv4 listen socket on port 18884.
1664832137: Opening ipv6 listen socket on port 18884.
1664832137: Error: Unable to load server certificate "test/ssl/server.crt". Check certfile.
1664832137: OpenSSL Error[0]: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small
```
Is this a problem that can be fixed here? Or is is a mosquitto problem? Or an OpenSSL version issue?

It looks like maybe we should generate new keys that are at least 2048 bits?

**Comment by icraggs** [comment]
I don't remember this mosquitto configuration being there. From the git history it looks like the last update was about 2018 so whatever mosquitto version was current at the time presumably wiorks.

I now always use the broker in paho.mqtt.testing, as do the CI tests, so whatever changes are made need to make sure that still works. 

Further investigation seems to show this is linked to the OpenSSL security level: 

https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_security_level.html

I think he default level changed to 2 in recent versions of OpenSSL. The broker in paho.mqtt.testing set the seclevel to 1 for now to allow the current configuration to continue to work.

I created an issue to be able to set this in the client: https://github.com/eclipse/paho.mqtt.c/issues/981

**Comment by fpagliughi** [comment]
Oh, funny. I had assumed this was being used by the test code to make some known connection and failures to verify against. It's using the testing server?

I've been using the mosquitto configuration for years to test the SSL examples in the C++ and Rust libraries - with the associated certificates.

It looks like there's a script in the `test/ssl` directory to regenerate the certificates:
https://github.com/eclipse/paho.mqtt.c/blob/master/test/ssl/gen.sh

This has hard-coded the keys to 1024 bits all over the place, like:
https://github.com/eclipse/paho.mqtt.c/blob/7c0735a5f02052c275baddb4f01f1f4dabdfed20/test/ssl/gen.sh#L20

If we make a variable for that, we can set it to a higher value and change it easily, like:
```
KEY_LEN=2048

openssl genrsa -out test-root-ca.key ${KEY_LEN}
...
```
This appears to update the certs in `test/ssl`, and seems fix them up nicely.

But the mosquitto configuration also uses some certs in `test/tls-testing/keys/server/`, particularly one, `server-mitm` to simulate a man-in-the-middle attack. That doesn't appear to be one from the `gen.sh` script. I don't know how that one was created.

**Comment by fpagliughi** [comment]
Oh, BTW, I'm agnostic as to the best way to fix all of this. It's probably time to regenerate the certificates - and we might as well make them 2048 bits.

But if you're not using the mosquitto configuration it would probably be better to remove it than to leave it in the repo in a broken state. I can copy what I need from here and put it in with the Rust and C++ libraries.

**Comment by icraggs** [comment]
I think regenerating the certificates to make it work with the current default OpenSSL security level is the best option. If you create a PR with the changes then the CI tests will check them out. The corresponding certs in the paho.mqtt.testing wioll need updating too.

The comment for the mitm certs in the config file says "uses fake hostname to simulate mitm attack".

I think one of the reasons I used the Python broker in the CI tests was due to the ease of installation and running in the CI environments, especially in Windows.

**Comment by dawagner** [comment]
I found this ticket while trying to understand how to run the tests.

The README says to use `python ../test/mqttsas2.py` but this script doesn't exist anymore. I dug into the issue tracker and found https://github.com/eclipse/paho.mqtt.c/issues/273 that mention the mosquitto setup but as this ticket explain, it doesn't work anymore, either.

Would you mind taking the opportunity to update the documentation, please?

**Comment by ARUN-ROOT** [comment]
hi 
i need some help how to Create publish and subscribe the MQTT topic using Mosquitto MQTT library in C
i am using MOSQUITTO MQTT V 2.0.15
Give any suggestion any link

**Comment by icraggs** [comment]
@dawagner the files appveyor.yml and travis-build.sh show how to run the tests on windows and Linux/Mac respectively. The script doesn't have the 2 on it any more. I'll correct the README.

**Comment by icraggs** [comment]
@ARUN-ROOT the place to discuss the Mosquitto client libraries is here: https://github.com/eclipse/mosquitto 

This repo is for the Paho MQTT C libraries only.  Thanks.

**Comment by icraggs** [comment]
@fpagliughi I've just updated the certs in the develop branch as they had expired in March. I updated them to 2048 bits at the same time, so this hopefully should have resolved this issue too.

**Comment by icraggs** [comment]
I'll add the same changes to the other branches asap.
