### ISSUE TITLE
MQTTAsync_reconnect does not reset the retry wait variables, causing long delays

### ISSUE THREAD

**Issue by jens-f** [eclipse/paho.mqtt.c#1274]
**Describe the bug**
When using a connection that has auto-retry enabled and this connection is trying to connect for a long time unsuccessfully, then calling `MQTTAsync_reconnect` does not trigger an immediate reconnect. Instead, it will simply wait until the next regular retry, which might take a long time.

**To Reproduce**
1. Setup a connection with 
```
    connOpts.automaticReconnect = 1;
    connOpts.retryInterval = 30;
    MQTTAsync_connect(pahoClient, &connOpts)
```
2. make sure that the mqtt broker is not on or reachable (we want the connection attempt to fail)
3. let the mqtt connection retry for a while. Paho's `MQTTAsync_startConnectRetry` will increase `m->currentIntervalBase` to minutes of wait in-between attempts
4. call `MQTTAsync_reconnect`
5. observe how the reconnect will not take place and instead the next attempt is made when `m->currentIntervalBase` is up

**Expected behavior**
When `MQTTAsync_reconnect` is called in the `automaticReconnect` scenario, `m->currentIntervalBase` should be reset to 0 so that the next attempt is made immediately when calling. Right now this is only happening when `m->retrying` is false but it should also happen in the case when a connection couldn't be established previously

** Environment (please complete the following information):**
 - OS: Linux
 - Paho Version: 1.3.11

**Comment by jens-f** [comment]
Actually I noticed that in `MQTTAsync_reconnect` there's also `m->reconnectNow = 1`, so the first attempt is without the wait, but if that fails it goes back to the long wait instead of gradually increasing it again. It'd be great if `reconnect` could reset `currentIntervalBase` to 0 in any case

**Comment by icraggs** [comment]
That makes sense. It was resetting the intervals only if the auto reconnect process wasn't running at all. I've put a change in to the develop branch to reset the intervals whenever reconnect is called.
