### ISSUE TITLE
Executable linked against paho-mqtt3as.dll stops working on Windows 2012 OS

### ISSUE THREAD

**Issue by nirmitdesai** [eclipse/paho.mqtt.c#1275]
**Describe the bug**
I am unable to launch an application linked against paho-mqtt3as.dll on Windows 2012 OS because OS throws an error:
No such error with previous version of paho library.

**To Reproduce**
Launch any executable linking against paho dll on windows 2012 OS

**Expected behavior**
Application should be launched successfully

**Screenshots**
Below, you can see that the DLL was  loaded in dependency walker and SetThreadDescription function wasn't found
![image](https://user-images.githubusercontent.com/1423848/194433896-33db0887-6578-4c72-8094-d0844c3aa846.png)

**Log files**
N/A

** Environment (please complete the following information):**
 - OS: Windows 2012
 - Version 1.3.11

**Additional context**

Whenever the application is launched, windows shows an error message "The procedure entry point SetThreadDescription could not be located in the dynamic link library C:\path\to\paho-mqtt3as.dll"
SetThreadDescription  was submitted as part of https://github.com/eclipse/paho.mqtt.c/issues/1100 

As per https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setthreaddescription, Windows Server 2016, Windows 10 LTSB 2016 and Windows 10 version 1607: SetThreadDescription is only available by [Run Time Dynamic Linking](https://learn.microsoft.com/en-us/windows/win32/dlls/using-run-time-dynamic-linking) in KernelBase.dll
But on Windows 2012, no implementation is available.

So I feel the right way to fix this would be to use run time dynamic linking instead of load time dynamic linking, since you don't know if at runtime, this method will be available or not.
I came across https://github.com/arangodb/arangodb/commit/c6972fcdf8452ee26e75e886e83ed6323becca10 which did similar fix.

For now, I just avoided compilation of line https://github.com/eclipse/paho.mqtt.c/blob/master/src/Thread.c#L90 and then executable can be launched fine.

**Comment by icraggs** [comment]
I've removed the call entirely for now due to not being able to get the conditional compilation correct. It may not be possible on Windows.
