### ISSUE TITLE
MQTTAsync_subscribe causing crash when both subscribe and publish happens at the same time

### ISSUE THREAD

**Issue by sudipto1995** [eclipse/paho.mqtt.c#1278]
**Describe the bug**
When there is simultaneous publish/subscribe occurring at the same topics, then the MQTTAsync_subscribe call crashes.

**To Reproduce**
Create a connection from a device to a broker. Create another connection from a system to the same broker
Publish to topics (eg., Topic1, Topic2,....Topic200)
Subscribe to the same topics from the system at the same time
During the MQTTAsync_subscribe call, the application crashes without any return code

**Expected behavior**

**Screenshots**

**Log files**
Please try to attach log files rather than pasting the log contents. It makes the issues easier to read.

** Environment (please complete the following information):**
 - OS: win64
 - Version: 

**Additional context**
I am using the paho v1.3.10

**Comment by sudipto1995** [comment]
Any information on this?

**Comment by icraggs** [comment]
Could you provide a client library trace, or debugger stack? Or a sample program or code snippet?

What do you mean by the same time? Are you using multiple threads? How many?

**Comment by sudipto1995** [comment]
The issue is resolved now. It turned out that the MQTTAsync_subscribe call is taking time to execute which was causing a pre-emption into the callback handler of MQTT message received. Since both were using the same mutex, the execution was going into an infinite waiting stage.
