### ISSUE TITLE
Thread_set_name broken on Windows

### ISSUE THREAD

**Issue by stefankueng** [eclipse/paho.mqtt.c#1280]
**Describe the bug**
the function Thread_set_name() uses a `const char*,` but then simply casts that string to a wide string without actually converting it to a wide string. Which leads to garbage chars for the thread name.

**Expected behavior**
convert the string to a wide string, do not just cast it to a wide string.

https://github.com/eclipse/paho.mqtt.c/blob/7c0735a5f02052c275baddb4f01f1f4dabdfed20/src/Thread.c#L90

**Comment by icraggs** [comment]
Same as #1275

**Comment by nirmitdesai** [comment]
It's bit different from issue#1275 because for this issue, the fix is to convert string to wide string first. But in case of issue#1275, you would have to use runtime dynamic linking (via LoadLibrary and GetProcAddress) instead of load time dynamic linking.

Thanks again for your effort!

**Comment by icraggs** [comment]
Given that I don't seem to be able to work out how to avoid making this call for the versions of Windows that don't support it, I'll probably just remove it on Windows for now.

**Comment by icraggs** [comment]
I've put in a change which should hopefully fix this.

**Comment by icraggs** [comment]
But I've also commented out the call entirely on Windows due to not being able to get the backward compatibility right.
