### ISSUE TITLE
Subscriber MQTTAsync_message->retained is set to 0 for a message published with a 'retain' flag

### ISSUE THREAD

**Issue by BinduRao2018** [eclipse/paho.mqtt.c#1281]
**Describe the bug**
MQTTAsync_message->retained is set to false for a message published with a 'retain' flag. Shouldn't this return 'true'?
According to the API description - (MQTTAsync.h), 'retained' set to false indicates that this is a normal message.  
For existing subscribers, a published message with a retain flag is a normal message and for late-joining subscribers, the message indicates it is a retained message.

**To Reproduce**
1. Set msgarvd_callback using MQTTAsync_setCallbacks and subscribe to a topic
2. Publish a message with the 'retain' flag set using mosquitto_pub 
3. Check for `MQTTAsync_message->retained` returned in the callback. The value is set to 0 instead of 1

**Expected behaviour**
MQTTAsync_message->retained, should reflect the message type set at the publisher's end

** Environment (please complete the following information):**
 -  OS - Linux
 - Version: 1.3.11

**Comment by icraggs** [comment]
The retained flag is not propagated when the message is first published. The retained flag is only received by a subscriber when it subscribes to a topic which has a retained message set.

This behaviour cannot be changed in MQTT 3.1.1, but it can be in MQTT 5.0:

_Bit 3 of the Subscription Options represents the Retain As Published option. If 1, Application Messages forwarded using this subscription keep the RETAIN flag they were published with. If 0, Application Messages forwarded using this subscription have the RETAIN flag set to 0. Retained messages sent when the subscription is established have the RETAIN flag set to 1._

**Comment by icraggs** [comment]
I think this is answered.
