### ISSUE TITLE
Trying to compile this lib to 32 bit in a 64 bit OS

### ISSUE THREAD

**Issue by Hzfd** [eclipse/paho.mqtt.c#1282]
**Describe the bug**
Hello I am a student from Brazil. I am doing my final project of engineering and need to make this lib run with FOCAS lib that is a 32 bit lib. I had followed the instructions and add some more option to build the lib in 32 bit, but it always fails when i try to build

**To Reproduce**
Take a library trace as outlined in the README, and/or have a program or describe the steps to reproduce the behavior:
1. follow the tutorial in the github page and give those arguments at cmake build:
  $cmake -DPAHO_WITH_SSL=TRUE -DPAHO_BUILD_DOCUMENTATION=TRUE \
    -DPAHO_BUILD_SAMPLES=TRUE -DCMAKE_CXX_FLAGS=-m32 DCMAKE_C_FLAGS=-m32 ~/paho.mqtt.c

2. whith those comands it should fail while building

I don't know much about coding or computer engineering, so if there is a way to compile this lib to run with another 32bit lib please tell me how.

thaks for the attention.

**Comment by icraggs** [comment]
I assume you're trying to build for Windows.

The appveyor builds for Windows are here: https://ci.appveyor.com/project/eclipsewebmaster/paho-mqtt-c

Two are 64 bit, one 32. The configuration is in appveyor.yml

It depends how you set the environment variables, at least in the way I build. Call vcvarsall.bat to set the environment with an argument of x86 or x64 for 32 ot 64 bit builds respectively.

**Comment by icraggs** [comment]
I think this is answered.
