### ISSUE TITLE
Automatic reconnect does not work when initial connection fails

### ISSUE THREAD

**Issue by nandlab** [eclipse/paho.mqtt.c#1288]
I would like to connect the mqtt client to the broker, and if the connection fails, automatically reconnect until the connection is established again.

I tried to use the automatic reconnect option for that. But I noticed that it only reconnects when the connection was already established and later lost. However if the initial connection fails, it does not try again automatically, so I have to reconnect manually.

Is there a way to tell the library that I want to keep trying to connect to the broker until it succeeds?

**Comment by icraggs** [comment]
That was a deliberate decision to do that when I first implemented it, but I have a recollection of changing it at a later date. I'll look into it.

What OS are you using? And what version of the library - the latest?

**Comment by nandlab** [comment]
My OS is `Devuan GNU/Linux 4 (chimaera) x86_64`.
I am using paho.mqtt.c version `1.3.9` and did not upgrade to the latest version yet.

I had to implement the initial reconnect after a delay using a boost asio timer, which was not very convenient.

I just wondered if the reconnect behaviour changed in the newer version of the library.

**Comment by icraggs** [comment]
I just used the latest version in the develop branch (there are some keepalive fixes over 1.3.11) and it connects successfully if the first connect doesn't work. You could see if that works for you.

**Comment by nandlab** [comment]
Thank you! I will try it out.

**Comment by nandlab** [comment]
It works!

**Comment by applea9** [comment]
Hi, 

I tested it with 1.3.10 and this function can work well. 

Could you give a hint that when this function is supported ?

thanks.

**Comment by nandlab** [comment]
Auto-reconnect works fine in 1.3.12.

**Comment by applea9** [comment]
@nandlab  Did you ever test with 1.3.10?

**Comment by nandlab** [comment]
I did not test with 1.3.10 or 1.3.11.
