### ISSUE TITLE
v1.3.11 Async subscribe connection lost with QoS0 

### ISSUE THREAD

**Issue by ImreSzebelledi** [eclipse/paho.mqtt.c#1292]
**Describe the bug**
I am am experiencing a strange behaviour when connection is dropped when I use async subscription qith QoS0 using version 1.3.11 within a minute after subscription start.
I cannot reproduce this in 1.3.10.

**To Reproduce**
1. Check out v1.3.11
2. Generate project with cmake
3. Modify samples: MQTTAsync_subscribe.c to subscribe to MQTTAsync_publish_time "data\time" topic and change broker address to localhost.
4. Build samples
5. Start MQTTAsync_publish_time and MQTTAsync_subscribe

**Expected behavior**
Not to drop connection to broker or be able to reconnect and subscribe again.

**Screenshots**
Cmake:
![image](https://user-images.githubusercontent.com/35853114/201630611-561050fd-05a1-46cf-bba4-b15e37286a26.png)
Error:
![image](https://user-images.githubusercontent.com/35853114/201631438-a664dac4-4232-4e4d-8229-0dd159ae2570.png)
Source code modification:
![image](https://user-images.githubusercontent.com/35853114/201631594-51a47502-1691-4986-9f8b-942709301662.png)

**Log files**
Please try to attach log files rather than pasting the log contents. It makes the issues easier to read.

** Environment (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: 19044.2251

**Additional context**
I have tried using public brokers as well, but the behaviour is the same.

**Comment by jumoog** [comment]
Whats your value for keepalive?

**Comment by ImreSzebelledi** [comment]
I haven't changed it in the sample code, so it is 20.

**Comment by ImreSzebelledi** [comment]
If I change to QoS1, then everything works as expected.

**Comment by icraggs** [comment]
I've added a fix to the develop branch for #1276 #1277. This looks the same. If you would like to try it out. Thanks,
