### ISSUE TITLE
Does MQTTClient.h API work with MQTTCLIENT_PERSISTENCE_DEFAULT flag?

### ISSUE THREAD

**Issue by pakokol** [eclipse/paho.mqtt.c#1296]
**Describe the bug**
I have been trying to implement a way to persist undelivered messages due to network errors with the MQTTCLIENT_PERSISTENCE_DEFAULT flag upon client creation. I have also tested it with the MQTTAsync.h API and there it seems to work, but I need the classic MQTTClient API.  Am I missing a flag or is it not supposed to be used that way? Or should I implement a custom way for persisting messages using the MQTTCLIENT_PERSISTENCE_USER flag? Is there any example available as a starting point on how to use these PERSISTENCE flags?

**To Reproduce**

1. Start MQTT broker
2. Run code:
``` cpp
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "MQTTClient.h"
#include <thread>
#include <chrono>

#if !defined(_WIN32)
#include <unistd.h>
#else
#include <windows.h>
#endif

#define ADDRESS     "tcp://localhost:1883"
#define CLIENTID    "ExampleClient"
#define TOPIC       "MQTT Examples"
#define PAYLOAD     "Hello World!"
#define QOS         1
#define TIMEOUT     10000L

MQTTClient_deliveryToken deliveredtoken;

void delivered(void *context, MQTTClient_deliveryToken dt)
{
    printf("Message with token value %d delivery confirmed\n", dt);
    deliveredtoken = dt;
}

int msgarrvd(void *context, char *topicName, int topicLen, MQTTClient_message *message)
{
    printf("Message arrived\n");
    printf("     topic: %s\n", topicName);
    printf("   message: %.*s\n", message->payloadlen, (char*)message->payload);
    MQTTClient_freeMessage(&message);
    MQTTClient_free(topicName);
    return 1;
}

void connlost(void *context, char *cause)
{
    printf("\nConnection lost\n");
    printf("     cause: %s\n", cause);
}

int main(int argc, char* argv[])
{
    MQTTClient client;
    MQTTClient_connectOptions conn_opts = MQTTClient_connectOptions_initializer;
    MQTTClient_message pubmsg = MQTTClient_message_initializer;
    MQTTClient_deliveryToken token;
    int rc;

    if ((rc = MQTTClient_create(&client, ADDRESS, CLIENTID,
        MQTTCLIENT_PERSISTENCE_DEFAULT, NULL)) != MQTTCLIENT_SUCCESS)
    {
        printf("Failed to create client, return code %d\n", rc);
        rc = EXIT_FAILURE;
        goto exit;
    }

    if ((rc = MQTTClient_setCallbacks(client, NULL, connlost, msgarrvd, delivered)) != MQTTCLIENT_SUCCESS)
    {
        printf("Failed to set callbacks, return code %d\n", rc);
        rc = EXIT_FAILURE;
        goto destroy_exit;
    }

    conn_opts.keepAliveInterval = 20;
    conn_opts.cleansession = 1;
    if ((rc = MQTTClient_connect(client, &conn_opts)) != MQTTCLIENT_SUCCESS)
    {
        printf("Failed to connect, return code %d\n", rc);
        rc = EXIT_FAILURE;
        goto destroy_exit;
    }

    pubmsg.payload = (void*)PAYLOAD;
    pubmsg.payloadlen = (int)strlen(PAYLOAD);
    pubmsg.qos = QOS;
    pubmsg.retained = 0;
    deliveredtoken = 0;
    
	while (true)
	{
		std::this_thread::sleep_for(std::chrono::seconds(1));
		printf("Publishing message!");
		if ((rc = MQTTClient_publishMessage(client, TOPIC, &pubmsg, &token)) != MQTTCLIENT_SUCCESS)
		{
			printf("Failed to publish message, return code %d\n", rc);
		}
	}

    if ((rc = MQTTClient_disconnect(client, 10000)) != MQTTCLIENT_SUCCESS)
    {
    	printf("Failed to disconnect, return code %d\n", rc);
    	rc = EXIT_FAILURE;
    }

destroy_exit:
    MQTTClient_destroy(&client);

exit:
    return rc;
}
```
4. After the code successfully connects stop MQTT server

**Expected behavior**
Undelivered messages should be persisted in the created folder. 

** Environment:**
 - OS: Linux and Windows
 - Version 1.3.11

**Comment by icraggs** [comment]
The messages were persisted for me when I tried it. 

It's harder to force the condition where messages are left on disk than in the async client, because the calls are more synchronous, and message exchanges will tend to complete. Once the message exchange for QoS 1 or 2 completes, the message is deleted from disk. The directory is deleted from disk at the end if there are no messages persisted within it.

**Comment by pakokol** [comment]
OK. I have noticed that the files are actually created when the client is successfully connected to the broker. But when the client disconnects for some reason the messages are not being persisted. I have noticed that in the MQTTAsync client you have in the creation options a parameter called sendWhileDisconnected in order to persist also messages while disconnected. Does the MQTTClient stop persisting messages when disconnected?

**Comment by pakokol** [comment]
But messages shouldn't complete when the broker is down and the client tries to send messages despite being disconnected. Shouldn't the messages be stored on disk in that case?

**Comment by icraggs** [comment]
Yes the MQTTClient API does not allow sending messages when disconnected. You should get an error from the publish call. Sending while disconnected was a later addition to the MQTTAsync API. The MQTTClient API was meant to be very simple, so more complicated features would not be added to it.

**Comment by icraggs** [comment]
I think this has been answered.
