### ISSUE TITLE
When ConnectLost is invoked？

### ISSUE THREAD

**Issue by 2751466366** [eclipse/paho.mqtt.c#1299]
Hello, I use this library to set the heartbeat interval to 2 minutes. Why is the ConnectLost callback activated quickly when the network is unavailable? Sometimes it takes more than 2 minutes to activate.

**Comment by icraggs** [comment]
If there is no other traffic on the connection, sometimes the only way to find out if it's still working is to send some data. In this case, if you set a keep alive interval of 2 minutes, it will take up to two minutes to find out. If the send data works at the TCP level, but no response is received, then another 50% of the interval could elapse before it's decided that the connection is not alive.

**Comment by 2751466366** [comment]
Thank you for your reply.  That means if I send data when the network is unavailable, the sending will fail and the ConnectLost callback will be called. Is that right?

**Comment by icraggs** [comment]
connectionLost is only called if there was previously a successful connection, and now there isn't (it is "lost"). You don't say whether you are using the MQTTClient or MQTTAsync API, but in both cases, if you haven't ever successfully connected, you won't get connectionLost.

But if you set the keep alive interval to a long time, sometimes it will take up to 1.5 times the keep alive interval to detect the connection is lost, if you aren't sending any messages to the broker.

**Comment by 2751466366** [comment]
I see, thank you very much
