### ISSUE TITLE
should it call the _callback MQTTClient_connectionLost in MQTTProtocol_keepalive

### ISSUE THREAD

**Issue by LarkPix** [eclipse/paho.mqtt.c#1301]
https://github.com/eclipse/paho.mqtt.c/blob/7c0735a5f02052c275baddb4f01f1f4dabdfed20/src/MQTTProtocolClient.c#L728
when the network fails,mqtt disconnect through keepalive but it doesnt notify the upper layer
`MQTTClients *m = (MQTTClients*)(client->context);
(*(m->cl))(m->context, NULL);`
should it call the MQTTClient_connectionLost cl

**Comment by icraggs** [comment]
The call to connectionLost works for me when the keepalive fails - it gets no response to a PINGREQ. I tried both master and develop branches.

If your situation is different you should take a client library trace and tell me the version of the library you are using, as requested in the issue template. Thanks.

**Comment by icraggs** [comment]
Version 1.3.11 had an issue with detecting network failures. If that was the source of your problem you should try 1.3.12.
