### ISSUE TITLE
v1.3.11 can not reconnect when mqtt keepalive timeout

### ISSUE THREAD

**Issue by orangice1997** [eclipse/paho.mqtt.c#1306]
version: v1.3.11
here DISCONNECT code is 0. but in my other router is -1, that can reconnect successfully

20221101 205536.914 3 client -> PINGREQ (0)
20221101 205543.623 PINGRESP not received in keepalive interval for client client on socket 3, disconnecting
20221101 205544.725 3 client -> DISCONNECT (0)
20221101 205544.725 SSL alert write:warning:close notify

**Comment by icraggs** [comment]
You don't say which version you're using. If you're using 1.3.11, try 1.3.10. Or try building with the -DREVERSED compile option. One of those should work. You could let me know which.

**Comment by orangice1997** [comment]
i add some patch for myself, then can reconnect
![image](https://user-images.githubusercontent.com/86704705/208335162-e446588d-3bd7-497c-8848-c557662230f6.png)

**Comment by icraggs** [comment]
There's a fix for this in 1.3.12. It should work for you.
