### ISSUE TITLE
you forget to merge develop branch into master

### ISSUE THREAD

**Issue by jumoog** [eclipse/paho.mqtt.c#1307]
the tag v1.3.12 has 0 commits https://github.com/eclipse/paho.mqtt.c/compare/v1.3.12...master

**Comment by jumoog** [comment]
ping @icraggs

**Comment by icraggs** [comment]
I think the changes are merged into the master branch - they're showing in my log. This is the tag in the master branch: https://github.com/eclipse/paho.mqtt.c/commit/4157a27d39f1dd5b95750ecb6acd1481432785d8

What I did forget to to is to commit the changes to the version.patch file so it's still showing as 11 in the tag. I fixed that in a later commit. There's always something.
