### ISSUE TITLE
Incorrect version in 1.3.12 release

### ISSUE THREAD

**Issue by Keith-S-Thompson** [eclipse/paho.mqtt.c#1308]
**Describe the bug**
The v1.3.12 release has an outdated `version.patch` file.
The `version.major`, `version.minor`, and `version.patch` files contain `1`, `3`, and `11`, respectively.

Commit `f7799da` fixes the version number, but the tag `v1.3.12` points to the previous commit, `4157a27`.

Suggested fix: Move the tag `v1.3.12` to commit `f7799da` and regenerate the release files (`.tar.gz`, `.zip`, and whatever else).

**Comment by icraggs** [comment]
Yes I forgot to commit the version number changes. Doh. I have been criticized in the past for moving the tag like this, but I asked Frank (the maintainer of the C++ and Rust clients which rely on this project) and he's for it. So I will.

**Comment by icraggs** [comment]
So I fixed that now. Hopefully should all be correct!
