### ISSUE TITLE
glue layer function naming causes library clashes

### ISSUE THREAD

**Issue by fhuberts** [eclipse/paho.mqtt.c#1313]
**Describe the bug**
All functions like Thread_start must be prefixed with ‘paho_’.

We are trying to use paho and libiec61850 together in an application, and unfortunately they both  have the same names  to start a thread.

It is good practice to prefix the names in your library by its name to avoid these clashes.

I’ve filed the same bug report with libiec61850.

**To Reproduce**
Link an application with paho and libiec61850, implement code that will start a thread from both libraries, run it and see one of the paths use the wrong function to start a thread.

**Expected behavior**
Both libraries use their own functions.

**Screenshots**
N.A.

**Log files**
N.A.

** Environment (please complete the following information):**
 - OS: Linux
 - Version: Debian 12, Fedora 37, ...

**Additional context**

**Comment by icraggs** [comment]
Ah yes, those functions should not really be public, I used them in some tests rather than copy them. Changing the names would be wise anyway.

**Comment by icraggs** [comment]
Would making the functions static/non-visible also work? (I intend to change the names anyway).

**Comment by applea9** [comment]
I met the same issue too. Currenty the solution is to make the functions not visible.

**Comment by fhuberts** [comment]
tnx!
