### ISSUE TITLE
Attempting to cross compile win32 on ubuntu results in compiler errors implying it cannot find or did not include file winsock2.h 

### ISSUE THREAD

**Issue by johnmci** [eclipse/paho.mqtt.c#1320]
**Describe the bug**
Followed instructions to install a cross compile environment on Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-137-generic x86_64)
per README.md 

**Expected behavior**
(a) creation of cmake files using the tool chain file
(b) cmake build would successfully compile all files for the indicated cross compile target.

** results ** 
It appears the cross compiler is unable to find the needed include files, or _WIN32 not defined?  winsock2.h

cmake -DPAHO_WITH_SSL=FALSE -DPAHO_BUILD_SAMPLES=FALSE -DPAHO_BUILD_DOCUMENTATION=FALSE -DCMAKE_TOOLCHAIN_FILE=~/source/paho.mqtt.c/cmake/toolchain.win32.cmake  ~/source/paho.mqtt.c

-- CMake version: 3.16.3
-- CMake system name: Windows
-- Timestamp is 2023-01-24T17:42:43Z
-- Configuring done
-- Generating done
-- Build files have been written to: /home/johnmci/source

cmake --build .
[  1%] Building C object src/CMakeFiles/common_obj.dir/Socket.c.obj
/home/johnmci/source/paho.mqtt.c/src/Socket.c: In function ‘cmpfds’:
/home/johnmci/source/paho.mqtt.c/src/Socket.c:248:38: error: dereferencing pointer to incomplete type ‘struct pollfd’
  248 |    SOCKET key1 = ((struct pollfd*)p1)->fd;
      |                                      ^~
 *looks like winsock2.h not included ?

 locate winsock2.h

/usr/i686-w64-mingw32/include/winsock2.h
/usr/share/mingw-w64/include/winsock2.h
/usr/x86_64-w64-mingw32/include/winsock2.h

ls -l /usr/i686-w64-mingw32/include/winsock2.h
lrwxrwxrwx 1 root root 40 Nov 15  2019 /usr/i686-w64-mingw32/include/winsock2.h -> ../../share/mingw-w64/include/winsock2.h
ls -l /usr/share/mingw-w64/include/winsock2.h
-rw-r--r-- 1 root root 50326 Nov 15  2019 /usr/share/mingw-w64/include/winsock2.h
ls -l /usr/x86_64-w64-mingw32/include/winsock2.h
lrwxrwxrwx 1 root root 40 Nov 15  2019 /usr/x86_64-w64-mingw32/include/winsock2.h -> ../../share/mingw-w64/include/winsock2.h

**Comment by icraggs** [comment]
winsock2.h is a Windows header file so it depends what version of Windows your environment is supporting.

You could try the USE_SELECT compile option which will use the Select OS call instead of Poll and see if that makes any difference. The MS docs https://learn.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsapoll say that poll was introduced in Windows 8.1/Vista

**Comment by icraggs** [comment]
I'm closing this in the absence of further information.
