### ISSUE TITLE
Paho 1.3.9 Cannot run wss with MQTTClient_create return value -14

### ISSUE THREAD

**Issue by ArNiu2** [eclipse/paho.mqtt.c#1323]
Hi,

We want to use 1.3.9 to connect host url wss://[ServerIP]:443 on our Embedded System device.
When running the code to this section below, we got the return value -14(MQTTCLIENT_BAD_PROTOCOL) from MQTTClient_create() and then the program crashed.
The last print log is the previous line of the MQTTClient_setCallbacks().

    MQTTClient client;
    MQTTClient_connectOptions conn_opts = MQTTClient_connectOptions_initializer;
    MQTTClient_SSLOptions ssl_opts=MQTTClient_SSLOptions_initializer;//
    ssl_opts.trustStore = "/tmp/node-cert.pem";
    ssl_opts.sslVersion=MQTT_SSL_VERSION_DEFAULT;//
    int rc;
    int ch;
    const char *TOPIC=SerialNum;
    const char *address;
	
    address = "wss://[ServerIP]:443";    

    const char *client_id= SerialNum;
    char *chs = SerialNum;
    char **topic=&chs;
    disconnectflag = 1;
	ModTcpIPA->MQTTSubscribing = 0;
    int rev = MQTTClient_create(&client, address, client_id, MQTTCLIENT_PERSISTENCE_NONE, NULL);
    cout<<"create return:"<<rev<<endl;
	conn_opts.keepAliveInterval = 30;
    conn_opts.cleansession = 0;
	if (ModTcpIPA->ThirdPartyMode == 1) {
		conn_opts.username = THIRDPARTYUSERNAME;
		conn_opts.password = THIRDPARTYPASSWORD;
	}
	else {
		conn_opts.username = DELTAUSERNAME;
		conn_opts.password = DELTAPASSWORD;
	}
    conn_opts.ssl=&ssl_opts;//
    conn_opts.MQTTVersion = MQTTVERSION_3_1;

    while(!ModTcpIPA->CloseMQTTThread){
        if(disconnectflag == 1){
            **cout<<"Last Print"<<endl;**
            rev = MQTTClient_setCallbacks(client, NULL, connlost, msgarrvd, delivered);
            cout<<"callback return:"<<rev<<endl;
            disconnectflag = 0;
        }
        if ((rc = MQTTClient_connect(client, &conn_opts)) != MQTTCLIENT_SUCCESS)
        {
            printf("Failed to connect, return code %d\n", rc);
        }else{
            printf("Subscribing to topic %s\nfor client %s using QoS%d\n\n"
               "Press Q<Enter> to quit\n\n", TOPIC, client_id, QOS);
            MQTTClient_subscribe(client, TOPIC, QOS);
		    while(disconnectflag == 0){
                if(strlen(MQTTBuff)!= 0){
                    ParseMQTTMsg(&client);
					//ParseMQTTGridSetting(&client);
                }
                sleep(1);
            }
			ModTcpIPA->MQTTSubscribing = 0;
            MQTTClient_unsubscribe(client, TOPIC);
            MQTTClient_disconnect(client, 10000);
        }
        sleep(30);
    }
    MQTTClient_destroy(&client);
    }

This section is work when the address is ws://[ServerIP]:8080 before.

We have tried to change the CmakeList.txt by set up this:
SET(PAHO_WITH_SSL TRUE CACHE BOOL "Flag that defines whether to build ssl-enabled binaries too. ")

Also, the Makefile of our device program is below:
_CFLAGS += -L$(LIBDIR) -lpaho-mqtt3a
CFLAGS += -L$(LIBDIR) -lpaho-mqtt3as
CFLAGS += -L$(LIBDIR) -lpaho-mqtt3c
CFLAGS += -L$(LIBDIR) -lpaho-mqtt3cs_

And the mqtt file in our device contains all four files above.
(We have searched the return value -14 and known that it needs mqtt3as/mqtt3cs instead of mqtt3a/mqtt3c when using the wss).

We have tried hard to use wss to connect the server, but the program still crashed.

The Linux version of our device:

User@am335x-evm:~  uname -a
Linux am335x-evm 4.1.13-g8dc6617 #2 PREEMPT Tue Dec 13 10:33:06 CST 2016 armv7l GNU/Linux
User@am335x-evm:~  cat /proc/version 
Linux version 4.1.13-g8dc6617 (User@ComputerName) (gcc version 4.9.3 20150413 (prerelease) (Linaro GCC 4.9-2015.05) ) #2 PREEMPT Tue Dec 13 10:33:06 CST 2016

If any solution for this situation?
(If need more information for our system or code, please let me know)

Thanks a lot.

**Comment by fpagliughi** [comment]
The `wss://` protocol is a secure one, so requires OpenSSL. So you are required to set `PAHO_WITH_SSL=TRUE`, as you are doing.

But then, the Paho build creates up to four different libraries with a different features. You need to select the **one** library that you need and just link to that one.

Since you seem to be using the synchronous library - `MQTTClient_connect()` rather than `MQTTAsyncClient_connect()`, and you need security, you should link to:
```
paho-mqtt3cs
```
...and **not** any of the other ones. So you should only have the one line in your Makefile:
```
CFLAGS += -L$(LIBDIR) -lpaho-mqtt3cs
```

Get rid of those other three lines. I assume your linker is resolving functions to the wrong (insecure) version of the library which will give you that error.

**Comment by ArNiu2** [comment]
Thanks for your reply.

It works as you said!

**Comment by fpagliughi** [comment]
Great. I will close the issue.
