### ISSUE TITLE
MQTTClient does not send PINGREQ

### ISSUE THREAD

**Issue by woodz-** [eclipse/paho.mqtt.c#1330]
Is there a reason why MQTTClient of the synchronous library does not send ping requests inbetween regular data packages?

Other libs like javascript or python do.

The client gets sporadically disconnected through the broker because of connection timeouts.

Version is 3.1.12
QOS: 0
keep alive interval: 20 sec.
OS: ubuntu linux on docker
Docker version: 20.10.5+dfsg1, build 55c4c88
mqtt connection is on localhost inside docker

There are some parallel issues which might address similar problems but marked as resolved

- [1284](https://github.com/eclipse/paho.mqtt.c/issues/1284)
- [1277](https://github.com/eclipse/paho.mqtt.c/issues/1277)

**Comment by icraggs** [comment]
Those issues were fixed in 1.3.12.

It might depend what the scenario is. The ping isn't needed if other packets are being sent within the keepalive period. I see you are using QoS 0 so then it depends whether the packets are being sent in both directions, or just in one from client to server.  A client library trace at the protocol level might illustrate your scenario.

**Comment by woodz-** [comment]
Your answer I appreciate, raises more questions in my head.
The scenario is

    paho-c client publish
             |
           broker
             |
    paho js client subscribe 

The js-client sends periodic ping PINGREQ packets. The interval is less than configured keep alive interval (20 sec.)
The c-client does not.

Is that what you are saying?
The c client is sending regular packets to the broker and thus does not need to send PINGREQ packets. The js-client on the other hand is listening only (subscribe) and therefore needs to send periodic PINGREQ.

What do you exactly mean by

> A client library trace at the protocol level

?

I have analyzed the mosquitto broker logs. On this level I can see the js client does its job well. It sends periodic PINGREQ.

The c client also does its job well, if you can confirm my conclusion above. It sends regular data packages by an interval less than keep alive interval. The range is between 5 - 15 sec.

Or do you mean wireshaking the c-client connection? What news could it bring in?

The fact is, the c-client gets sporadically disconnected and I am on the scout why that is.

**Comment by icraggs** [comment]
The README has instructions on how to take a trace for this library. The protocol level will show the MQTT packets being sent and received.

The Mosquitto log should have some messages related to the disconnection.

I tried an experiment with the paho_cs_pub sample, sending QoS 0 messages on a regular basis (see below). The PING messages were still sent, because there are no messages being sent back from the broker to client, so the client app needs to know if the broker is still available. I would expect the PINGs to be sent in your case as well. 

```
./build.paho/src/samples/paho_cs_pub x --trace protocol -k 5
Trace : 3, =========================================================
Trace : 3,                    Trace Output
Trace : 3, Product name: Eclipse Paho Synchronous MQTT C Client Library
Trace : 3, Version: 1.3.12
Trace : 3, Build level: 2023-01-11T15:34:21Z
Trace : 3, OpenSSL version: OpenSSL 1.1.1s  1 Nov 2022
Trace : 3, OpenSSL flags: compiler: clang -fPIC -arch x86_64 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -D_REENTRANT -DNDEBUG
Trace : 3, OpenSSL build timestamp: built on: Tue Nov  1 12:36:10 2022 UTC
Trace : 3, OpenSSL platform: platform: darwin64-x86_64-cc
Trace : 3, OpenSSL directory: OPENSSLDIR: "/usr/local/etc/openssl@1.1"
Trace : 3, =========================================================
Trace : 4, 19700101 120000.000 5 paho-cs-pub -> CONNECT version 4 clean: 1 (0)
Trace : 4, 19700101 120000.000 5 paho-cs-pub <- CONNACK rc: 0
Trace : 4, 19700101 120000.000 5 paho-cs-pub -> PINGREQ (0)
Trace : 4, 19700101 120000.000 5 paho-cs-pub <- PINGRESP
sdsa
Trace : 4, 19700101 120000.000 5 paho-cs-pub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(5): sdsa

Trace : 4, 19700101 120000.000 5 paho-cs-pub -> PINGREQ (0)
Trace : 4, 19700101 120000.000 5 paho-cs-pub <- PINGRESP
adTrace : 4, 19700101 120000.000 5 paho-cs-pub -> PINGREQ (0)
Trace : 4, 19700101 120000.000 5 paho-cs-pub <- PINGRESP
asd
Trace : 4, 19700101 120000.000 5 paho-cs-pub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(6): adasd

Trace : 4, 19700101 120000.000 5 paho-cs-pub -> PINGREQ (0)
Trace : 4, 19700101 120000.000 5 paho-cs-pub <- PINGRESP
adasda
Trace : 4, 19700101 120000.000 5 paho-cs-pub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(7): adasda

adasda
Trace : 4, 19700101 120000.000 5 paho-cs-pub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(7): adasda

adsadsa
Trace : 4, 19700101 120000.000 5 paho-cs-pub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(8): adsadsa

adsadas
Trace : 4, 19700101 120000.000 5 paho-cs-pub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(8): adsadas

asdasda
Trace : 4, 19700101 120000.000 5 paho-cs-pub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(8): asdasda

Trace : 4, 19700101 120000.000 5 paho-cs-pub -> PINGREQ (0)
Trace : 4, 19700101 120000.000 5 paho-cs-pub <- PINGRESP
asdsadas
Trace : 4, 20230303 180809.288 5 paho-cs-pub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(9): asdsadas

adsada
Trace : 4, 20230303 180809.288 5 paho-cs-pub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(7): adsada

asdsadsa
Trace : 4, 20230303 180809.288 5 paho-cs-pub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(9): asdsadsa

asdsada
Trace : 4, 20230303 180809.288 5 paho-cs-pub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(8): asdsada

Trace : 4, 20230303 180809.288 5 paho-cs-pub -> PINGREQ (0)
Trace : 4, 20230303 180809.288 5 paho-cs-pub <- PINGRESP
^CTrace : 4, 20230303 180809.288 5 paho-cs-pub -> DISCONNECT (0)

```

**Comment by woodz-** [comment]
My trace is as follows

    =========================================================
                       Trace Output
    Product name: Eclipse Paho Synchronous MQTT C Client Library
    Version: 1.3.12
    Build level: 2023-01-05T14:54:51Z
    /proc/version: Linux version 5.15.76-v8+ (dom@buildbot) (aarch64-linux-gnu-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1597 SMP PREEMPT Fri Nov 4 12:16:41 GMT 2022
    =========================================================
    20230307 225658.373 6 pub_client -> CONNECT version 4 clean: 1 (0)
    20230307 225658.374 6 pub_client <- CONNACK rc: 0
    20230307 225701.794 6 pub_client -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(117): {"pub_client": {"tem"
    20230307 225706.794 6 pub_client -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(117): {"pub_client": {"tem"
    20230307 225711.794 6 pub_client -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(117): {"pub_client": {"tem"
    20230307 225716.794 6 pub_client -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(117): {"pub_client": {"tem"
    20230307 225721.794 6 pub_client -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(117): {"pub_client": {"tem"
    20230307 225726.794 6 pub_client -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(117): {"pub_client": {"tem"
    20230307 225731.794 6 pub_client -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(117): {"pub_client": {"tem"
    20230307 225736.794 6 pub_client -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(117): {"pub_client": {"tem"
    20230307 225741.794 6 pub_client -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(117): {"pub_client": {"tem"
    20230307 225746.794 6 pub_client -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(117): {"pub_client": {"tem"
    20230307 225751.794 6 pub_client -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(117): {"pub_client": {"tem"

and it confirms what I see in the mosquitto broker's log: **no PINGREQ**s.

Messages in traces are somehow truncated, no idea why. But data transmission is complete on all my subscribing clients.

Could it be the protocol version? I am not specifically mention mqtt5 options for init and connect functions. So for my understanding it then will default to protocol version 3.1.

Any ideas on how to proceed with this?

**Comment by icraggs** [comment]
The paho_cs_pub sample calls 

    rc = MQTTClient_setCallbacks(client, client, connectionLost, messageArrived, NULL);

which starts a background thread to handle such things as sending pings. You'll need to do this or call MQTTClient_yield at intervals, if you aren't already.

**Comment by woodz-** [comment]
OK,

I started from the sample `MQTTClient_publish.c` and didn't recognize that it is only for one shot purposes. A hint in the form of a comment on top of the file to this restriction might be helpful...

I will give your suggestion a try and report later.

**Comment by icraggs** [comment]
I think this is addressed.

**Comment by woodz-** [comment]
Sorry, addressed to what?

I have additional questions.
Your suggestion to use `MQTTClient_setCallbacks` will make the program a synchronous but multi threaded application.
Isn't there a possibility to keep the program single threaded and still send PINGREQs?

**Comment by icraggs** [comment]
As in there hadn't been any activity for a while and I think I answered your question.

You can keep the program single threaded by making calls to the API on a regular basis - at least as often as the PING is needed. The MQTTClient_yield function is there for that purpose if you don't need to publish anything at that point.

You can also set the keepalive to a longer interval as you are publishing on a regular basis, or turn keepalive off entirely by setting it to 0.
