### ISSUE TITLE
Problems with multithreading

### ISSUE THREAD

**Issue by qinrhx** [eclipse/paho.mqtt.c#1334]
Hello, is this library multi-thread safe? During the test, I found that multi-threaded subscription and unsubscription will trigger the mqtt connection to be disconnected, but single-threaded use will not. The test code is as follows:

`
MQTTClient m_c;

void on_disconnect(void* context, char* cause)
{
	printf("MQTT disconnected:%s\n", NULL == cause ? "" : cause);

	exit(-1);
}

int on_message(void* context, char* topicName, int topicLen, MQTTClient_message* message)
{
	const std::string topic = topicLen > 0 ? std::string(topicName, topicLen) : topicName;
	printf("onMessage topic:%s\n", topic.c_str());

	MQTTClient_freeMessage(&message);
	MQTTClient_free(topicName);
	return 1;
}

void* thread_test(void* ctx) {
	const char* topic = (const char*)ctx;
	while (true)
	{
		printf("subcribe topic:%s\n", topic);

		MQTTSubscribe_options opts = MQTTSubscribe_options_initializer;
		MQTTProperties properties = MQTTProperties_initializer;
		MQTTResponse rc = MQTTClient_subscribe5(m_c, topic, 0, &opts, &properties);
		MQTTProperties_free(&properties);
		if (MQTTREASONCODE_SUCCESS != rc.reasonCode) {
			MQTTResponse_free(rc);
			printf("MQTT v5 subscribe fail: %s, %d\n", topic, rc.reasonCode);
			return false;
		}
		else {
			printf("MQTT v5 subscribe ok: %s\n", topic);
		}
		MQTTResponse_free(rc);

		printf("unsubcribe topic:%s\n", topic);
		MQTTProperties properties2 = MQTTProperties_initializer;
		MQTTResponse rc2 = MQTTClient_unsubscribe5(m_c, topic, &properties2);
		MQTTProperties_free(&properties2);
		if (MQTTREASONCODE_SUCCESS != rc2.reasonCode) {
			MQTTResponse_free(rc2);
			printf("MQTT v5 unsubscribe fail: %s, %d\n", topic, rc2.reasonCode);
			return false;
		}
		else {
			printf("MQTT v5 subscribe ok: %s\n", topic);
		}
		MQTTResponse_free(rc2);
	}
	return NULL;
}

int main(int argc, char* argv[])
{
	MQTTClient_init_options initOpts = MQTTClient_init_options_initializer;
	MQTTClient_global_init(&initOpts);

	std::string addr = "tcp://10.80.80.189:2883";

	MQTTClient_createOptions createOpts = MQTTClient_createOptions_initializer;
	createOpts.MQTTVersion = MQTTVERSION_5;

	int res = MQTTClient_createWithOptions(&m_c, addr.c_str(), "", MQTTCLIENT_PERSISTENCE_NONE, NULL, &createOpts);
	if (MQTTCLIENT_SUCCESS != res) {
		printf("create mqtt client fail: %d\n", res);
		return -1;
	}

	res = MQTTClient_setCallbacks(m_c, NULL, on_disconnect, on_message, NULL);
	if (MQTTCLIENT_SUCCESS != res)
	{
		printf("MQTT set callback fail: %d\n", res);
		return false;
	}
	
	MQTTClient_connectOptions connOpts = MQTTClient_connectOptions_initializer5;
	MQTTResponse rc = MQTTClient_connect5(m_c, &connOpts, NULL, NULL);
	if (MQTTREASONCODE_SUCCESS != rc.reasonCode) {
		MQTTResponse_free(rc);
		printf("MQTT v5 connect to broker fail: %d\n", rc.reasonCode);
		return -1;
	}
	MQTTResponse_free(rc);

	pthread_t id;
	pthread_create(&id, NULL, thread_test, (void*)"test1");
	pthread_create(&id, NULL, thread_test, (void*)"test2");
	/*pthread_create(&id, NULL, thread_test, (void*)&cli);
	pthread_create(&id, NULL, thread_test, (void*)&cli);
	pthread_create(&id, NULL, thread_test, (void*)&cli);*/

	sleep(100000);

	return 0;
}
`

And the test result print as bellow:

![image](https://user-images.githubusercontent.com/37607426/223009975-b990b5a0-7913-44c4-9a11-295ba32813dc.png)

**Comment by icraggs** [comment]
It's intended to cope with multi-threading although the MQTTAsync API is more capable in that regard. The MQTTClient API is the simple API to get started.

A library trace as described in the readme, first at the protocol level, might give more idea of what's happening.

Also, what library version and OS?

**Comment by qinrhx** [comment]
Thanks for the reply.
The library version I am using is 1.3.9.
OS version is linux 3.2.0 armv7l

The trace output is as follows
[mqtt.log](https://github.com/eclipse/paho.mqtt.c/files/10940050/mqtt.log)

**Comment by qinrhx** [comment]
> It's intended to cope with multi-threading although the MQTTAsync API is more capable in that regard. The MQTTClient API is the simple API to get started.
> 
> A library trace as described in the readme, first at the protocol level, might give more idea of what's happening.
> 
> Also, what library version and OS?
[mqtt.log](https://github.com/eclipse/paho.mqtt.c/files/10940080/mqtt.log)

Thanks for the reply.
The library version I am using is 1.3.9.
OS version is linux 3.2.0 armv7l

The trace output is as follows log file:

**Comment by qinrhx** [comment]
> It's intended to cope with multi-threading although the MQTTAsync API is more capable in that regard. The MQTTClient API is the simple API to get started.
> 
> A library trace as described in the readme, first at the protocol level, might give more idea of what's happening.
> 
> Also, what library version and OS?

Thanks for the reply.
The library version I am using is 1.3.9.
OS version is linux 3.2.0 armv7l

The trace output in the log file bellow:

[mqtt.log](https://github.com/eclipse/paho.mqtt.c/files/10940092/mqtt.log)

**Comment by icraggs** [comment]
I've made a change which allows your example to work. I would say however that for complex application multi-threading the MQTTAsync API is better.
