### ISSUE TITLE
MQTTAsync_send() recevied success but connectionLost and Server didn't receive payload.

### ISSUE THREAD

**Issue by ArNiu2** [eclipse/paho.mqtt.c#1335]
Hi,

We tried to connect server and publish test json packet to server on our Embedded Device. (Ver: Paho 1.3.9)
We successfully connected to server and send the test packet.
After we sent the packet, we got connectLost from callback log.

The code is below:
```
    MQTTAsync client;
    MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;
    MQTTAsync_SSLOptions sslOpts = MQTTAsync_SSLOptions_initializer;

    int rc = -1;
    int ch;
    const char *TOPIC=SN;
	const char *address;
	address = "ssl://[ServerIP]:8085";
    char urll[]={"ssl://[ServerIP]:8085"};
    char* url[]={urll};
    
    sslOpts.trustStore = "/ca.crt";//CA_CERTS_FILE;
    sslOpts.keyStore = "/client.crt";//CLIENT_CERT_FILE;
    sslOpts.privateKey = "/client.key"; //CLIENT_PRIVATE_KEY_FILE;
    sslOpts.enableServerCertAuth=0;

    const char *client_id=SN;
    char *chs = SN;
    char **topic=&chs;
    disconnectflag = 1;
    ModTcpIPA->MQTTSubscribing = 0;
    rc = MQTTAsync_create(&client, address, client_id, MQTTCLIENT_PERSISTENCE_NONE, NULL);
    cout<<"MQTT Create rc = "<<rc<<endl;
    conn_opts.keepAliveInterval = 15;
    conn_opts.cleansession = 0;
    conn_opts.ssl = &sslOpts;

    conn_opts.serverURIs = url;
    printf("serverURL:%s",url[0]);
    conn_opts.serverURIcount = 1;

    conn_opts.context = &client;
    conn_opts.onSuccess = onConnect;
    conn_opts.onFailure = onConFailure;
    conn_opts.automaticReconnect = 1;
    conn_opts.minRetryInterval = 2; //seconds
    conn_opts.maxRetryInterval = 15;

    while(!ModTcpIPA->CloseMQTTThread){
        if(disconnectflag == 1){
            MQTTAsync_setCallbacks(client, NULL, connlost, msgarrvd, delivered); //?
            disconnectflag = 0;
        }
        MQTTAsync_setConnected(client, client, onConnected);
        if ((rc = MQTTAsync_connect(client, &conn_opts)) != MQTTASYNC_SUCCESS)
        {
                printf("Failed to connect, return code %d\n", rc);
        }else{
            printf("Subscribing to topic %s\nfor client %s using QoS%d\n\n"
               "Press Q<Enter> to quit\n\n", TOPIC, client_id, QOS);
            char testTopic[] = "devicetopic";
            char returnPayload[128];
            string testjson = "{\"ts\":1678073215,\"values\":{\"test\": \"publish\"}}";
            StrToChar(returnPayload,testjson);
			ModTcpIPA->MQTTSubscribing = 1;
            while(disconnectflag == 0){
                if(MQTTConnect == 1){
                    publish(client, testTopic, sizeof(testTopic),returnPayload);
                    MQTTConnect = 2;
                }
                if(strlen(MQTTBuff)!= 0){
                    ParseMQTTMsg(&client);
                }
                sleep(1);
            }
			ModTcpIPA->MQTTSubscribing = 0;
            MQTTAsync_disconnect(client, NULL); //timeout = 0sec
        }
        sleep(30);
    }
    MQTTAsync_destroy(&client);
    return rc;
```

publish function is:

```
int InSock::publish(MQTTAsync c, char* topic, int payloadLen, char* payload) {

    int rc = MQTTASYNC_SUCCESS;
    MQTTAsync_message pubmsg = MQTTAsync_message_initializer;
    pubmsg.payload = payload;
    pubmsg.payloadlen = payloadLen;
    pubmsg.qos = 1;
    pubmsg.retained = 0;
    MQTTAsync_responseOptions opts = MQTTAsync_responseOptions_initializer;
    cout<<"topic:"<<topic<<endl;
    cout<<"payloadlen: "<<pubmsg.payloadlen<<" payload:"<<pubmsg.payload<<" p:"<<payload<<endl;
    printf("payload: %s\n",pubmsg.payload);
    rc = MQTTAsync_send(c, topic, pubmsg.payloadlen, pubmsg.payload,
                pubmsg.qos, pubmsg.retained, &opts);
    cout<<"send return: "<<rc<<endl;
    if (rc != MQTTASYNC_SUCCESS){
        cout<<"[publish] not success"<<endl;
    }
    else{
        cout<<"[publish] success"<<endl;
    }
    cout<<"[publish]~~~~"<<endl;
    
    return rc;
}
```

All the rc we got is 0, which means success.
After I saw the log "[publish]~~~~" is printed, the "connection lost" is behind this.

Also, I couldn't find the json on the server, but I can find the connecting log when "OnConnect" callback is triggered.

And we would get "connection lost" when reconnect to server.
Log:
```
[20230306-07:29:32.776 DEBUG ][onConnect:820]: Connect OK!
onConnected~~~
[20230306-07:29:32.786 DEBUG ][connlost:812]: 
Connection lost

[20230306-07:29:32.786 DEBUG ][connlost:813]:      cause: (null)

onConnected~~~
[20230306-07:29:33.301 DEBUG ][connlost:812]: 
Connection lost

[20230306-07:29:33.301 DEBUG ][connlost:813]:      cause: (null)
```

But if I comment the "publish" function for not to send(), our device could connect to server stably and not trigger connection lost.

The Linux version of our device:

User@am335x-evm:~ uname -a
Linux am335x-evm 4.1.13-g8dc6617 https://github.com/eclipse/paho.mqtt.c/issues/2 PREEMPT Tue Dec 13 10:33:06 CST 2016 armv7l GNU/Linux
User@am335x-evm:~ cat /proc/version
Linux version 4.1.13-g8dc6617 (User@ComputerName) (gcc version 4.9.3 20150413 (prerelease) (Linaro GCC 4.9-2015.05) ) https://github.com/eclipse/paho.mqtt.c/issues/2 PREEMPT Tue Dec 13 10:33:06 CST 2016

I wonder how can I fix this situation?
I expect our device can successfully connect and send packet to server, and the server is also got the packet.
Also, our device need to stably connected to server.
(If need more information for our system or code, please let me know)

Thanks a lot.

**Comment by icraggs** [comment]
You need to wait until you get the onConnect callback before you publish to get it to work reliably. All the async functions work in the background, the rc from the initial call just says that the request has been successfully submitted. 

I suggest you try out and look at the sample paho_c_pub.

**Comment by ArNiu2** [comment]
Hi, 

Thanks for your kindly reply.
I have already set the onConnect callback and set flag like this code below before your suggestion:
```
static void onConnect(void* context, MQTTAsync_successData* response)
{
    DEBUG_NL("Connect OK!");
    MQTTConnect++;
}
```
And the publish function would be called when the varible "MQTTConnect" is not zero which means the program waits the connection is established. 

I roughly look at the sample paho_c_pub and find out that it need to wait 10sec.
I tried to add sleep() before publish() to fix my problem.(I tried 30sec, 1min. But it is still not fixed.)

The problem situation which still is I got the MQTTAsync_send() return value zero and then it is disconnected (the server still not receive the packet.)
P.S: I didn't wait the connection established in the beginning, and the MQTTAsync_send() would return -3 not 0.

I am sure the connection is success by checking the server UI like this form:
```
2023-03-07 15:38:29	lastConnectTime	1678174709265
```

Is that any suggestion for this result?

Thanks a lot !

**Comment by icraggs** [comment]
paho_c_pub doesn't need to wait 10 seconds - if you mean the "mysleep(100)" call, that is waiting for 100 milliseconds, but only within a loop when waiting for background work to complete.

Are there any error messages on the server? What server is it? Is there something in the message it doesn't like?

Taking a trace at the protocol level as described in the readme could shed more light.

You could also try using the paho_c_pub sample to send your message to see if that worked.

**Comment by ArNiu2** [comment]
Hi,
Thanks for your kindly reply.
I traced the protocol and tried to use sample code to send.
It finally works!

Thanks again!
