### ISSUE TITLE
MQTTClient_connect reconnect failed until my app restart

### ISSUE THREAD

**Issue by kexinmm** [eclipse/paho.mqtt.c#1338]
When my app platsvr disconnected with broker, I will retry every 2 minutes. But occasionally, it never connected successfully when disconnected, until I killall platsvr. When my app was restarted, it would connect successfully soon.

**Expected behavior**
 Expected: when the net is ok, it should connect successfully every time.

** Environment (please complete the following information):**
 - OS: Linux arm
 - Version 1.3.0

Should I try 1.3.2?

**Comment by kexinmm** [comment]
Additional informations:
1. I have uses SSL.

**Comment by fpagliughi** [comment]
Version 1.3.0 is pretty old at this point. (5 yrs?) The latest is v1.3.12. Definitely try a newer version to see if your issue was fixed in the last few years.

**Comment by icraggs** [comment]
Closing as no further info.
