### ISSUE TITLE
Why do we try SSLSocket_connect in MQTTAsync_connecting(MQTTAsyncs* m) function after SSLSocket_setSocketForSSL does not return MQTTASYNC_SUCCESS

### ISSUE THREAD

**Issue by bjaggi-sag** [eclipse/paho.mqtt.c#1340]
**Describe the bug**
In function **int MQTTAsync_connecting(MQTTAsyncs* m)** inside **MQTTAsyncUtils.c**, when the function does not return MQTTASYNC_SUCCESS why do we try connecting with **SSLSocket_connect** in the same function and simply exit the function with error.

**Comment by icraggs** [comment]
I'm not sure I follow the question. Which function does not return MQTTASYNC_SUCCESS? Which instance of calling SSLSocket_connect are you referring to?

Is there an actual problem you are trying to debug? If so, taking a protocol trace and including the other information asked for in the issue template would probably help.

**Comment by icraggs** [comment]
Closing as no further info.
