### ISSUE TITLE
Improper callback context and/or double callbacks

### ISSUE THREAD

**Issue by fpagliughi** [eclipse/paho.mqtt.c#1341]
The C++ and Rust clients use dynamic "Tokens" to track asynchronous operations. These are accessed via reference-counted smart pointers, but we can think of the behavior as something similar to using a heap-allocated struct as the `context` pointer that gets passes to the onSuccess/onFailure callback. The memory is then free'd in the callback.

So the assumption is that a callback will be called exactly once for each operation; either indicating success or failure.

The value of the _context_ pointer is different for each operation. It would be a disaster if the callback had the wrong context value (segfault), or if the callback were fired twice (double free).

Both of those problems seem to be happening. Consider a slightly modified _MQTTAsync_subscribe_ example which the connect options `context` is a malloc'ed struct.

```
/*******************************************************************************
 * Copyright (c) 2012, 2022 IBM Corp., Ian Craggs
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * and Eclipse Distribution License v1.0 which accompany this distribution. 
 *
 * The Eclipse Public License is available at 
 *   https://www.eclipse.org/legal/epl-2.0/
 * and the Eclipse Distribution License is available at 
 *   http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *    Ian Craggs - initial contribution
 *******************************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "MQTTAsync.h"

#if !defined(_WIN32)
#include <unistd.h>
#else
#include <windows.h>
#endif

#if defined(_WRS_KERNEL)
#include <OsWrapper.h>
#endif

// #define TRY_RECONNECT

#define ADDRESS 	"mqtt://localhost:1883"
#define CLIENTID	"ExampleClientSub"
#define TOPIC   	"MQTTExamples"
#define QOS 		1
#define TIMEOUT 	10000L

int disc_finished = 0;
int subscribed = 0;
int finished = 0;

void onConnect(void* context, MQTTAsync_successData* response);
void onConnectFailure(void* context, MQTTAsync_failureData* response);

typedef struct tagConnectToken {
	MQTTAsync client;
	int otherStuff;
} ConnectToken;

// We do this to make sure a new allocation gives us a different address than the last one
// (if you malloc right after a free, you often get the same block handed back to you)
ConnectToken* newConnectToken(void)
{
	ConnectToken* tok1 = malloc(sizeof(ConnectToken));
	ConnectToken* tok = malloc(sizeof(ConnectToken));
	free(tok1);
	return tok;
}

void pahoSleep(long ms)
{
	#if defined(_WIN32)
		Sleep(ms);
	#else
		usleep(ms * 1000L);
	#endif
}

void reconnect(MQTTAsync client)
{
	MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;
	int rc;

	ConnectToken* tok = newConnectToken();
	tok->client = client;
	tok->otherStuff = 42;

	conn_opts.keepAliveInterval = 20;
	conn_opts.cleansession = 1;
	conn_opts.onSuccess = onConnect;
	conn_opts.onFailure = onConnectFailure;
	conn_opts.context = tok;

	printf("Reconnecting w/ token 0x%p\n", tok);

	if ((rc = MQTTAsync_connect(client, &conn_opts)) != MQTTASYNC_SUCCESS)
	{
		printf("Failed to start connect, return code %d\n", rc);
		finished = 1;
	}
}

void connlost(void *context, char *cause)
{
	MQTTAsync client = (MQTTAsync)context;

	printf("\nConnection lost\n");
	if (cause)
		printf("	 cause: %s\n", cause);

	reconnect(client);
}


int msgarrvd(void *context, char *topicName, int topicLen, MQTTAsync_message *message)
{
	printf("Message arrived\n");
	printf("	 topic: %s\n", topicName);
	printf("   message: %.*s\n", message->payloadlen, (char*)message->payload);
	MQTTAsync_freeMessage(&message);
	MQTTAsync_free(topicName);
	return 1;
}

void onDisconnectFailure(void* context, MQTTAsync_failureData* response)
{
	printf("Disconnect failed, rc %d\n", response->code);
	disc_finished = 1;
}

void onDisconnect(void* context, MQTTAsync_successData* response)
{
	printf("Successful disconnection\n");
	disc_finished = 1;
}

void onSubscribe(void* context, MQTTAsync_successData* response)
{
	printf("Subscribe succeeded\n");
	subscribed = 1;
}

void onSubscribeFailure(void* context, MQTTAsync_failureData* response)
{
	printf("Subscribe failed, rc %d\n", response->code);
	finished = 1;
}


void onConnectFailure(void* context, MQTTAsync_failureData* response)
{
	printf("Connect failed w/ token 0x%p, rc %d\n", context, response->code);

	ConnectToken* tok = (ConnectToken*)context;
	MQTTAsync client = tok->client;
	free(tok);

	#if defined(TRY_RECONNECT)
		pahoSleep(1000);
		reconnect(client);
	#else
		finished = 1;
	#endif
}

void onConnect(void* context, MQTTAsync_successData* response)
{
	printf("Successful connection w/ token 0x%p\n", context);

	ConnectToken* tok = (ConnectToken*)context;
	MQTTAsync client = tok->client;
	free(tok);

	MQTTAsync_responseOptions opts = MQTTAsync_responseOptions_initializer;
	int rc;

	printf("Subscribing to topic %s\nfor client %s using QoS%d\n\n"
		   "Press Q<Enter> to quit\n\n", TOPIC, CLIENTID, QOS);
	opts.onSuccess = onSubscribe;
	opts.onFailure = onSubscribeFailure;
	opts.context = client;
	if ((rc = MQTTAsync_subscribe(client, TOPIC, QOS, &opts)) != MQTTASYNC_SUCCESS)
	{
		printf("Failed to start subscribe, return code %d\n", rc);
		finished = 1;
	}
}

int main(int argc, char* argv[])
{
	MQTTAsync client;
	MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;
	MQTTAsync_disconnectOptions disc_opts = MQTTAsync_disconnectOptions_initializer;
	int rc;
	int ch;

	if ((rc = MQTTAsync_create(&client, ADDRESS, CLIENTID, MQTTCLIENT_PERSISTENCE_NONE, NULL))
			!= MQTTASYNC_SUCCESS)
	{
		printf("Failed to create client, return code %d\n", rc);
		rc = EXIT_FAILURE;
		goto exit;
	}

	if ((rc = MQTTAsync_setCallbacks(client, client, connlost, msgarrvd, NULL)) != MQTTASYNC_SUCCESS)
	{
		printf("Failed to set callbacks, return code %d\n", rc);
		rc = EXIT_FAILURE;
		goto destroy_exit;
	}

	ConnectToken* tok = newConnectToken();
	tok->client = client;
	tok->otherStuff = 42;

	conn_opts.keepAliveInterval = 20;
	conn_opts.cleansession = 1;
	conn_opts.onSuccess = onConnect;
	conn_opts.onFailure = onConnectFailure;
	conn_opts.context = tok;

	printf("Attempting connect w/ token 0x%p\n", tok);

	if ((rc = MQTTAsync_connect(client, &conn_opts)) != MQTTASYNC_SUCCESS)
	{
		printf("Failed to start connect, return code %d\n", rc);
		rc = EXIT_FAILURE;
		goto destroy_exit;
	}

	while (!subscribed && !finished)
	{
		pahoSleep(100);
	}

	if (finished)
		goto exit;

	do 
	{
		ch = getchar();
	} while (ch!='Q' && ch != 'q');

	disc_opts.onSuccess = onDisconnect;
	disc_opts.onFailure = onDisconnectFailure;
	if ((rc = MQTTAsync_disconnect(client, &disc_opts)) != MQTTASYNC_SUCCESS)
	{
		printf("Failed to start disconnect, return code %d\n", rc);
		rc = EXIT_FAILURE;
		goto destroy_exit;
	}
	while (!disc_finished)
	{
		pahoSleep(100);
	}

destroy_exit:
	MQTTAsync_destroy(&client);
exit:
	return rc;
}
```

If this connects properly, and then the broker goes down causing us to lose the connection, we get this:

```
Connection lost
Reconnecting w/ token 0x0x7f5128000ce0
20230315 095628.641 Connect failed, more to try
20230315 095628.641 0 inflight messages deleted for client ExampleClientSub
20230315 095628.641 0 responses removed for client ExampleClientSub
20230315 095628.641 Calling connect failure for client ExampleClientSub
Connect failed w/ token 0x0x7f5128000ce0, rc -1                          <- 1st callback 
20230315 095628.641 Connecting to serverURI localhost:1883 with MQTT version 4
20230315 095628.641 New socket 3 for localhost:1883, port 1883
20230315 095628.641 Connect pending
20230315 095628.641 m->c->connect_state = 1
20230315 095628.641 Removed socket 3
20230315 095628.641 Removed socket 3
20230315 095628.641 Connect failed, more to try
20230315 095628.641 Could not find client corresponding to socket 3
20230315 095628.641 Connecting to serverURI localhost:1883 with MQTT version 3
20230315 095628.641 New socket 3 for localhost:1883, port 1883
20230315 095628.641 Connect pending
20230315 095628.641 m->c->connect_state = 1
20230315 095628.641 Removed socket 3
20230315 095628.841 Removed socket 3
20230315 095628.841 0 inflight messages deleted for client ExampleClientSub
20230315 095628.841 0 responses removed for client ExampleClientSub
20230315 095628.841 Calling connect failure for client ExampleClientSub
Connect failed w/ token 0x0x7f5128000ce0, rc -1                   <- 2nd callback
free(): double free detected in tcache 2
Aborted (core dumped)
```

The onFailure callback is fired twice for one call to `MQTTAsync_connect()`. The first one doesn't make sense to me. It appears that it's being fired before a connection is even attempted.

It then gets even weirder if you #define TRY_RECONNECT. In that case, then it seems that when a connection is re-established after a few failed attempts, the onSuccess is called with the context of the previous failed attempt! That segfaults.

**Comment by fpagliughi** [comment]
I've narrowed it down and seem to be seeing the problem when I call `MQTTAsync_connect()` from **inside** the "Connection Lost" callback.

So I get notified that the connection was lost, and from within that callback, I try to call  `MQTTAsync_connect()`.
It's not using auto reconnects or even a call to `MQTTAsync_reconnect()`

It looks like the connection lost callback is fired early in the process of unwinding the connection status (MQTTAsyncUtils.c:1614). By calling `MQTTAsync_connect()` at this point the client data structs (like context) updated and changing the proper behavior of the rest of the connection-lost processing.

The `MQTTAsync_addCommand` then fails:
https://github.com/eclipse/paho.mqtt.c/blob/f7799da95e347bbc930b201b52a1173ebbad45a7/src/MQTTAsyncUtils.c#L1636-L1637

...making `more_to_try` FALSE, and then the failure callback is fired _using the new context!_
https://github.com/eclipse/paho.mqtt.c/blob/f7799da95e347bbc930b201b52a1173ebbad45a7/src/MQTTAsyncUtils.c#L1656

This firing of the failure callback with the new token is incorrect.

Later, the requested connection attempt is made, and when completed, for success or failure, a callback is fired (properly) with the new context, but at this point my completion token has been free'd, and I get a segfault or double free error.

**Comment by fpagliughi** [comment]
I was looking for a work-around, but I can't use the library's `int MQTTAsync_reconnect(MQTTAsync handle);` since it doesn't take any options, and thus doesn't allow me to update to a new `context` pointer.

**Comment by icraggs** [comment]
I'm back! And I'm working through the issue. (The reconnect call was meant to be used with auto reconnect).

There are two cases:

1. in nextOrClose, !more_to_try, connectionLost is called before the success/failure callbacks. If the connect options are changed in the connectionLost callback, those are picked up by the code to decide whether the success/failure callbacks are to be called. Fix: move the call to connectionLost after the calls to success or failure.
2. in nextOrClose more_to_try, if the MQTT version is MQTTVERSION_DEFAULT. I was going to remove MQTTVERSION_DEFAULT in 1.4, as the 3.1.1 to 3.1 fallback isn't needed any more and is sometimes confusing. Anyway, here we always call the 3.1 fallback, even if the 3.1.1 connect initially succeeded, which can result in more than 1 instance of success/failure being called. Solution: if the 3.1.1 connect succeeds, don't try 3.1 at all - it's only needed if the broker doesn't support 3.1.1. And remove the fallback entirely in 1.4 of this library.

I'm just working through the best code for case 2. Case 1 is straightforward. Case 2 can also be avoided by setting the MQTT version connect option to 3.1.1.

**Comment by fpagliughi** [comment]
Welcome back!

This sounds good. As for MQTTVERSION_DEFAULT, I agree that it's pretty obsolete and am fine with it being removed in the next version. I will remove its use from the C++ and Rust clients in preparation for 1.4

**Comment by icraggs** [comment]
When I said remove MQTTVERSION_DEFAULT, I was thinking of not removing the constant, but making MQTTVERSION_DEFAULT equivalent to MQTTVERSION_3.1.1, to be clear. Or would it be better to remove MQTTVERSION_DEFAULT entirely?

**Comment by fpagliughi** [comment]
Oh, yeah. Changing the value would be less disruptive for backward compatibility. You're right.

**Comment by fpagliughi** [comment]
Any thoughts on a 1.3.13 release? I will be looking to do a Paho C++ release in August. It would be great to get this all out together.

**Comment by icraggs** [comment]
@fpagliughi I'm happy to put out a 1.3.13 release soon - there are enough fixes in already to be worthwhile. Have you been able to try out the fixes to this issue?

**Comment by fpagliughi** [comment]
Oh, apologies. I sent the last message just before leaving on holiday. I'm back and will re-confirm the fix(es). I think I tested this one when it was posted, but I will go through it again to be sure.

**Comment by fpagliughi** [comment]
OK. My test app crashes when I use it with v1.3.12, and it **doesn't** crash when I use the code in the develop branch.

So it seems fixed to me.

If you will move to a v1.3.13 release soon, I will immediately follow it with a bug-fix update to the Rust client to use the new version.

In the meantime, I'm also working on an update to the C++ lib. It's been +2yrs since that's had an update. It needs some love. I will get that out with the v1.3.13 release as well.
