### ISSUE TITLE
Paho 1.3.12 (> 1.3.9) do not compile with Android BoringSSL and security question to community

### ISSUE THREAD

**Issue by Pascal-Fremaux** [eclipse/paho.mqtt.c#1343]
**Describe the bug**

I know that Paho MQTT C do not support officially the BoringSSL API.

Compiling with SSL with BoringSSL on Android 12 in place of an OpenSSL 1.1.1 fails:

/obj/vendor/alliance/external/paho.mqtt.c/src/SSLSocket.o vendor/alliance/external/paho.mqtt.c/src/SSLSocket.c
vendor/alliance/external/paho.mqtt.c/src/SSLSocket.c:620:2: error: implicit declaration of function 'SSL_CTX_set_security_level' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        SSL_CTX_set_security_level(net->ctx, 1);
        ^
vendor/alliance/external/paho.mqtt.c/src/SSLSocket.c:620:2: note: did you mean 'SSL_CTX_set_verify_depth'?
external/boringssl/src/include/openssl/ssl.h:2407:21: note: 'SSL_CTX_set_verify_depth' declared here
OPENSSL_EXPORT void SSL_CTX_set_verify_depth(SSL_CTX *ctx, int depth);
                    ^
1 error generated.

(Of course the compiler alternative recommendation is wrong)

Code involved:
```
#if (OPENSSL_VERSION_NUMBER >= 0x10100000L)
	SSL_CTX_set_security_level(net->ctx, 1);
#endif
```

**To Reproduce**
Link to BoringSSL

**Expected behavior**
Paho C should take care to what is not compatible with BoringSSL used in Android releases.

**Screenshots**
N/A

**Log files**
N/A

** Environment (please complete the following information):**
 - OS: Android 12

**Additional context**

SSL_CTX_set_security_level is a "recent" addition to OpenSSL (since 1.1.0 )
defined in ssl.h (generated):
https://github.com/openssl/openssl/blob/03fa5127ded6ba0dc9f178090eca0dbe70769c0e/include/openssl/ssl.h.in
https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_security_level.html

but is not supported by the BoringSSL API (claiming support for a 1.1.1 but do not have the very same API)
https://github.com/google/boringssl/blob/master/include/openssl/ssl.h

I could not find an equivalent for the moment on BoringSSL (question: meaning?)
https://github.com/google/boringssl/blob/261ec612e21b81a4c16bbda615d0850556483b4f/PORTING.md

But I wonder if this is really necessary to call that in Paho even for OpenSSL.
As said in the OpenSSL 1.1.1 documentation above, and the code, level 1 is the default of the 1.1.1 branch, so this command would not be necessary (as set by OPENSSL_TLS_SECURITY_LEVEL at compile time)
https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/include/openssl/tls1.h

Note: OPENSSL_TLS_SECURITY_LEVEL was upgraded to level 2 by OTC vote end of 2021 in the master (but not yet in the released 3.0/3.1)
https://github.com/openssl/openssl/commit/b3a33dac8880b88038083b64d234506659921436

If you wanted to go for more security, the minimum today should be the level 2-4.
As defined in OpenSSL doc above, level 1 is obsoleted now (SSLv2 prohibited, very obsolete key length)

Today, in standard security, every SSL version is prohibited/deprecated, and for TLSv1.1, it is also no more recommended.
And key length like the ones below level 2 are also far obsolete (this is more complex for the key length, as many protocols types with different key lengths).
As of today, a minimum level of security should be the level 2 to 4: for SSL/TLS today, TLSv1.2 is a minimum and TLSv1.3 is the recommended choice (more secure, more performant, more simple than the v1.2). As of now, the MQTT server providers support at least TLSv1.2, and some have already upgraded to the TLSv1.3 (unfortunately, not all of them AFAIK).
Also for the hash algorithm, SHA1 is deprecated since 2015 (or 2017?) (only in level4).

So setting a level of 1 is useless, as already the default in 1.1.1, and 2 would be the very minimum as of today (as in teh OpenSSL new branch).
Level 4 would become the future new default, the only problem is some also key length is a bit high for the needs: it is the good choice for the TLS version (>=1.2), the good choice for the hash algo (no SHA1 => SHA256 or more)
Note that TLSv1.3 is the good choice for people when available as they have removed anything potentially dangerous, in addition to everything obsolete in all the algos (ciphering and auth).

So I have no idea for whom is the SSL_CTX_set_security_level() call included into Paho, and it is not compatible with BoringSSL.

Another question I try to dig into is if there is any equivalent API in BoringSSL: knowing Google and the choice for their fork, they might have a default security level higher than the level 1 equivalent (need to prove it).
https://github.com/google/boringssl/blob/master/include/openssl/tls1.h

**Comment by icraggs** [comment]
I've just removed that call from the develop branch. It was there because I was still using 1024 bit keys in the TLS testing. I've now updated those so the call isn't needed. This should be in the next release.
