### ISSUE TITLE
MQTTAsync cleansession works incorrectly

### ISSUE THREAD

**Issue by wolverin-a** [eclipse/paho.mqtt.c#1364]
I am sending snapshots from the camera via the mqtt server and I need the subscriber to be able to pick up all previously sent pictures. For this purpose, I set
`MQTTAsync_connectOptions.cleansession = 0`
for the subscriber, after which he receives messages from ALL topics to which he is not even subscribed

Subscriber and publisher have QOS = 1

To check, I tried mosquitto_sub and it doesn't have such a problem.

OS Debian 10.13
Mosquitto version 1.5.7
protocol 3.1.1
paho 1.3.12

maybe the problem is that I can't send binary data via paho?

**Comment by jumoog** [comment]
> after which he receives messages from ALL topics to which he is not even subscribed

You use a different ClientID for each Client? If `cleansession` is 0, it means that the broker will try to reuse the previous session when connecting. The ClientID is used for identification.

**Comment by wolverin-a** [comment]
I connect to the mqtt server, subscribe to the topic, save the snapshots, disconnect and stop application, then run my program again, which repeats the same thing with ANOTHER topic the same ClientID.

But how can a subscriber receive something that he is not subscribed to, even if the ClientID was the same a second ago???

**Comment by wolverin-a** [comment]
I even tried to connect after a few minutes after using the same ClientID and I get messages from unsuscribed topics again

**Comment by wolverin-a** [comment]
I think I understood - if you subscribe to a topic with cleansession = 0 and disconnect, then the next time you connect, the subscription will be considered already completed and messages will be **stored indefinitely** during the session **until unsuscribed**.

However, if you unsubscribe, the messages are **no longer saved**

**Comment by icraggs** [comment]
Yes, and this is the behaviour of the broker so will be the same whatever MQTT client you use.
