### ISSUE TITLE
Unable to download dependencies

### ISSUE THREAD

**Issue by ApuLimaye** [eclipse/paho.mqtt.c#1366]
**Describe the bug**
I am trying to install the paho.mqtt.c library on Armbian linux os but am unable to install the required dependencies as specified in the building cmake section Readme file.

**To Reproduce**
Take a library trace as outlined in the README, and/or have a program or describe the steps to reproduce the behavior:
1. Went to paho.mqtt.c git repository
2. https://github.com/eclipse/paho.mqtt.c. Downloaded the repository from this link
3. Then I tried running the commands one by one given in that section
4. What could be the problem, is my version incompatable or is this library outdated or am I making any mistake installing it.

**Expected behavior**
Ideally all the dependencies should be properly downloaded along with the build file. Then by using the cmake command I should be able to install the paho.mqtt.c library and add it to my C compiler path. But this is not happening as many of the dependencies aren't being properly installed.

**Screenshots**

![Screenshot (47)](https://github.com/eclipse/paho.mqtt.c/assets/91175715/7aa0e015-42f2-4f4f-9167-3da41d0d037a)
![Screenshot (48)](https://github.com/eclipse/paho.mqtt.c/assets/91175715/e8c050f5-5866-43a9-9849-c49ad5ea40d6)

**Log files**
Please try to attach log files rather than pasting the log contents. It makes the issues easier to read.

** Environment 
 - Armbian OS for orange Pi
 - Version - Debian GNU/Linux 10 (buster)

**Comment by icraggs** [comment]
Looks like graphviz might not be available for your OS? You could try using the plain make file instead.

**Comment by icraggs** [comment]
No further info
