### ISSUE TITLE
timeb.h not found, replace with alternative

### ISSUE THREAD

**Issue by BenShen98** [eclipse/paho.mqtt.c#1367]
**Is your feature request related to a problem? Please describe.**
[timeb.h is no longer provided by the GNU C library](https://man7.org/linux/man-pages/man3/ftime.3.html#:~:text=NOTE%3A%20This%20function%20is%20no%20longer%20provided%20by%20the%20GNU%20C%20library.%0A%20%20%20%20%20%20%20Use%20clock_gettime(2)%20instead.) and it is also removed in Android NDK r10.

**Describe the solution you'd like**
Should it be switched to use `clock_getres`, `clock_gettime` or `clock_settime` as the Linux manual suggest? 

I am happy to implement the change if that is desired

**Comment by icraggs** [comment]
Hello. Yes, if you would like to submit a PR with the change, I'll look at it. 

clock_gettime is used elsewhere (MQTTTime.c and Thread.c), so switching to that would be probably the best option for Linux. Windows doesn't have clock_gettime, so we can stick with the existing code for that.

**Comment by icraggs** [comment]
Looking at the code I think on non-windows platforms we default to gettimeofday anyway. So this seems to be catered for already.

**Comment by icraggs** [comment]
I think this is done already unless it's used somewhere I haven't spotted.
