### ISSUE TITLE
Crash occurred while using mqttv1.3.1

### ISSUE THREAD

**Issue by wshhja** [eclipse/paho.mqtt.c#1370]
**Describe the bug**
Crash occurred while using mqttv1.3.1,bracetrace:
#0  Socket_getReadySocket (more_work=more_work@entry=0, tp=tp@entry=0x7f557fe818, 
    mutex=mutex@entry=0x7f9d1ba710 <socket_mutex_store>) at src/Socket.c:249
#1  0x0000007f9d102d70 in MQTTAsync_cycle (rc=0x7f557fe878, timeout=1000, sock=0x7f557fe87c) at src/MQTTAsync.c:3754
#2  MQTTAsync_receiveThread (n=<optimized out>) at src/MQTTAsync.c:2150
#3  0x0000007f9b47efc4 in start_thread (arg=0x7f9d102c48 <MQTTAsync_receiveThread>) at pthread_create.c:335
#4  0x0000007f9b19b410 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:89

**I have tried print the variable s in Socket.c,but all the pointer is null, I'm not sure if this is normal.**

I found a similar bug before #1290  but my issue is not same as it. How can i fix the crash?

**To Reproduce**
Take a library trace as outlined in the README, and/or have a program or describe the steps to reproduce the behavior:
use paho.mqtt.cpp-1.1, create an async_client and connect, then crashed.

**Expected behavior**
The connection create correctly

**Screenshots**

**Log files**
Please try to attach log files rather than pasting the log contents. It makes the issues easier to read.

** Environment (please complete the following information):**
 - OS: [e.g. Linux aarch64]
 - Version []

**Additional context**

**Comment by icraggs** [comment]
You could start by supplying some more information as suggested in the issue template - a library trace or test program, or details of the scenario. The version of the client code and the OS and architecture (ARM?). Did you cross compile or do it natively?

If you're just creating a client and connecting. then there's probably something else going on. A client library trace is probably the best option given that you're using the C++ client.

**Comment by icraggs** [comment]
No more info.
