### ISSUE TITLE
readInt in MQTTPacket.c returns badness

### ISSUE THREAD

**Issue by december1981** [eclipse/paho.mqtt.c#1372]
This fixed it for me. Otherwise, what should return, say, 128 ends up returning -128, because of anomolous sign extension from the lower byte of the integer.

```c++
--- a/src/MQTTPacket.c
+++ b/src/MQTTPacket.c
@@ -362,7 +362,7 @@ exit:
 int readInt(char** pptr)
 {
        char *ptr = *pptr;
-       int val = ((((uint32_t)ptr[0]) << 8) | ((uint32_t)ptr[1]));
+       int val = ((((uint32_t)ptr[0]) << 8) | (uint8_t)ptr[1]);
        *pptr += 2;
        return val;
 }
```

**Comment by icraggs** [comment]
Thanks.

Ref: https://github.com/eclipse/paho.mqtt.c/pull/1327. I may revert that change and put my own in.

**Comment by icraggs** [comment]
I've reverted that PR, so hopefully should work now.

**Comment by december1981** [comment]
Then I'll close this
