### ISSUE TITLE
Unable to connect over websocket

### ISSUE THREAD

**Issue by sudipto1995** [eclipse/paho.mqtt.c#1385]
**Describe the bug**
Unable to connect to a server over unsecure websocket.

**To Reproduce**
`#include "MQTTAsync.h"

#define ADDRESS     "ws://rfdab.rfmondial.com:80"
//#define ADDRESS1     "ws://rfdab.rfmondial.com/mqtt/:80"
#define CLIENTID    "mqttsampletest"
#define TOPIC       "testtopic/sample/topic"
#define PAYLOAD     "Hello World!"
#define QOS         1
#define TIMEOUT     10000L

int finished = 0;

void connlost(void* context, char* cause)
{
    MQTTAsync client = (MQTTAsync)context;
    MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;
    int rc;

    printf("\nConnection lost\n");
    printf("     cause: %s\n", cause);

    printf("Reconnecting\n");
    conn_opts.keepAliveInterval = 20;
    conn_opts.cleansession = 1;
    if ((rc = MQTTAsync_connect(client, &conn_opts)) != MQTTASYNC_SUCCESS)
    {
        printf("Failed to start connect, return code %d\n", rc);
        finished = 1;
    }
}

void onConnectFailure(void* context, MQTTAsync_failureData* response)
{
    printf("Connect failed, rc %d\n", response ? response->code : 0);
    finished = 1;
}

void onConnect(void* context, MQTTAsync_successData* response)
{
    MQTTAsync client = (MQTTAsync)context;
    MQTTAsync_responseOptions opts = MQTTAsync_responseOptions_initializer;
    MQTTAsync_message pubmsg = MQTTAsync_message_initializer;
    int rc;

    printf("Successful connection\n");
    opts.context = client;
    pubmsg.payload = (char**)&PAYLOAD;
    pubmsg.payloadlen = (int)strlen(PAYLOAD);
    pubmsg.qos = QOS;
    pubmsg.retained = 0;
    if ((rc = MQTTAsync_sendMessage(client, TOPIC, &pubmsg, &opts)) != MQTTASYNC_SUCCESS)
    {
        printf("Failed to start sendMessage, return code %d\n", rc);
        exit(EXIT_FAILURE);
    }
}

int messageArrived(void* context, char* topicName, int topicLen, MQTTAsync_message* m)
{
    // not expecting any messages
    return 1;
}

int main(int argc, char* argv[])
{
    MQTTAsync client;
    MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer_ws;
    int rc;

    if ((rc = MQTTAsync_create(&client, ADDRESS, CLIENTID, MQTTCLIENT_PERSISTENCE_NONE, NULL)) != MQTTASYNC_SUCCESS)
    {
        printf("Failed to create client object, return code %d\n", rc);
        exit(EXIT_FAILURE);
    }

    if ((rc = MQTTAsync_setCallbacks(client, NULL, connlost, messageArrived, NULL)) != MQTTASYNC_SUCCESS)
    {
        printf("Failed to set callback, return code %d\n", rc);
        exit(EXIT_FAILURE);
    }
    
    conn_opts.keepAliveInterval = 60;
    conn_opts.cleansession = 1;
    conn_opts.onSuccess = onConnect;
    conn_opts.onFailure = onConnectFailure;
    conn_opts.context = client;
    conn_opts.username = "anon";
    conn_opts.password = "anon";
    
    if ((rc = MQTTAsync_connect(client, &conn_opts)) != MQTTASYNC_SUCCESS)
    {
        printf("Failed to start connect, return code %d\n", rc);
        exit(EXIT_FAILURE);
    }

    printf("Waiting for publication of %s\n"
        "on topic %s for client with ClientID: %s\n",
        PAYLOAD, TOPIC, CLIENTID);
    while (!finished)
#if defined(_WIN32)
        Sleep(100);
#else
        usleep(10000L);
#endif

    MQTTAsync_destroy(&client);
    return rc;
}`

**Expected behavior**
Successfully send message on the Topic.

**Screenshots**
Here, a screenshot the WireShark log
<img width="932" alt="websocket-wireshark" src="https://github.com/eclipse/paho.mqtt.c/assets/74963456/a1bc0b6b-9310-44a4-acac-4b4dfbb2b90c">

(Blacked the IP address of my machine)

**Log files**
[mqttlogs.txt](https://github.com/eclipse/paho.mqtt.c/files/12259915/mqttlogs.txt)

** Environment (please complete the following information):**
 - OS: Windows
 - Version 11

**Additional context**
Using the latest paho-mqtt3a library

Note: I am able to connect to the server using MQTT explorer using the server id - "ws://rfdab.rfmondial.com/mqtt/". If I try to use the same server ID in my code, I am getting add resolution error. Therefore, removing the "/mqtt/" part from the address in the code.

**Comment by icraggs** [comment]
The trace looks like there's no response from the server and the connection times out. Does the server expect the mqtt path on the URL? 

I can't tell from this info what might be the issue. I would try a number of different URL formats. And what version of the library specifically are you using (the trace would say but you've cut that bit off).

**Comment by sudipto1995** [comment]
Yes, I was able to resolve the issue by specifying the path after the port number in the URL in this format - 
protocol://hostname:port/path

instead of protocol://hostname/path:port
