### ISSUE TITLE
possible error with read&write Int/Int4 error

### ISSUE THREAD

**Issue by jumoog** [eclipse/paho.mqtt.c#1403]
I'm creating this Bug reported because of the comment on a commit by @bxShop (in case @icraggs missed it)

> when publish qos1 message with Packet Identifier 0x00 0x80，this will decoded to a wrong msgid -128，caused the async api `Blocking publish on queue full for client`。
> 
> int readInt(char** pptr) { ... int val = ((((uint8_t)ptr[0]) << 8) | ((uint8_t)ptr[1])); ... }

https://github.com/eclipse/paho.mqtt.c/commit/ed07139291d182fa0e2a24ecb018a1647a020b3d#commitcomment-127929331

**Comment by icraggs** [comment]
I've just reverted that PR. readInt4 and writeInt4 have been changed to return and take unsigned ints rather than ints, so that may help the original issue.
