### ISSUE TITLE
what causes the ping packet to be 68 bytes, very large

### ISSUE THREAD

**Issue by ou2363762938** [eclipse/paho.mqtt.c#1408]
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=2547356630925306610 skey=@crypt_b8cf3c7e_e92469d0b4cf4036b4d91beeaf4ae2ce mmweb_appid=wx_webfilehelper](https://github.com/eclipse/paho.mqtt.c/assets/46561484/d15a74a2-c34f-4617-9320-085e01960f8a)

**Comment by icraggs** [comment]
It's better to ask this question in a TCP or wireshark forum. You can see that the TCP payload is 2 bytes, which is the MQTT data.

**Comment by icraggs** [comment]
I think this question is answered - it's the TCP overhead.
