### ISSUE TITLE
arm win11 load dll  error!!!!

### ISSUE THREAD

**Issue by zghnx** [eclipse/paho.mqtt.c#1410]
eclipse-paho-mqtt-c-win32-1.3.13

![image](https://github.com/eclipse/paho.mqtt.c/assets/80946720/76beff9b-068e-4d6a-9348-82219918d84f)

**Comment by icraggs** [comment]
I don't know what the "arm" means in the issue title, but the pre-built DLLs and applications are for Intel architecture, not ARM (if that's what it means).

**Comment by icraggs** [comment]
I just tried this on Windows 10 and it worked.

**Comment by icraggs** [comment]
I think this is working.
