### ISSUE TITLE
MQTTAsync Client doesn't work outside of OnConnect

### ISSUE THREAD

**Issue by ffreality** [eclipse/paho.mqtt.c#1515]
## Description
I am working on integrating `Paho MQTT C client` to `Unreal Engine 5`. 
`Sync API` finished and working as expected.  After that I moved to `Async API` but I got this problem.

My class `declerations` are in here.
https://gist.github.com/ffreality/2f3bd21b8cb6e1eadfdca23f16ee8dee

My `definitions` are in here.
https://gist.github.com/ffreality/5b54415e80e76eacf75d01338cc6532c

As you see, I have a `MQTTAsync Client` in my header. I can publish a message in `OnConnect` callback function but when I want to access that `client` in other functions such as `MQTT_Async_Publish` (my custom function which have been exposed to UE5's blueprint interface), it says it is not connected and I can't publish anything.

`Sync API` doesn't have that problem.

I don't want to publish a message on in `OnConnect`.
I should do it whenever I call `MQTT Async Publish node` like this screenshot.

![image](https://github.com/user-attachments/assets/299df913-4caa-4879-b5b0-d6e0d53d192b)

## Expriments
I tried to move functions outside the AsyncTask but problem continues.

## Environment
 - OS: Windows 11
 - Version: Master

**Comment by icraggs** [comment]
It depends on how the synchronization is happening, I'm guessing. The MQTTClient_connect call is synchronous, only returning when the connect is complete. The MQTTAsync_connect call is only complete when the onSuccess (plus onConnect) or onFailure callback is invoked - if any other call is made before then, the Paho client will not be connected.

**Comment by ffreality** [comment]
great haste makes great waste... just added some delay and it worked !
