### ISSUE TITLE
MQTTAsync_disconnect throws access violation error

### ISSUE THREAD

**Issue by ffreality** [eclipse/paho.mqtt.c#1519]
## Description

As I mentioned before, I am working on sync and async versions of mqtt client plugin for Unreal Engine 5. I don't have any problem with Sync API including this issue.
For async one, I did client initialization, publish, subscribe and unsubscribe implementations.

But when I want to call `MQTTAsync_disconnect`, it gives `access violiation error` like from screenshot. My code is in below and as you can see, function tries to disconnect the client only when it connected. I know that that it actually connected because I can publish messages.

## Experiments
I tried to call this function with some delay to wait `OnConnect` callback's successful return.

I put `MQTTAsync_disconnect` inside to `try&catch` but it can't catch anything. (I built library with `RelWithDebInfo` option)

## Sample Code
```
void AMQTT_Manager_Paho_Async::MQTT_Async_Destroy()
{
	if (!this->Client)
	{
		return;
	}
	
	if (MQTTAsync_isConnected(this->Client))
	{
		MQTTAsync_disconnectOptions Disconnect_Options = MQTTAsync_disconnectOptions_initializer;
		Disconnect_Options.context = this;
		Disconnect_Options.timeout = 10000;

		if (this->Client_Params.Version == EMQTTVERSION_Async::V_5)
		{
			Disconnect_Options.onSuccess5 = OnDisconnect5;
			Disconnect_Options.onFailure5 = OnDisconnectFailure5;
			Disconnect_Options.reasonCode = MQTTREASONCODE_DISCONNECT_WITH_WILL_MESSAGE;
		}

		else
		{
			Disconnect_Options.onSuccess = OnDisconnect;
			Disconnect_Options.onFailure = OnDisconnectFailure;
		}

		try
		{
			MQTTAsync_disconnect(&this->Client, &Disconnect_Options);
		}

		catch (const std::exception& Exception)
		{
			const FString ExceptionString = Exception.what();
			UE_LOG(LogTemp, Warning, TEXT("Disconnect exception : %s"), *ExceptionString);
		}
	}

	MQTTAsync_destroy(&this->Client);
}
```

## Screenshots

![image](https://github.com/user-attachments/assets/4284dcb9-6121-4b61-a1fa-8046bc173776)

## Environment
 - OS: Windows 11
 - Version: Master - CMake RelWithDebInfo Build

**Comment by ffreality** [comment]
any suggestions ?

**Comment by icraggs** [comment]
You have the address operator & in front of this->Client in the disconnect call. I'm guessing that's not right?

**Comment by ffreality** [comment]
> You have the address operator & in front of this->Client in the disconnect call. I'm guessing that's not right?

sometimes I feel really stupid.
Anyway. UE5 client plugins are ready.
https://github.com/FF-Plugins-Active/FF_MQTT_Sync
https://github.com/FF-Plugins-Active/FF_MQTT_Async
