### ISSUE TITLE
Is there a freertos version that supports mqttv5？

### ISSUE THREAD

**Issue by huaconghe** [eclipse/paho.mqtt.c#1526]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by icraggs** [comment]
FreeRTOS has its own MQTT client, which I'm guessing from your question does not support MQTT 5.0. I've no plans to create one myself - I suggest you ask FreeRTOS support.

**Comment by icraggs** [comment]
Answered.
