### ISSUE TITLE
dlclose@GLIBC_2.17 error

### ISSUE THREAD

**Issue by zheyuejiang12** [eclipse/paho.mqtt.c#1527]
ln -s libpaho-mqtt3as.so.1.0  build/output/libpaho-mqtt3as.so.1
ln -s libpaho-mqtt3as.so.1 build/output/libpaho-mqtt3as.so
/opt/gcc-ubuntu-9.3.0-2020.03-x86_64-aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc  -I src -lpthread -L build/output -L /home/zheyuejiang/Desktop/mqtt/openssl/lib -o build/output/paho_c_version -lpaho-mqtt3a src/MQTTVersion.c -ldl
/opt/gcc-ubuntu-9.3.0-2020.03-x86_64-aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc -o build/output/samples/MQTTClient_publish src/samples/MQTTClient_publish.c -lpaho-mqtt3cs  -I src -Wl,--start-group -lpthread -lssl -lcrypto -Wl,--end-group -L build/output -L /home/zheyuejiang/Desktop/mqtt/openssl/lib 
/opt/gcc-ubuntu-9.3.0-2020.03-x86_64-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: warning: libdl.so.2, needed by /home/zheyuejiang/Desktop/mqtt/openssl/lib/libcrypto.so, not found (try using -rpath or -rpath-link)
/opt/gcc-ubuntu-9.3.0-2020.03-x86_64-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: /home/zheyuejiang/Desktop/mqtt/openssl/lib/libcrypto.so: undefined reference to `dlopen@GLIBC_2.17'
/opt/gcc-ubuntu-9.3.0-2020.03-x86_64-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: /home/zheyuejiang/Desktop/mqtt/openssl/lib/libcrypto.so: undefined reference to `dlsym@GLIBC_2.17'
/opt/gcc-ubuntu-9.3.0-2020.03-x86_64-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: /home/zheyuejiang/Desktop/mqtt/openssl/lib/libcrypto.so: undefined reference to `dlclose@GLIBC_2.17'
/opt/gcc-ubuntu-9.3.0-2020.03-x86_64-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: /home/zheyuejiang/Desktop/mqtt/openssl/lib/libcrypto.so: undefined reference to `dladdr@GLIBC_2.17'
/opt/gcc-ubuntu-9.3.0-2020.03-x86_64-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: /home/zheyuejiang/Desktop/mqtt/openssl/lib/libcrypto.so: undefined reference to `dlerror@GLIBC_2.17'
collect2: error: ld returned 1 exit status
Makefile:238: recipe for target 'build/output/samples/MQTTClient_publish' failed
make: *** [build/output/samples/MQTTClient_publish] Error 1

**Comment by icraggs** [comment]
Are you cross compiling? If not how are you building?
