### ISSUE TITLE
Docs link is not working

### ISSUE THREAD

**Issue by RohanDoshi21** [eclipse/paho.mqtt.c#1538]
[https://eclipse.github.io/paho.mqtt.c/](https://eclipse.github.io/paho.mqtt.c/) is not working

**Comment by icraggs** [comment]
Thanks, I'll look into it.

**Comment by icraggs** [comment]
It should be working again now. The updated URL is https://eclipse-paho.github.io/paho.mqtt.c/ as a new Github organization was created. 

I've changed the references that I know of, but I expect there are more. If there are any more you find, if you let me know that would be great. (Any branch other than master, I still need to change the README, for one).

**Comment by RohanDoshi21** [comment]
Thanks, would report any other broken references.
