### ISSUE TITLE
MQTTAsync_traceCallback add void* context

### ISSUE THREAD

**Issue by SeaAndSand** [eclipse/paho.mqtt.c#1545]
typedef void MQTTAsync_traceCallback(enum MQTTASYNC_TRACE_LEVELS level, char* message);
LIBMQTT_API void MQTTAsync_setTraceCallback(MQTTAsync_traceCallback* callback);

Can the log callback function add a void* context pointer? My program will create several clients, and I am worried that the prints will be indistinguishable.

**Comment by icraggs** [comment]
Would that help? 

The background threads deal with all the client objects, so in many cases a trace entry can't be associated with a particular client. There is only one call to set a trace callback, so the context would be the same for all entries.

The protocol messages, sending and receiving of packets already include the MQTT clientID and socket ID.
